if(!CBC)var CBC={};CBC.namespace=function(){var c=arguments,a=null,b,d,f;for(b=0;b<c.length;b+=1){f=(""+c[b]).split(".");a=this;for(d="CBC"==f[0]?1:0;d<f.length;d+=1)a[f[d]]=a[f[d]]||{},a=a[f[d]]}return a};CBC.SETTINGS||(CBC.SETTINGS=function(){var c=[];return{getVal:function(a){return c[a]},setVal:function(a,b){c[a]=b}}}());
CBC.namespace("APP").Instances=function(){var c={};return{get:function(a){return a=="all"?c:c[a]},add:function(a,b){if(!c[a]){c[a]=b;return c[a]}return false},test:function(a){if(c[a]){alert("An instance of name '"+a+"' has already been defined.  Please pick another instance name.");return true}return false}}}();
YUI.add("cbc_core",function(c){c.namespace("CBC.Util");c.CBC.Util=function(){return{getObjectFromCookie:function(a){var b={},d=c.Cookie.get(a);if(!d)return null;for(var d=d.split("&"),f=0;f<d.length;f++){a=d[f].split("=");a[0]=a[0].replace(/\s/,"");b[a[0]]=a[1]}return b},getExpiry:function(a){var b=new Date;return b.setTime(b.getTime()+a*864E5)},changeCookieProperty:function(a,b,d,f){var g={path:"/",domain:"cbc.ca"};if(c.Cookie.get(a)){var e=this.getObjectFromCookie(a);e[b]=d;b=this.objToQueryString(e);
if(f)g.expires=new Date(f);c.Cookie.set(a,b,g)}else{if(f)g.expires=new Date(f);c.Cookie.set(a,b+"="+d,g)}},readCookieProperty:function(a,b){return!c.Cookie.get(a)?null:this.getObjectFromCookie(a)[b]},changeSessionCookieProperty:function(a,b){this.changeCookieProperty("cbcsession",a,b)},readSessionCookieProperty:function(a){return this.readCookieProperty("cbcsession",a)},queryStringToObj:function(a){for(var a=a.split(/[;&]/),b={},d=0;d<a.length;d++){var f=a[d].split("="),c=unescape(f[0].toLowerCase()),
f=unescape(f[1]).replace(/\+/g," ");c.length>0&&f.length>0&&(b[c]=f)}return b},objToQueryString:function(a){var b="",d=0,f;for(f in a){d>0&&(b=b+"&");b=b+(f+"="+a[f]);d++}return b},isLoggedIn:function(){return c.Cookie.get("at")&&c.Cookie.get("pd")?true:false},signUp:function(a){var b,d;if(a&&a.cb)b=a.cb;if(a&&a.iname)d=a.iname;c.use("cbc_auth",function(a){if(!c)var c=new a.CBC.Util.Auth;c.spawnRegister({Y:a,cb:b,iname:d});CBC.APP.Instances.add("authwrap",c)})},logIn:function(a){var b,d;if(a&&a.cb)b=
a.cb;if(a&&a.iname)d=a.iname;c.use("cbc_auth",function(a){if(!c)var c=new a.CBC.Util.Auth;c.spawnLogin({Y:a,cb:b,iname:d});CBC.APP.Instances.add("authwrap",c)})},getLoggedInUserId:function(){return this.isLoggedIn()?this.readCookieProperty("at","u"):-1},scrollToNode:function(a,b){typeof a=="string"&&(a=c.one("#"+a));b=b?b:20;c.use("anim",function(d){d=new d.Anim({node:d.one("window"),duration:0.8,to:{scroll:[0,parseInt(a.get("region").top,10)-b]},easing:d.Easing.easeOut});d.run();return d})},Template:function(a){if(a){this.sourceString=
a;this.evaluate=function(a,d){var c=this.sourceString;try{if(d)for(var g in d){var e=RegExp("\\["+g+": \\{(.*?)\\}\\]","i"),i=e.exec(c);if(i)for(var l=i[0],j=i[1].split("||"),h=0;h<j.length;h++)j[h].match(d[g]+":")&&(c=c.replace("#"+l,j[h].substr(j[h].indexOf(":")+1,j[h].length)))}if(a!=null)for(g in a){var e=RegExp("#{("+g+")}","gm"),k=a[g];typeof a[g]=="string"&&(k=k.replace(/\$/g,"&#36;"));c=c.replace(e,k)}return c}catch(m){return""}}}},ucfirst:function(a){return a.toString().substr(0,1).toUpperCase()+
a.substr(1)},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},utc_days:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],utc_months:["January","February","March","April","May","June","July","August","September","October","November","December"],getGMTOffset:function(){var a=new Date,b=a.getFullYear(),d=Math.floor(1+b*5/4)%7,c=new Date(b+"/11/"+(7-d)+" 01:59");return a>new Date(b+"/03/"+(14-d)+" 01:59")&&a<c?-4:-5},getTimeDifference:function(a){try{var b=new Date,c=this.getGMTOffset(),
f=b.getTime(),g=b.getTimezoneOffset()*6E4,b=f+g+36E5*c,a=new Date(a),e=(Date.parse((new Date(b)).toUTCString())-Date.parse(a.toUTCString()))/1E3;if(e/3.155692597632E7>1){_split=(e/3.155692597632E7).toString().split(".");e=_split[0]+(_split[1].substring(0,1)=="0"?"":"."+_split[1].substring(0,1));e=e+(e>1?" years":" year")}else if(e/2629743.8313599997>1){e=Math.round(e/2629743.8313599997);e=e+(e>1?" months":" month")}else if(e/60>60){e=Math.round(e/3600);if(e>23){e=Math.round(e/24);e=e+(e>1?" days":
" day")}else e=e+(e>1?" hours":" hour")}else if(e>60){e=Math.round(e/60);e=e+(e>1?" minutes":" minute")}else{e=Math.round(e);e=e+(e>1?" seconds":" second")}return e}catch(i){this.debug(i);return""}},debug:function(a){typeof console!="undefined"&&console.log(a)},print:function(a){typeof console!="undefined"?console.log(a):alert(a)}}}});