//# sourceMappingURL=mtm.js.map
(function(n,p,K,R,yb,E,y,L,t){if(n.opener&&"mzbtVisualTagPlacerWindow"==n.name.substring(0,25)){var ja=p.createElement("script");ja.src="//d36wtdrdo22bqa.cloudfront.net/scripts/visual-tag-placer/app.js";ja.id="mzbtScript";ja.className="fromMtm";p.getElementsByTagName("head")[0].appendChild(ja)}else{n.__mtm_data=n.__mtm_data||[];n.__mtm_spy=0;var S=function(){return(new y).getTime()},zb=String(S())+"."+Math.random(),H={},Pa=function(a){return a.replace(/&(?!\w+;)/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,
"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},Z=function(a){return a.replace(/[\\'"]/g,"\\$&").replace(/<\//g,"<\\/").replace(/\x3c!--/g,"<\\!--").replace(/\/>/g,"/\\>")},Ab=/<script[>\s\r\n][.\r\n]*?<\/script\b/gi,Bb=/<script[>\s\r\n]\b[.\r\n]*?>/i,Qa=function(a){return a.replace(/\\([\!"#$%&'\(\)\*\+,\.\/:;<=>\?\@\[\\\]\^`\{\|\}~])/g,"$1")},wa=function(a){a+="=";for(var b=p.cookie.split(/\s*;\s*/),c=0,d=b.length;c<d;c++){var e=b[c];if(0==e.indexOf(a))return unescape(e.substring(a.length))}},
Ra="indexOf"in E.prototype?E.prototype.indexOf:function(a){for(var b=0,c=this.length;b!=c;b++)if(this[b]===a)return b;return-1},Cb=p.getElementsByClassName?function(a,b){return a.getElementsByClassName(b)}:function(a,b){for(var c=a.getElementsByTagName("*"),d=[],e=new L("(?:^|\\b)"+b+"(?:\\b|$)"),f=0,g=c.length;f<g;f++)e.test(c[f].className)&&d.push(c[f]);return d},xa=p.querySelector?function(a,b){return p[b?"querySelectorAll":"querySelector"](a)}:function(a,b){var c=p.body,d=a.match(/(?:[^#\\]|\\.)*#((?:[^#\.\s\\]|\\[^\s])+).*?\s(.*$)/g),
e=d&&d[1];e&&(c=c.getElementById(Qa(e)),a=d[2].trim());for(var e="string"===typeof a?a:a.split(/\s+/),f=[c],g=e.length,h=0;h<g;h++)if(d=e[h].match(/^([^\.])?(\..+$|$)/g)){var k=d[1],d=d[2];k&&(k=k.toLowerCase());if(d){if(d=Qa(d).replace(/\./g," "),f=c.getElementsByClassName(d),k){for(var d=[],l=0,x=f.length;l!=x;l++){var c=f[l],q=c.tagName;q&&q.toLowerCase()==k&&d.push(c)}f=d}}else k&&(f=c.getElementsByTagName(k));if(1===f.length)break}return b?f:f[0]},Db="CSS1Compat"==p.compatMode,Sa=function(){var a=
n.pageYOffset;return a===t?(Db?p.documentElement:p.body).scrollTop:a},Eb=n.requestAnimationFrame||n.webkitRequestAnimationFrame||n.mozRequestAnimationFrame||function(a){__mtm_tags._overriddenAPIs.setTimeout(a,1E3/60)},Fb={},ka=function(a){return Fb[a]||"//"+__mtm[1]+"/module-"+a+".js"};n.__mtm_load=function(a,b,c){if(b){var d;if("undefined"!=typeof XMLHttpRequest)d=new XMLHttpRequest;else try{d=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{d=new ActiveXObject("Microsoft.XMLHTTP")}catch(f){return}}d.open("GET",
a,!0);d.onreadystatechange=function(){if(4==d.readyState&&200==d.status){var a=p.createElement("div");__mtm_tags._overriddenAPIs.innerHTMLSetter(a,d.responseText);p.getElementsByTagName("body")[0].appendChild(a)}};d.send(null)}else b=p.createElement("script"),b.async=1,c&&(b.onerror=c,b.onreadystatechange=function(){var a=this.readyState;"complete"!=a&&"loaded"!=a||__mtm_tags._overriddenAPIs.setTimeout(c,0)}),b.src=a,a=p.getElementsByTagName("script")[0],(a.parentNode||p.body).insertBefore(b,a)};
for(var $={},za=function(a,b,c){if($[b])$[b].push(c);else{$[b]=[c];var d=function(a,c){var d=$[b];if(d){delete $[b];for(var h=0,k=d.length;h!=k;h++)d[h](a,c)}};ya[b]=function(a){d(t,a)};__mtm_load(a,0,function(a){d(a)})}},aa=function(a,b,c){function d(){++e>=g&&c()}if(a&&a.length)for(var e=0,f=0,g=a.length;f<g;f++)b(a[f],d);else c()},Gb=(1<<32)-1||-1,Hb=0,Ta=function(a,b,c,d,e,f,g){var h=c.length,k=(h-1>>5)+1,l=new E(k);d&&(d=h&31)&&(l[k-1]=~((1<<d)-1));var x=g(l,k),q=Hb++;a=a?a.concat(q):[q];b&&
(b.sel[q]=c.length);for(b=0;b<h;b++)e(a,c[b],function(a){var b=a>>5,c=1<<(a&31);return function(a,d){a!==t&&(l[b]=a?(l[b]||0)|c:(l[b]||0)&~c,d.ch[q]=1);--d.sel[q]||(d.ch[q]?x(d):f(t,d))}}(b))},Ua=function(a,b,c,d,e){Ta(a,b,c,1,d,e,function(a,b){return function(c){for(var d=0;d!=b;d++)if(~a[d]&Gb){e(0,c);return}e(1,c)}})},Ib=function(a,b,c,d,e){Ta(a,b,c,0,d,e,function(a,b){return function(c){for(var d=0;d!=b;d++)if(a[d]){e(1,c);return}e(0,c)}})},Jb=function(a,b,c,d){Ua(a,b,c,function(a,b,c){b(a,c)},
d)},ba=new y,ca={},Aa={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11},Va={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6},B={},Kb=function(a,b){var c=b.rules,d=b.off,e=function(a,b,c){var e=0;if("u"===b||"g"===b||"z"===b)e=0;else if("s"===b)e=d;else{if("w"!==b&&b)throw"unknown type "+b;e=-Math.ceil(c[6]-d)}e*=6E4;return new y(a.getTime()+e)},f=function(a,b){var c=a[0],d=a[1],m=d[5],k;B[c]||(B[c]={});if(B[c][d])k=B[c][d];else{if(isNaN(d[4])){var f,g;"last"===d[4].substr(0,4)?
(k=new y(y.UTC(c,Aa[d[3]]+1,1,m[0]-24,m[1],m[2],0)),f=Va[d[4].substr(4,3)],g="<="):(k=new y(y.UTC(c,Aa[d[3]],d[4].substr(5),m[0],m[1],m[2],0)),f=Va[d[4].substr(0,3)],g=d[4].substr(3,2));var h=k.getUTCDay();">="===g?k.setUTCDate(k.getUTCDate()+(f-h+(f<h?7:0))):k.setUTCDate(k.getUTCDate()+(f-h-(f>h?7:0)))}else k=new y(y.UTC(c,Aa[d[3]],d[4],m[0],m[1],m[2],0));B[c][d]=k}b&&(k=e(k,m[4],b));return k},g=function(a,b){for(var c=[],d=0;b&&d<b.length;d++)b[d][0]<=a&&(b[d][1]>=a||b[d][0]===a&&"only"===b[d][1]||
"max"===b[d][1])&&c.push([a,b[d]]);return c},h=function(a,b,c){var d,m;a.constructor!==y?(d=a[0],m=a[1],a=!c&&B[d]&&B[d][m]?B[d][m]:f(a,c)):c&&(a=e(a,"w",c));b.constructor!==y?(d=b[0],m=b[1],b=!c&&B[d]&&B[d][m]?B[d][m]:f(b,c)):c&&(b=e(b,"w",c));return Number(a)-Number(b)},k=a.getUTCFullYear(),l;l=g(k,c);l.push(a);l.sort(h);2>Ra.call(l,a)&&(l=l.concat(g(k-1,c)),l.sort(h));c=Ra.call(l,a);return 1<c&&0>h(a,l[c-1],l[c-2][1])?l[c-2][1]:0<c&&c<l.length-1&&0<h(a,l[c+1],l[c-1][1])?l[c+1][1]:0===c?null:l[c-
1][1]},Wa=function(a,b){if(null===b)return a;var c=a.getTime(),d;for(d=b.length-1;0<=d&&!(b[d].since&&b[d].since<c);d--);var e=b[d+1];d=e.off;(e=Kb(a,e))&&(d=-Math.ceil(e[6]-d));return(d=a.getTimezoneOffset()-d)?new y(c+6E4*d):a},Xa=function(a){a=a.split(/[:\s-]/);return new y(a[0],parseInt(a[1],10)-1,a[2],a[3]||0,a[4]||0,a[5]||0)},Lb={minute:"Minutes",hour:"Hours",day:"Date",month:"Month",year:"FullYear",dayOfWeek:"Day"},Ba=function(a,b){if(!a)return 1;var c=a.length;if(!c)return 1;for(var d=0;d!=
c;d++){var e=a[d],f;a:{f=e.period;var g=b;if(f){g=g.getTime();if("string"==typeof f.from&&Xa(f.from).getTime()>g){f=!1;break a}if("string"==typeof f.to&&Xa(f.to).getTime()<g){f=!1;break a}}f=!0}if(f)a:{e=e.rules;f=b;if(e)b:for(g in g=void 0,e){var h=e[g],k=f["get"+Lb[g]]();if("*"!=h){for(var h=h.split(/,/),l=0,x=h.length;l<x;l++){var q=h[l].split(/-/),r=parseInt(q[0],10);if(!(r>k)){if(r==k)continue b;if(1!=q.length&&parseInt(q[1],10)>=k)continue b}}f=0;break a}}f=1}if(f)return 1}return 0},T={},G=
{},U={},Ca={},ma=function(a){if(O[a]){for(var b={},c=0,d=O[a].length;c!=d;c++)O[a][c](b);delete O[a]}U[a]=1;if(d=G[a]){var b=[],c=!0,e;for(e in d)if(d=T[e])--d[1]?c=!1:(b.push([d[0],e,d[1]]),delete T[e]);b.length&&da(b)();c&&delete G[a]}},ea={"var":{},ev:{},"":{},dom:{},tag:{}},Mb=0,M=function(a,b,c,d){var e=ea[a],f=e[b];f||(setTimeout(function(){v("","+",{g:a,k:b})},0),e[b]=f={sel:{},selChildren:{},cb:{}});e=Mb++;f.cb[e]=[c,d];if(d){c=f.sel;var f=f.selChildren,g=d.length-1,h=d[g];c[h]?c[h]++:c[h]=
1;var k=h;for(g--;0<=g;g--){var h=d[g],l=f[h];l?l[k]||(l[k]=1,c[h]++):(f[h]=l={},l[k]=1,c[h]=1);k=h}}return e},N=function(a,b,c){var d=ea[a][b],e;if(d&&(e=d.cb[c])){if(e=e[1]){var f=d.sel,g=d.selChildren,h=e.length-1,k=e[h];if(!--f[k]){delete f[k];var l=k;for(h--;!f[l]&&0<=h;h--){var k=e[h],x=g[k];x&&delete x[l];l=0;for(b in x)l++;l?f[k]=l:(delete g[k],delete f[k]);l=k}}}delete d.cb[c];for(b in d.cb)return 1;delete ea[a][b];v("","-",{g:a,k:b});return-1}},v=function(a,b,c){"ev"==a?ma(b):"tag"==a&&
"l"==b.charAt(0)&&ma("-"+b.substring(1));if(a=ea[a][b]){var d;b=a.sel;var e={};for(d in b)e[d]=b[d];c={sel:e,ch:{},ev:c};a=a.cb;for(d in a)a[d][0](c)}},P=p.addEventListener,na={},Nb=1,Q=function(a,b,c,d){var e=a.__mtm_eid;e||(na[a.__mtm_eid=e=Nb++]=[a,{}]);var f=na[e][1],g=b+"."+e;f[b]||(e=function(a){v("dom",g,a)},f[b]=e,P?a.addEventListener(b,e):a.attachEvent("on"+b,e));return M("dom",g,c,d)},V=function(a,b,c){var d=a.__mtm_eid;if(d&&0>N("dom",b+"."+d,c)){c=na[d][1];var e=c[b];P?a.removeEventListener(b,
e):a.detachEvent("on"+b,e);delete c[b];var f;for(d in c){f=1;break}if(!f)try{delete a.__mtm_eid,delete na[d]}catch(g){}}},Da,Ya,Ob=function(){if(!Ya){for(var a=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"],b=p.createElement("a"),c,d=0;5!=d;d++)if(b[c=a[d]]){Da=c;break}Ya=1}},oa=function(a,b){Ob();var c=function(a){return function(c){var d=c.ev.target;if(Da){if(d[Da](b)){a(c);return}}else for(var h=xa(b,1),k=0;k<h.length;k++)if(h[k]==d){a(c);return}a(c,
1)}},d;return{listen:function(b,f){d=Q(p,a,c(f),b)},stop:function(){V(p,a,d)}}},O={},pa=function(a){I?a():(O["mtm.dom"]||(O["mtm.dom"]=[]),O["mtm.dom"].push(a))},Pb=function(){for(var a=0,b=__mtm_data.length;a<b;a++){var c=__mtm_data[a],d;for(d in c)"event"==d?U[c.event]=1:"exec"==d?Za(c.exec):Ca[d]=c[d]}__mtm_data={push:function(a){for(var b in a)if("event"==b){var c=a.event;c&&"string"==typeof c&&"-"!=c[0]&&"mtm."!=c.substring(0,3)&&v("ev",c)}else"exec"==b?Za(a.exec):(Ca[b]=a[b],v("var",b))}}},
I=0,Ea=function(){v("ev","mtm.dom")},Qb=function(){var a=function(){P?(p.removeEventListener("DOMContentLoaded",b),n.removeEventListener("load",b)):(p.detachEvent("onreadystatechange",b),n.detachEvent("onload",b))},b=function(b){if(P||"load"===b.type||"complete"===p.readyState)I=1,a(),Ea()},c=p.readyState;if(I=P?"loading"!=c:"complete"==c)Ea();else if(P)p.addEventListener("DOMContentLoaded",b),n.addEventListener("load",b);else{p.attachEvent("onreadystatechange",b);n.attachEvent("onload",b);var d;
try{d=null==n.frameElement&&p.documentElement}catch(e){}d&&d.doScroll&&function g(){if(!I){try{d.doScroll("left")}catch(b){return __mtm_tags._overriddenAPIs.setTimeout(g,50)}I=1;a();Ea()}}()}},$a=["resize","scroll","load"],Fa=function(a){for(var b=new E(3),c=0;3!=c;c++)b[c]=Q(n,$a[c],a);return b},ab=function(a){for(var b=0;3!=b;b++)V(n,$a[b],a[b])},Rb=function(a){za("//tdi.mezzobit.com/locate","locate",function(b,c){var d=[];c&&(c.country&&(d.push("s"+c.country),c.region&&d.push("r"+c.country+c.region),
c.city&&d.push("c"+c.country+(c.region||"")+"-"+c.city.toLowerCase())),c.postal&&d.push("p"+c.postal),c.dma&&d.push("m"+c.dma));a(d)})},bb=function(a){var b=null,c;return function(d){null===b?c?c.push(d):(c=[d],za(ka(a),a,function(a,d){b=d;for(var g=0,h=c.length;g!=h;g++)c[g](a,d);c=null})):d(t,b)}},Sb=bb("uaparser"),Tb=function(a){return function(b){var c=b[1]||"name";return{get:function(b){Sb(function(e,f){b(f&&f[a][c]||null)})}}}},Ub=bb("blocksensing"),Vb={eq:function(a,b,c){return b.join?0<=b[0].indexOf(a)&&
(!b[1]||0>b[1].indexOf(a)):c?c(String(a))==c(String(b)):a==b},contains:function(a,b){return 0<=a.indexOf(b)},starts:function(a,b){return 0==a.indexOf(b)},ends:function(a,b){var c=a.lastIndexOf(b);return 0<=c&&c==a.length-b.length},matches:function(a,b){return null!==a.match(new L(b))},"matches-ci":function(a,b){return null!==a.match(new L(b,"i"))},lt:function(a,b,c){return c?c(String(a))<c(String(b)):a<b},le:function(a,b,c){return c?c(String(a))<=c(String(b)):a<=b},gt:function(a,b,c){return c?c(String(a))>
c(String(b)):a>b},ge:function(a,b,c){return c?c(String(a))>=c(String(b)):a>=b},"true":function(a){return a},"in":function(a,b,c){c&&(a=c(String(a)));for(var d=0,e=b.length;d<e;d++){var f=b[d];if(f.join){if(0<=f[0].indexOf(a)&&(!f[1]||0>f[1].indexOf(a)))return 1}else if((c?c(String(f)):f)==a)return 1}return 0}},Wb={lt:1,le:1,gt:1,ge:1},fa,cb,db=function(){var a=R.search;if(!fa||a!==cb){cb=a;var b=/\+/g,c=/([^&=]+)=?([^&]*)/g,d=a.substring(1);for(fa={};a=c.exec(d);)fa[decodeURIComponent(a[1].replace(b,
" "))]=decodeURIComponent(a[2].replace(b," "))}},eb=function(a){var b={};if(a)for(var c=0,d=a.length;c!=d;c++)b[a[c]]=1;return{sel:b,ch:{}}},qa,fb,Ga,gb,Xb=function(a,b){var c=M("","ps",a,b);if(!qa){var d=n.history;qa=d.pushState;d.pushState=fb=function(){qa.apply(this,arguments);v("","ps")};Ga=d.replaceState;d.replaceState=gb=function(){Ga.apply(this,arguments);v("","ps")}}return c},hb={URL:function(a,b){var c=a[1],d={};if(c&&"whole"!=c)switch(c){case "queryParam":d.get=function(a){db();a(fa[b.name])};
break;case "protocol":d.get=function(a){a(R.protocol.replace(/:$/,""))};break;default:d.get=function(a){a(R[c])}}else d.get=function(a){a(R.toString())};if(n.history){var e,f;d.listen=function(a,b){e=Q(n,"popstate",b,a);f=Xb(b,a)};d.stop=function(){V(n,"popstate",e);if(0>N("","ps",f)){var a=n.history;--pushStateCntr||(a.pushState==fb&&(a.pushState=qa),a.replaceState==gb&&(a.replaceState=Ga))}}}return d},UA:function(){return{get:function(a){a(K.userAgent)}}},Referrer:function(){return{get:function(a){a(p.referrer)}}},
Event:function(a,b){var c,d=b.name;return{listen:function(a,b){U[d]&&(b(),delete U[d]);c=M("ev",d,b,a)},stop:function(){N("ev",d,c)}}},Language:function(a){var b={get:function(b){var c=K.language||K.userLanguage||K.browserLanguage;b("string"==typeof c?("base"==a[1]?c.split(/[_-]/)[0]:c).toLowerCase():t)}};if(P){var c;b.listen=function(a,b){c=Q(n,"languagechange",b,a)};b.stop=function(){V(n,"languagechange",c)}}return b},Location:function(){return{get:Rb}},Const:function(a,b){return{get:function(a){a(b.value)}}},
Var:function(a,b){return{get:function(a){for(var d=b.name.split("."),e=n,f=0,g=d.length;f<g&&e!==t;f++)e=e[d[f]];a(e)}}},Code:function(a,b,c){return{get:function(a){var e=function(){var c;try{c=eval(b.code)}catch(e){n.console&&console.log(e)}a(c)};c?pa(e):e()}}},Data:function(a,b){var c,d=b.name;return{get:function(a){a(Ca[d])},listen:function(a,b){c=M("var",d,b,a)},stop:function(){N("var",d,c)}}},DOMText:function(a,b){return{get:function(a){pa(function(){var d=p.getElementById(b.id);a(d?d.innerHTML:
t)})}}},DOMAttr:function(a,b){return{get:function(a){pa(function(){var d=p.getElementById(b.id);a(d?d.getAttribute(b.attr):t)})}}},Rand:function(){return{get:function(a){a(String(Math.floor(4294967295*Math.random())))}}},Cookie:function(a,b){return{get:function(a){a(wa(b.cookie))}}},Click:function(a,b){return oa("click",b.sel)},FormSubmit:function(a,b){return oa("submit",b.sel)},InputChange:function(a,b){return oa("change",b.sel)},DOMEvent:function(a,b){return oa(b.ev,b.sel)},DOMLoaded:function(){var a;
return{get:function(a){a(I)},listen:function(b,c){a=M("ev","mtm.dom",c,b)},stop:function(){N("ev","mtm.dom",a)}}},Timer:function(a,b){var c;return{listen:function(a,e){c=__mtm_tags._overriddenAPIs.setInterval(function(){e(eb(a))},b.delay)},stop:function(){n.clearInterval(c)}}},ScrollDepth:function(){var a;return{get:function(a){a(Sa())},listen:function(b,c){a=Q(n,"scroll",c,b)},stop:function(){V(n,"scroll",a)}}},AdBlocking:function(){return{get:function(a){Ub(function(b,c){a(b||c?1:0)})}}}},ga={"URL.port":0,
"URL.protocol":2,"URL.hostname":2,Language:2,"Language.base":2,"Location.lon":1,"Location.lat":1,"Device.type":2,"Device.manufacturer":2,Rand:0,ScrollDepth:0},Yb=["Browser","OS","Device"],Zb=["major","minor","patch"],Ha=0;3!=Ha;Ha++){var W=Yb[Ha];hb[W]=Tb(W.toLowerCase());ga[W]=2;ga[W+".family"]=2;ga[W+".version"]=3;for(var Ia=0;3!=Ia;Ia++)ga[W+"."+Zb[Ia]]=0}var ib=[function(a){var b;try{b=parseInt(a,10)}catch(c){return}return isNaN(b)?t:b},function(a){var b;try{b=parseFloat(a)}catch(c){return}return isNaN(b)?
t:b},function(a){return a.toLowerCase()},function(a){a=a.split(".");for(var b=0,c=a.length;b!=c;b++){var d=a[b],e=d.length;6>e&&(a[b]=(new E(7-e)).join("0")+d)}return a.join(".")}],ac=function(a,b){if("s"==a)return{get:function(a){$b(b,function(){a(!0)})}};var c,d=a+b;return{listen:function(a,b){c=M("tag",d,b,a)},stop:function(){N("tag",d,c)}}},jb=function(a){if(a){var b=a.type.split(/\./),c=hb[b[0]];if(c)return c(b,a.params,a.visual)}},kb=function(a,b,c){if(a)if(a=a.get){var d=b&&b["default"];a(d!==
t?function(a){c(a||d)}:c)}else c();else c()},bc=function(a,b){kb(jb(a),a,b)},ob=function(a,b,c,d){if(a&&a.length){var e=n.__mtm_tags,f=e.rules,g={sel:{},ch:{}};Ib(0,g,a,function(a,d,l){(d=f[d])?Jb(a,g,[function(a,c){c(Ba(d.temporalConditions,ca[d.timezone||b]||ba),g)},function(a,b){d.probabilityCondition?d.probabilityCondition.calls?b(!(Math.random()*d.probabilityCondition.calls>=d.probabilityCondition.times),g):c(d,function(a){b(a||0,g)}):b(1,g)},function(a,b){if(d.pageConditions){var c=e.variables;
Ua(a,g,d.pageConditions,function(a,b,d){var k,e,f,h,l,q=b.comparator;(l=b.tag)?(h=ac(q.charAt(0),l),q=q.substring(1)):((f=b.variable)?(k=c[f],k.num&&(e=ib[1])):(e=ga[f=b.systemVariable],e!==t&&(e=ib[e]),k={type:f}),h=jb(k));var x,n,p,A,ra=Vb[q],F=Wb[q],v=b.value,y=b.negate,lb="tr"==q,Ka="nt"==q,mb=function(a){kb(h,k,function(b){if(lb||Ka)b===t||b?(n=1,d(lb,a)):d(t,a);else{var c=b instanceof E,m,k;c&&(k=b.length);if(x)if(c){if(p instanceof E&&k==p.length){var h;for(m=0;m<k;m++)if(b[m]!==p[m]){h=1;
break}if(!h){d(t,a);return}}}else if(b===p){d(t,a);return}p=b;var f=A;h=function(b){F&&f===A?d(t,a):(x=1,b&&(n=1),d(b,a))};if(c)for(m=0;m<k;m++){if(A=ra(b[m],v,e)){h(!y);return}}else if("string"==typeof b||"number"==typeof b||null==b){A=ra(null==b?"":b,v,e);h(y?!A:A);return}A=!1;h(y)}})};h.get?mb(g):d(0,g);var nb=b.once||Ka;if(h.listen&&(!n||!nb)){var sa=h.stop;if(Ka){var B=function(){__mtm_tags._overriddenAPIs.setTimeout(function(){n||(n=1,sa&&sa(),d(1,eb(a)))},v)};if(l){l="p"+l;var G=M("tag",l,
function(){N("tag",l,G);B()})}else B()}h.listen(a,function(a,b){if(nb&&(sa&&sa(),n)){d(t,a);return}b?d(t,a):mb(a)})}},b)}else b(1,g)}],l):l(0,g)},d)}else d(1)},X,dc=n.Proxy||"function"==typeof yb.observe,ec=function(a){return a instanceof E?"a"+a.map(function(a){return"\x00"+a}).join(""):a||""},fc=0,pb=function(a,b){if(dc&&a&&a.length){var c={},d=function(a,b,d,e){d=d[e];var f;if(d&&(f=d.length)){var g;(g=c[a])||(g=c[a]={id:fc++,npctx:b instanceof E?b.map(function(a){return new L(a)}):b?new L(b):
null});(a=g[e])||(a=g[e]={});for(e=0;e!=f;e++)a[d[e]]=1}},e=function(a,b){if(a[b]){var c=[],d;for(d in a[b])c.push(d);a[b]=new L("(?:"+c.join("|")+")")}},f=n.__mtm_tags,g=f.arrules;aa(a,function(a,b){(a=g[a])?ob(a.activationRules,f.timezone,function(a,b){b(!0)},function(c){if(c){c=a.context;var e=function(b){var c=ec(b);d(c,b,a,"actions");d(c,b,a,"urls");d(c,b,a,"scripts")};c instanceof E?c.forEach(e):e()}b()}):b()},function(){var a,d=[],f;for(f in c)d.push(a=c[f]),e(a,"urls"),e(a,"scripts");a?b(d):
b()})}else b()},qb=function(a,b,c,d){c||(c={});c.error=function(b){n.console&&console.log(b.msg?"ERROR from "+a+": "+b.msg:b);d&&d(b)};c.innerHTMLSetter=__mtm_tags._overriddenAPIs.innerHTMLSetter;b&&(c.done=b);return c},rb=function(a,b){var c=H[a].id;return function(){H[a].e=S();v("tag","_l",c);v("tag","l"+c);b()}},sb=function(a,b){var c=H[a].id;return qb("tag "+c,b,{mtmsid:a},function(a){v("tag","_e",c)})},tb=function(a,b){return sb(a,rb(a,b))},Za=function(a){"string"==typeof a&&(a={code:a.code});
ha(a.loc?"string"==typeof a.loc?p.getElementById(a.loc):a.loc:p.getElementsByTagName("body")[0]||p.getElementsByTagName("head")[0],a.code,qb("user code",a.callback))},ta=function(a,b){var c=a.split(/::/),d=c[0],e;try{e=xa(d,b)}catch(f){}return(b?e.length:e)?[e,d,c[1]]:[]},ub=function(a,b,c,d,e,f){var g=!1,h=b.place;if(h&&"string"==typeof b.code){var k=b.selector;!k&&(k=ta(h.sel,h.multi),k.length||f===t)&&(b.selector=k);if(!k.length)g=f||!1;else if(!(g=e[c])){f=k[0];h.multi||(f=[f]);g=-1;h=0;for(k=
f.length;h!=k;h++){var l=f[h].getBoundingClientRect(),l=Math.abs((l.top+l.bottom>>1)-a);if(0>g||l<g)g=l}e[c]=g}!1!==g&&(d[b.id]=g)}if(b=G["-"+c])for(var x in b)ub(a,T[x][0],x,d,e,g)},vb=function(a,b,c,d){if(b.metric)return b.metric;var e={};ub(a,b,c,e,d);a=0;for(var f in e)a+=e[f]?1/e[f]:1;return b.metric=a},gc=function(a,b){var c=p.createElement("span"),d=b.parentNode;switch(a){case "before":return d.insertBefore(c,b);case "after":return b.nextSibling?d.insertBefore(c,b.nextSibling):d.appendChild(c);
case "-mzbt-prepend":if(b.firstChild)return b.insertBefore(c,b.firstChild);default:return b.appendChild(c)}},wb={},ua={},$b=function(a,b){if(wb[a])b();else if(ua[a])ua[a].push(b);else{var c=[b];ua[a]=c;pa(function(){J.when(a,function(b){var e=b.place;if(e){var f=b.selector,g=e.multi;f||(f=ta(e.sel,g),f.length&&(b.selector=f));if(f.length){var h=f[0];if(h){g||(h=[h]);var k;b=function(){for(var b=n.innerWidth||p.documentElement.clientWidth,d=n.innerHeight||p.documentElement.clientHeight,e=0,f=h.length;e!=
f;e++){var g=h[e];if(g.clientWidth||g.clientHeight)if(g=g.getBoundingClientRect(),g.top<d&&0<=g.bottom&&g.left<b&&0<=g.right){wb[a]=!0;ab(k);delete ua[a];b=0;for(d=c.length;b!=d;b++)c[b]();break}}};k=Fa(b);b()}}}})})}},La={},va={},Y=function(a,b,c){var d=J[b];if(d)for(var e in a){var f=a[e];e=e.split(".");for(var g=d,h=0,k=e.length;g&&h!=k;h++)g=g[e[h]];g&&f(b,g,c)}};(function(){var a="width top bottom position display z-index".split(" "),b={IMG:!0,VIDEO:!0,AUDIO:!0,EMBED:!0,OBJECT:!0},c=function(a,
d){switch(a.nodeType){case 3:return d||""==a.nodeValue.replace(/[\s\n\r]/g,"");case 1:if(!a.offsetWidth||!a.offsetHeight)break;var e=n.getComputedStyle(a);if("hidden"==e.visibility||!e.opacity)break;if(b[a.tagName.toUpperCase()])return;for(var e=a.childNodes,k=0,l=e.length;k!=l;k++)if(!c(e[k]))return}return!0},d,e=function(){Eb(function(){d.forEach(function(b){var e=b[0],h=b[1],k=e.style;b=function(){if(!z){var b=p.createElement("div");b.className="mtm-sticky-placeholder";var c=b.style;c.visibility=
"hidden";c.display="block";var d={};a.forEach(function(a){d[a]=k[a]});var m=n.getComputedStyle(e),f=m.display;"block"!=f&&"none"!=f&&(k.display=d.display="block");["box-sizing","width","height"].forEach(function(a){c[a]=m[a]||"0"});["left","right","top","bottom"].forEach(function(a){["margin","padding"].forEach(function(b){b=b+"-"+a;c[b]=m[b]||"0"});var b="border-"+a+"-width";c[b]=m[b]||"0"});d.placeholder=b;e.__mtm_oldInfo=d;f=e.clientWidth;if(!f&&"visible"==m.overflow)for(var h=e.children,l=0,r=
h.length;l!=r;l++){var q=h[l].clientWidth;q>f&&(f=q)}k.width=f+"px";k.display="block";"static"==m.position&&(k.position="relative");"auto"==m["z-index"]&&(k["z-index"]=1);e.parentNode.insertBefore(b,e)}};var l=e.getBoundingClientRect(),x=h.bottom?"bottom":"top",q=h.bottom?"top":"bottom",r=parseInt(n.getComputedStyle(e)["margin-"+x])||0;h.bottom||(r=-r);var r=l[x]+r,s=e.__mtm_stickyState||0,m,u,z=e.__mtm_oldInfo;s&&(u=z.placeholder.getBoundingClientRect());if(1==s){var w=l.bottom,la=l.left,cc=l.right,
Ja=function(a){if(a.offsetWidth||a.offsetHeight){var b=a.getBoundingClientRect(),c=b.top,d=parseInt(n.getComputedStyle(a)["margin-top"])||0;0<d&&(c-=d);d=b.left;if(la<b.right&&d<cc)return c>=u.bottom&&c<w&&(m=a,w=c),!0}};if(h.brk)for(var C=xa(h.brk,!0),t=0,D=C.length;t!=D;t++)Ja(C[t]);h.brkSticky&&d.forEach(function(a){a==e||a.__mtm_stickyState||Ja(a)});if(!(h.brk||h.brkSticky||h.nobrk))for(var C=e,v,t=function(a){return v==a||a.__mtm_oldInfo&&v==a.__mtm_oldInfo.placeholder};C&&C instanceof Element;){for(v=
C;(v=v.nextSibling)&&c(v,!0););if(v&&!d.some(t)&&Ja(v))break;C=C.parentNode}if(m){b();if("fixed"==n.getComputedStyle(m).position)k.position="fixed",k.top="auto",k.bottom=w+"px";else if(k.position="absolute",C=e.offsetParent)"static"==n.getComputedStyle(C).position&&(C.style.position="relative"),k.top="auto",k.bottom=C.getBoundingClientRect().bottom-w+"px";e.__mtm_stickyState=2}}if(!m)if(C=function(){e.parentNode.removeChild(z.placeholder);a.forEach(function(a){k[a]=z[a]});delete e.__mtm_oldInfo;delete e.__mtm_stickyState},
1==s)u.top>l.top&&C();else{var A=h.bottom?n.innerHeight:0;if(!h.ignoreTopSticky&&(D=e.__mtm_oldScrollPos,"undefined"==typeof D&&(D=r+Sa()),0<=D||0<=r)){t=k.visibility;k.visibility="hidden";var ra=l.left+l.right>>1,F;D>r?(F=D,D=r):F=r;0>D&&(D=0);var y=function(){for(var a=p.elementFromPoint(ra,F);a&&a instanceof Element;){var b=n.getComputedStyle(a);if("fixed"==b.position){var c=b.top;if(h.bottom&&"auto"==c&&"auto"!=b.bottom||!h.bottom&&"auto"!=c)return A=a.getBoundingClientRect()[q],!0;break}a=a.parentNode}};
if(h.bottom){var B=F;F=D;for(D=B;F<=D&&!y();F+=10);}else for(;F>=D&&!y();F-=10);k.visibility=t}if(2==s&&u[x]>=A&&u.top<=l.top)C();else if(2==s&&r>A||0==s&&r<=A)b(),k.position="fixed",h.bottom?(k.bottom=n.innerHeight-A+"px",k.top="auto"):(k.top=A+"px",k.bottom="auto"),e.__mtm_stickyState=1}e.__mtm_oldScrollPos=r})})};va["place.sticky"]=function(a,b){var c=X.vis[a];c&&p.addEventListener&&(c.forEach(function(a){var b=n.getComputedStyle(a),c=b.display;a=a.style;"block"!=c&&"none"!=c&&(a.display="block");
"none"!=b["float"]&&(a["float"]="none");"both"!=b.clear&&(a.clear="both")}),c=c.map(function(a){return[a,b]}),d?d=d.concat(c):(d=c,Fa(e)),d.sort(function(a,b){return a[0].getBoundingClientRect().top-b[0].getBoundingClientRect().top}),e())}})();var hc=function(a,b,c){var d="mzbtn-"+a;if(!wa(d)){var e,f,g,h=p.createElement("div"),k=p.createElement("div"),l,x,q,r=function(){p.cookie=d+"=1;path=/;expires="+(new y((new y).getTime()+31536E6)).toUTCString();h.parentNode.removeChild(h);q&&q.parentNode.removeChild(q);
x&&V(n,"resize",x)};h.className="mzbt-notice-wrapper";a=p.createElement("div");a.className="mzbt-notice-container";__mtm_tags._overriddenAPIs.innerHTMLSetter(a,(b.styles?"<style scoped='1'>"+b.styles+"</style>":"")+tagData);k.appendChild(a);h.appendChild(k);a=3==b.ypos.from;var s="position:"+(a?"relative":"fixed")+";width:"+b.width;b.modal||(s+=";z-index:2147483647");var m="width:100%;padding:0;overflow-y:auto",u=b.height,z=u.length-1;"%"==b.height.charAt(z)?g=parseFloat(b.height.substring(0,z)):
m+=";max-height:"+u;switch(b.xpos.from){case 2:s+=";right:"+b.xpos.offs;break;case 1:a?s+=";margin-left:auto;margin-right:auto":(s+=";left:50%",e=1);m+=";margin-left:"+b.xpos.offs;break;default:s+=";left:"+b.xpos.offs}switch(b.ypos.from){case 2:s+=";bottom:"+b.ypos.offs;m+=";position:absolute;bottom:0";break;case 1:s+=";top:50%";m+=";margin-top:"+b.ypos.offs;f=1;break;default:s+=";top:"+b.ypos.offs}if(e||f||g)s+=";visibility:hidden",l=function(){e&&(h.style.marginLeft=-(h.offsetWidth/2)+"px");f&&
(h.style.marginTop=-(h.offsetHeight/2)+"px");g&&(k.style.maxHeight=((n.innerHeight||(p.documentElement&&p.documentElement.offsetHeight?p.documentElement.offsetHeight:p.body.offsetHeight))*g/100|0)+"px")},x=Q(n,"resize",l);h.setAttribute("style",s);k.setAttribute("style",m);s=function(a){for(var b=0;b<a.length;b++)Q(a[b],"click",r);for(b=0;b<a.length;b++){var c=a[b];"a"!=c.tagName.toLowerCase()||c.getAttribute("href")||c.setAttribute("href","javascript:void(0)")}};if(b.autoDismiss)if(2==b.autoDismiss)s([h]);
else{s(h.getElementsByTagName("a"));s(h.getElementsByTagName("button"));m=h.getElementsByTagName("input");u=[];for(z=0;z<m.length;z++){var w=m[z].getAttribute("type");w&&"button"==w.toLowerCase()&&u.push(m[z])}s(u)}else s(Cb(h,"mzbt-popup-dismiss"));a?(b=c.firstChild)?c.insertBefore(h,b):c.appendChild(h):b.modal?(q=p.createElement("div"),q.className="mzbt-notice-overlay",q.setAttribute("style","position:fixed;overflow:auto;top:0;left:0;bottom:0;right:0;z-index:2147483647"),q.appendChild(h),c.appendChild(q)):
c.appendChild(h);l&&(l(),h.style.visibility="visible")}},xb=function(a,b){var c=a.id,d;for(d in J){var e=J[d],f=e.depends;f&&0<=f.indexOf(c)&&!b[d]&&Ma(e,!0,function(a,c){a.lazy&&c?b[d]=e:xb(e,b)})}},ic=function(a,b){Ma(a,!0,function(c,d){if(c.lazy){var e;if(d)e=[a];else{var f={};xb(a,f);e=[];for(var g in f)e.push(f[g]);if(!e.length)return}f=a.activationRules;f||(f=a.activationRules=[]);g=0;for(var h=e.length;g!=h;g++){var k=e[g].id,l="lazy-"+k;b[l]||(b[l]={pageConditions:[{comparator:"str",tag:k}]});
f.push(l)}}})},ia={},J={when:function(a,b){J[a]?b(J[a]):(ia[a]||(ia[a]=[]),ia[a].push(b))},add:function(a,b){J[a]=b;var c=ia[a];if(c){delete ia[a];for(var d=0,e=c.length;d!=e;d++)c[d](b)}}},Na=[],jc=function(a){for(var b=0,c=Na.length;b!=c;b++)a=Na[b](a);return a},kc=function(a,b){var c=G["-"+a];if(c)for(var d in c)if(b(T[d][0],d))break},H={},lc=1,Oa={},Ma=function(a,b,c){var d=a.id,e=Oa[d];if(e)b||delete Oa[d],c.apply(this,e);else{var e=a.tagCode,f=a.place,g=e instanceof E,h=f instanceof E,k=null,
l={};a.pid&&(l.pid=a.pid);if(g||h){var x=100*Math.random(),q=0,r=g?e:a.place,s=r.length,m,u=a.persistABInSession;if(u){var z="mzbtp-"+a.id,k=wa(z);if("string"==typeof k&&k.length)try{k=parseInt(k,10),0<=k&&k<s&&(m=1)}catch(w){}}if(!m)for(k=s-1,m=0;m!=s;m++)if(x<(q+=r[m][0])){k=m;u&&(p.cookie=z+"="+m+";path=/");break}g&&(a.pid&&(l.pid=a.pid[k]),e=e[k][1]);h&&(f=f[k],g||(f=f[1]));l.varn=k}b&&(Oa[d]=[e,f,l]);c(e,f,l)}},mc=/\{\{-?([^\{\}]+)\}\}/g,nc=/^VisualPlacement(?:\.(?:id|pos))?$/,oc=function(a,
b,c,d){for(var e=[],f={},g,h;null!==(g=mc.exec(a));)h=g[1],nc.test(h)||(f[g[1]]=!0);for(h in f)e.push(h);var k=n.__mtm_tags.variables;aa(e,function(a,b){bc((k?k[a]:null)||{type:a},function(c){f[a]=c;b()})},function(){e.length&&(a=a.replace(/\{\{\{\{|\{\{(-?)([^\{\}]+)\}\}/g,function(d,e,k,h){return k?(k=f[k],k!==t?(k=null===k?"":String(k),e||b?h=k:c?(d=k,h=a.substring(0,h),h=Bb.test(h.replace(Ab,""))?Z(d):Pa(d)):h=Z(k),h):d):"{{"}));d(a)})},pc=function(a,b){Ma(a,!1,function(c,d,e){var f=function(a){b(a,
d,e)};if("VIRT"==c.type)f();else{var g=c.type;oc(c.data,"HTML URL"==g||"JS URL"==g,"HTML"==g,function(b){switch(c.type){case "HTML":f(b);break;case "JS":f("<script>"+b.replace(/<\/(script)\b/gi,"<\\/$1")+"\x3c/script>");break;case "HTML URL":f("<script>__mtm_load('"+Z(b)+"',true)\x3c/script>");break;case "JS URL":f("<script src='"+Pa(b)+"'>\x3c/script>");break;case "POPUP":f(function(b,d){hc(a.id,c,b);d()});break;default:f("")}})}})},qc=0,rc=function(){var a=K.userAgent.match(/\bMSIE\s+([\d\.]+)/);
a&&(a=10>parseFloat(a[1]));return a}(),da=function(a){return function(){var b=p.body,c=b;if((a=jc(a)).length){if(b){if(I&&1<a.length&&b.getBoundingClientRect){var d=(n.innerHeight||p.documentElement.clientHeight)/3,e={};a.sort(function(a,b){return vb(d,b[0],b[1],e)-vb(d,a[0],a[1],e)})}}else c=(c=p.getElementsByTagName("script")[0])?c.parentNode:p.getElementsByTagName("head")[0];var f=[],g=[],h=function(a,b){f.push([a,1]);g.push(b)},k=[];aa(a,function(a,d){var e=a[0],f=a[1],g=function(){var a=lc++;
H[a]={id:f,state:e.state,s:S()};v("tag","p"+f);return a},m,u,z,w=e.place;w&&(m=w.sel,u=w.multi);var la=e.code,w="function"==typeof la;if(m||w)if(I)if(w)k.push(f),z=g(),e.code(b,function(){Y(va,f,e);Y(La,f,e);H[z].e=S();v("tag","_l",f);v("tag","l"+f);v("tag","f"+f);d()});else if(m=e.selector||ta(m,u),w=m[0]){var n=m[2],t=n?n.replace(/^-mzbt-/,""):"after",C=m[1];u||(w=[w]);k.push(f);var y=X.vis[f]=[];z=g();var D="string"==typeof e.code;aa(w,function(a,c){if(D){var d,e,m;m=la.replace(/\{\{\{\{|\{\{(-?)(VisualPlacement(?:\.(id|pos))?)\}\}/g,
function(b,c,m,f){if(!m)return"{{";if("pos"==f)return t;if(f)return e||(e=a.getAttribute("id"))||a.setAttribute("id",e="mzbtEl"+qc++),d=1,c?e:Z(e);d=1;return c?C:Z(C)});d?(containerEl=b,y.push(a)):y.push(containerEl=gc(n,a));ha(containerEl,m,sb(z,c))}else y.push(a),c()},function(){rb(z,d)();Y(La,f,e)});Y(va,f,e)}else v("tag","d"+f),d();else h(e,f),d();else if(I)k.push(f),ha(c,e.code,tb(g(),d));else if(rc)h(e,f),d();else{m=p.createElement("div");__mtm_tags._overriddenAPIs.innerHTMLSetter(m,e.code);
u=!1;m=m.children;for(var w=0,B=m.length;w!=B;w++){var A=m[w].nodeType;if(3==A){u=!0;break}if(1==A&&(A=m[w].nodeName.toLowerCase(),"script"!=A&&"noscript"!=A&&"link"!=A&&"meta"!=A)){u=!0;break}}u?(h(e,f),d()):(k.push(f),ha(c,e.code,tb(g(),function(){Y(La,f,e);d()})),Y(va,f,e))}},function(){k.length&&__mtm_load("//stats.mezzobit.com/tag-log?c="+__mtm[0]+"&ids="+k.join(",")+"&r="+zb);var a=f.length;if(a){G["mtm.dom"]||(G["mtm.dom"]={});for(var b=0;b!=a;b++){var c=g[b];G["mtm.dom"][c]=1;T[c]=f[b]}U["mtm.dom"]&&
ma("mtm.dom")}})}}},ha=function(){(function(){function a(a,g){a=a||"";g=g||{};var h=g.innerHTMLSetter,q;for(q in b)b.hasOwnProperty(q)&&(g.autoFix&&(g["fix_"+q]=!0),g.fix=g.fix||g["fix_"+q]);var r=p.createElement("div"),s=function(a){return"string"===typeof a&&-1!==a.indexOf("&")?(h(r,a),r.textContent||r.innerText||a):a},r=p.createElement("div"),s=function(a){return"string"===typeof a&&-1!==a.indexOf("&")?(h(r,a),r.textContent||r.innerText||a):a},m=function(b){a=b+a},u={comment:/^\x3c!--/,endTag:/^<\//,
atomicTag:/^<\s*(script|style|noscript|iframe|textarea)[\s\/>]/i,doctypeTag:/^<\!doctype[^>]*>/i,startTag:/^</,chars:/^[^<]/},z={comment:function(){var b=a.indexOf("--\x3e");if(0<=b)return{content:a.substr(4,b-1),length:b+3}},endTag:function(){var b=a.match(d);if(b)return{tagName:b[1],length:b[0].length}},atomicTag:function(){var b=z.startTag();if(b){if(b.unary)return delete b.unary,b.content="",b;var c=a.slice(b.length);if(c.match(new L("</\\s*"+b.tagName+"\\s*>","i"))&&(c=c.match(new L("([\\s\\S]*?)</\\s*"+
b.tagName+"\\s*>","i"))))return{tagName:b.tagName,attrs:b.attrs,content:c[1],length:c[0].length+b.length}}},doctypeTag:function(){var b=a.indexOf(">");return 0>b?null:{length:b+1}},startTag:function(){if(0>a.indexOf(">"))return null;var b=a.match(c);if(b){var d={};b[2].replace(e,function(a,b,c,e,m){a=c||e||m||f.test(b)&&b||null;d[b.toLowerCase()]=s(a)});return{tagName:b[1],attrs:d,unary:!!b[3],length:b[0].length}}},chars:function(){var b=a.indexOf("<");return{length:0<=b?b:a.length}}},w=function(){for(var b in u)if(u[b].test(a)){var c=
z[b]();return c?(c.type=c.type||b,c.text=a.substr(0,c.length),a=a.slice(c.length),c):null}};g.fix&&function(){var b=/^(AREA|BASE|BASEFONT|BR|COL|FRAME|HR|IMG|INPUT|ISINDEX|LINK|META|PARAM|EMBED)$/i,c=/^(COLGROUP|DD|DT|LI|OPTIONS|P|TD|TFOOT|TH|THEAD|TR)$/i,d=[];d.last=function(){return this[this.length-1]};d.lastTagNameEq=function(a){var b=this.last();return b&&b.tagName&&b.tagName.toUpperCase()===a.toUpperCase()};d.containsTagName=function(a){for(var b=0,c;c=this[b];b++)if(c.tagName===a)return!0;
return!1};var e=function(a){a&&"startTag"===a.type&&(a.unary=b.test(a.tagName)||a.unary);return a},f=w,h=function(){var a=d.pop();m("</"+a.tagName+">")},r={startTag:function(a){var b=a.tagName;"TR"===b.toUpperCase()&&d.lastTagNameEq("TABLE")?(m("<TBODY>"),u()):g.fix_selfClose&&c.test(b)&&d.containsTagName(b)?d.lastTagNameEq(b)?h():(m("</"+a.tagName+">"),u()):a.unary||d.push(a)},endTag:function(a){d.last()?g.fix_tagSoup&&!d.lastTagNameEq(a.tagName)?h():d.pop():g.fix_tagSoup&&(f(),u())}},u=function(){var b=
a,c=e(f());a=b;if(c&&r[c.type])r[c.type](c)};w=function(){u();return e(f())}}();return{append:function(b){a+=b},prepend:m,readToken:w,readTokens:function(a){for(var b;(b=w())&&(!a[b.type]||!1!==a[b.type](b)););},clear:function(){var b=a;a="";return b},rest:function(){return a},stack:[]}}var b=function(){var a={},b=this.document.createElement("div");b.innerHTML="<P><I></P></I>";a.tagSoup="<P><I></P></I>"!==b.innerHTML;b.innerHTML="<P><i><P></P></i></P>";a.selfClose=2===b.childNodes.length;return a}(),
c=/^<([\-A-Za-z0-9_]+)((?:\s+[\w\-]+(?:\s*=?\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,d=/^<\/([\-A-Za-z0-9_]+)[^>]*>/,e=/([\-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,f=/^(checked|compact|declare|defer|disabled|ismap|multiple|nohref|noresize|noshade|nowrap|readonly|selected)$/i;a.supports=b;var g=function(a){return a.text};a.tokenToString=function(a){var b={comment:function(a){return"\x3c!--"+a.content},endTag:function(a){return"</"+a.tagName+
">"},atomicTag:function(a){return b.startTag(a)+a.content+b.endTag(a)},doctypeTag:g,startTag:function(a){var b="<"+a.tagName,c;for(c in a.attrs)var d=a.attrs[c],b=b+(" "+c+'="'+(d?d.replace(/(^|[^\\])"/g,'$1\\"'):"")+'"');return b+(a.unary?"/>":">")},chars:g};return b[a.type](a)};a.escapeAttributes=function(a){var b={},c;for(c in a){var d=a[c];b[c]=d&&d.replace(/(^|[^\\])"/g,'$1\\"')}return b};for(var h in b)a.browserHasFlaw=a.browserHasFlaw||!b[h]&&h;this.htmlParser=a}).call(this);(function(){function a(){}
function b(a){return a!==t&&null!==a}function c(a,b,c){var d,e=a&&a.length||0;for(d=0;d<e;d++)b.call(c,a[d],d)}function d(a,b,c){for(var d in a)a.hasOwnProperty(d)&&b.call(c,d,a[d])}function e(a,b){d(b,function(b,c){a[b]=c});return a}function f(a,c){a=a||{};d(c,function(c,d){b(a[c])||(a[c]=d)});return a}function g(a){try{return l.call(a)}catch(b){var d=[];c(a,function(a){d.push(a)});return d}}var h={afterAsync:a,afterDequeue:a,afterStreamStart:a,afterWrite:a,beforeEnqueue:a,beforeWrite:function(a){return a},
done:a,error:function(a){throw a;},releaseAsync:!1},k=this,l=E.prototype.slice,n=function(){function a(c,d,e){var f=h+d;if(2===arguments.length)return f=c.getAttribute(f),b(f)?String(f):f;b(e)&&""!==e?c.setAttribute(f,e):c.removeAttribute(f)}function f(b,c){var d=b.ownerDocument;e(this,{root:b,options:c,win:d.defaultView||d.parentWindow,doc:d,parser:k.htmlParser("",{autoFix:!0,innerHTMLSetter:c.innerHTMLSetter}),actuals:[b],proxyHistory:"",proxyRoot:d.createElement(b.nodeName),scriptStack:[],writeQueue:[]});
a(this.proxyRoot,"proxyof",0)}var h="data-ps-";f.prototype.write=function(){[].push.apply(this.writeQueue,arguments);for(var a;!this.deferredRemote&&this.writeQueue.length;)a=this.writeQueue.shift(),"function"===typeof a?this.callFunction(a):this.writeImpl(a)};f.prototype.callFunction=function(a){var b={type:"function",value:a.name||a.toString()};this.onScriptStart(b);a.call(this.win,this.doc);this.onScriptDone(b)};f.prototype.writeImpl=function(a){this.parser.append(a);var b;a=[];for(var c,d;(b=
this.parser.readToken())&&!(c=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("script"):!1)&&!(d=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("style"):!1);)a.push(b);this.writeStaticTokens(a);c&&this.handleScriptToken(b);d&&this.handleStyleToken(b)};f.prototype.writeStaticTokens=function(a){a=this.buildChunk(a);if(a.actual)return a.html=this.proxyHistory+a.actual,this.proxyHistory+=a.proxy,this.options.innerHTMLSetter(this.proxyRoot,a.html),this.walkChunk(),a};f.prototype.buildChunk=function(a){var b=
this.actuals.length,d=[],e=[],f=[];c(a,function(a){d.push(a.text);if(a.attrs){if(!/^noscript$/i.test(a.tagName)){var c=b++;e.push(a.text.replace(/(\/?>)/," "+h+"id="+c+" $1"));"ps-script"!==a.attrs.id&&"ps-style"!==a.attrs.id&&f.push("atomicTag"===a.type?"":"<"+a.tagName+" "+h+"proxyof="+c+(a.unary?" />":">"))}}else e.push(a.text),f.push("endTag"===a.type?a.text:"")});return{tokens:a,raw:d.join(""),actual:e.join(""),proxy:f.join("")}};f.prototype.walkChunk=function(){for(var c,d=[this.proxyRoot];b(c=
d.shift());){var e=1===c.nodeType;e&&a(c,"proxyof")||(e&&(this.actuals[a(c,"id")]=c,a(c,"id",null)),(e=c.parentNode&&a(c.parentNode,"proxyof"))&&this.actuals[e].appendChild(c));d.unshift.apply(d,g(c.childNodes))}};f.prototype.handleScriptToken=function(a){var b=this.parser.clear();b&&this.writeQueue.unshift(b);a.src=a.attrs.src||a.attrs.SRC;if(a.src&&this.scriptStack.length)this.deferredRemote=a;else this.onScriptStart(a);var c=this;this.writeScriptToken(a,function(){c.onScriptDone(a)})};f.prototype.handleStyleToken=
function(a){var b=this.parser.clear();b&&this.writeQueue.unshift(b);a.type=a.attrs.type||a.attrs.TYPE||"text/css";this.writeStyleToken(a);b&&this.write()};f.prototype.writeStyleToken=function(a){var b=this.buildStyle(a);this.insertStyle(b);a.content&&(b.styleSheet&&!b.sheet?b.styleSheet.cssText=a.content:b.appendChild(this.doc.createTextNode(a.content)))};f.prototype.buildStyle=function(a){var b=this.doc.createElement(a.tagName);b.setAttribute("type",a.type);d(a.attrs,function(a,c){b.setAttribute(a,
c)});return b};f.prototype.insertStyle=function(a){this.writeImpl('<span id="ps-style"/>');var b=this.doc.getElementById("ps-style");b.parentNode.replaceChild(a,b)};f.prototype.onScriptStart=function(a){a.outerWrites=this.writeQueue;this.writeQueue=[];this.scriptStack.unshift(a)};f.prototype.onScriptDone=function(a){a!==this.scriptStack[0]?this.options.error({message:"Bad script nesting or script finished twice"}):(this.scriptStack.shift(),this.write.apply(this,a.outerWrites),!this.scriptStack.length&&
this.deferredRemote&&(this.onScriptStart(this.deferredRemote),this.deferredRemote=null))};f.prototype.writeScriptToken=function(a,b){var c=this.buildScript(a),d=this.shouldRelease(c),e=this.options.afterAsync;a.src&&(c.src=a.src,this.scriptLoadHandler(c,d?e:function(){b();e()}));try{this.insertScript(c),a.src&&!d||b()}catch(f){this.options.error(f),b()}};f.prototype.buildScript=function(a){var b=this.doc.createElement(a.tagName);d(a.attrs,function(a,c){b.setAttribute(a,c)});a.content&&(b.text=a.content);
return b};f.prototype.insertScript=function(a){this.writeImpl('<span id="ps-script"/>');var b=this.doc.getElementById("ps-script");b.parentNode.replaceChild(a,b)};f.prototype.scriptLoadHandler=function(a,b){function c(){a=a.onload=a.onreadystatechange=a.onerror=null;b()}var d=this.options.error;e(a,{onload:c,onreadystatechange:function(){/^(loaded|complete)$/.test(a.readyState)&&c()},onerror:function(){var c={message:"remote script failed "+a.src};a=a.onload=a.onreadystatechange=a.onerror=null;d(c);
b()}})};f.prototype.shouldRelease=function(a){return!/^script$/i.test(a.nodeName)||!!(this.options.releaseAsync&&a.src&&a.hasAttribute("async"))};return f}();k.postscribe=function(){function b(){var a=l.shift(),d;a&&(d=a[a.length-1],d.afterDequeue(),a.stream=c.apply(null,a),d.afterStreamStart())}function c(f,h,k){function l(a){a=k.beforeWrite(a);p.write(a);k.afterWrite(a)}p=sc(new n(f,k),__mtm_tags&&__mtm_tags._writerConstructors,__mtm_tags&&__mtm_tags._writerModifiers,k);p.id=m++;p.name=k.name||
p.id;d.streams[p.name]=p;var r=f.ownerDocument,u={close:r.close,open:r.open,write:r.write,writeln:r.writeln};e(r,{close:a,open:a,write:function(){return l(g(arguments).join(""))},writeln:function(){return l(g(arguments).join("")+"\n")}});var t=p.win.onerror||a;p.win.onerror=function(a,b,c){k.error({msg:a+(b?" - "+b+":"+c:" (inline script)")});t.apply(p.win,arguments)};p.write(h,function(){e(r,u);p.win.onerror=t;k.done();p=null;b()});return p}function d(c,e,g){"function"===typeof g&&(g={done:g});g=
f(g,h);var k=[c,e,g];c.postscribe={cancel:function(){k.stream?k.stream.abort():k[1]=a}};g.beforeEnqueue(k);l.push(k);p||b();return c.postscribe}var m=0,l=[],p=null;return e(d,{streams:{},queue:l,WriteStream:n,HTMLParser:k.htmlParser})}()}).call(this);return this.postscribe}.call({}),sc=function(a,b,c,d){if(b)for(var e=0,f=b.length;e!=f;e++)b[e](a);if(!c)return a;d=a.options;var g,h,k=a.parser.append;a.parser.append=function(a){var b=a.length;h?h.substring(0,b)==a&&(g[1]+=b,h=h.substring(b)||null):
g||(g=[0,b]);return k.apply(this,arguments)};var l=a.parser.prepend;a.parser.prepend=function(a){g&&g[1]&&(g[0]+=a.length);return l.apply(this,arguments)};var n=a.parser.clear;a.parser.clear=function(){g&&g[1]&&(h=this.rest(),g=[0,0]);return n.apply(this,arguments)};var p=function(b,e){for(var f=0,g=c.length;f!=g;f++)c[f].call(a,b,e,d)},r=a.parser.readToken;a.parser.readToken=function(){var a;g&&g[1]&&(a=this.rest().length);var b=r.apply(this,arguments);if(!b||"startTag"!=b.type&&"atomicTag"!=b.type||
"ps-script"==b.attrs.id)return b;var c=!1;g&&g[1]&&(a-=this.rest().length,g[0]>=a?g[0]-=a:(g[0]=0,p(b,!0),c=!0),0>(g[1]-=a)&&(g[1]=0));c||p(b,!1);return b};return a};n.__mtm_preview=function(){__mtm_proc(__mtm_tags)};var ya={};n.__mtm_proc=function(a,b){if(b){if(ya[b])ya[b](a)}else if("object"==typeof a&&null!==a&&a.tags){if(a.previewMode!==t)if(a.previewExpire===t||1E3*a.previewExpire>S()){if(!a.previewMode){delete a.previewMode;delete a.previewExpire;n.__mtm_tags=a;__mtm_load("//tdi.mezzobit.com/tag-container/check-preview?c="+
__mtm[0]);return}}else if(!a.enabled)return;if(!n.__mtm_start){var c;n.__mtm_start=(c=n.performance)&&(c=c.timing)&&(c.navigationStart||c.responseEnd)||S()}if(a.dg)__mtm_load("//"+__mtm[1]+"/mtm-"+a.dg+".js");else{if(c=n.__mtm_tags)if(a._skipProfiler=c._skipProfiler||c._standalone,a._profiler=c._profiler,a._getProfilerData=c._getProfilerData,a._writerModifiers=c._writerModifiers,a._dcl=c._dcl,a._overriddenAPIs=c._overriddenAPIs,a.postscribe=c.postscribe,c._tagStats&&(H=a._tagStats=c._tagStats),c=
c._triggerEv)"function"==typeof c&&n.removeEventListener("message",c),p.documentElement.addEventListener("sprofiler-msg",a._triggerEv=function(a){v.apply(n,a.detail)});n.__mtm_tags=a;if(!a._overriddenAPIs){a._overriddenAPIs={innerHTMLSetter:function(a,b){a.innerHTML=b}};var d=["setTimeout","setInterval"];for(c=0;2!=c;c++)(function(b){b=d[b];var c=n[b];a._overriddenAPIs[b]=c.apply?function(){return c.apply(n,arguments)}:function(a,b){return c(a,b)}})(c)}a.postscribe||(a.postscribe=ha);if(!a._skipProfiler){if(!a._profiler&&
(a.debug||a.vs)&&p.currentScript&&(n.MutationObserver||n.WebKitMutationObserver)&&!/Edge\/\d/i.test(K.userAgent)){__mtm_load(ka("profile"));return}a._profiler&&!a._getProfilerData&&(a._getProfilerData=a._profiler(H,0,0,v,a._overriddenAPIs))}a.timezones&&a.timezones[a.timezone]&&(ca[a.timezone]=Wa(ba,a.timezones[a.timezone]),delete a.timezones[a.timezone]);if(Ba(a.activityPeriodRules,ca[a.timezone]||ba)){if(a.timezones)for(var e in a.timezones)ca[e]=Wa(ba,a.timezones[e]);if(a._accessLoaded)X=a._accessRules;
else if(a._accessLoaded=1,X=a._accessRules={vis:{}},a.arrules){pb(a.accessRestrictionRules,function(a){a&&(X.g=a);__mtm_load(ka("access"))});return}if(a._profiler&&a.vs){if(!a._tageventsLoaded){a._tageventsLoaded=1;__mtm_load(ka("tagevents"));return}a._tagEventsInit||(a._tagEventsInit=1,a._tagevents(da,ea,v,M,N,Fa,ab,aa,ta,kc,Na,J,H,a.vs.prof))}Pb();var f="yes"==K.doNotTrack||"yes"==K.msDoNotTrack;Qb();var g=[],h=function(b){var c=b.depends,d;if(c&&(d=c.length)){b.defer+=d;for(var e=0;e!=d;e++){var f=
"-"+c[e];G[f]||(G[f]={});G[f][b.id]=1}}pc(b,function(e,f,h){e={code:e,place:f,state:h};if(b.defer){if(T[b.id]=[e,b.defer],c&&d)for(e=0;e!=d;e++)f="-"+c[e],U[f]&&ma(f)}else e=[e,b.id],b.activationDelay?a._overriddenAPIs.setTimeout(da([e]),b.activationDelay):k?g.push(e):da([e])()})};e=function(b){var c=b.timezone||a.timezone;if(!(f&&!b.place||!Ba(b.activityPeriodRules,ca[c]||ba)||b.pathname&&R.pathname!=b.pathname&&R.pathname!=b.pathname+"/")){if(b.query){db();for(var d in b.query)if(b.query[d]!=fa[d])return}b.defer=
0;ic(b,a.rules);ob(b.activationRules,c,function(a,c){za("//tdi.mezzobit.com/rate-limit/i"+b.id+"_"+a.id,"rateLimit"+b.id,function(a,b){c(b)})},function(a){a&&pb(b.accessRestrictionRules,function(a){a&&(X[b.id]=a);h(b)})})}};n.__mtm_spy++;var k=1;a.rules||(a.rules={});var l=a.tags,x=l.length;for(c=0;c!=x;c++){var q=l[c];J.add(q.id,q)}for(c=0;c!=x;c++)e(l[c]);k=0;g.length&&da(g)();a.debug&&a._profLogger&&a._profLogger(a._getProfilerData)}}}};n.__mtm_tags&&!n.__mtm_tags._standalone?__mtm_proc(__mtm_tags):
__mtm_load("//"+__mtm[1]+"/"+__mtm[0]+".js")}})(window,document,navigator,location,Object,Array,Date,RegExp);
