(function(require, define) {
define(function(require, exports, module) {
var $ = require('jquery'), widgets = require('widgets'), widgetLoader = require('widgetloader');

function BaseWidget(a){}BaseWidget.goldenRatio=1.61803399;var blockTypes={};BaseWidget.prototype.blockTypes=blockTypes;var usedImages={};BaseWidget.prototype.usedImages=usedImages;BaseWidget.touchEnabled=void 0!==document.ontouchend;BaseWidget.ie6mode=!1;
function ModenizrFixedSupport(){var a=document.createElement("div"),b=a.cloneNode(!1),d=!1,c;(c=document.body)||(d=!0,c=document.documentElement.appendChild(document.createElement("body")));var f=c.style.cssText;c.style.cssText="padding:0;margin:0";a.style.cssText="position:fixed;top:42px";c.appendChild(a);c.appendChild(b);var n=a.offsetTop!==b.offsetTop;c.removeChild(a);c.removeChild(b);c.style.cssText=f;d&&document.documentElement.removeChild(c);return n}
BaseWidget.fixedSupport=function(){var a=ModenizrFixedSupport();BaseWidget.fixedSupport=function(){return a};return a};BaseWidget.prototype.getBlockHeight=function(a,b,d,c){if(d)return d;a=a.desiredAspect;c&&(a=Math.max(1/c,Math.min(c,a)));return Math.round(b/a)};BaseWidget.prototype.hasAdCfg=function(a,b){return this.findAdCfg(a,b,!0)};
function getPlatform(){var a=navigator.userAgent||navigator.vendor||window.opera,b=/(Android|Opera M(ob|in)i|iPhone|BlackBerry|Windows Phone|Silk|PlayBook|(Ovi|UC)Browser|Nokia|SAMSUNG)/.test(a),d=/Tab|Pad|Nexus (7|9|10)/.test(a);-1!=a.indexOf("Android")&&-1==a.indexOf("Mobile")&&(d=!0,b=!1);var a=-1<navigator.userAgent.toLowerCase().indexOf("windows nt 6.2")&&-1<navigator.userAgent.toLowerCase().indexOf("touch"),c="desktop";d||a?c="tablet":b&&(c="mobile");return c}
function checkAdPlatform(a,b){return a.platform&&a.platform!=b?(kaloogaLog("Ad excluded based on platform: "+b),!1):!0}function checkAdCountries(a,b,d){return a.countries&&kalooga.geoIpData&&0>$.inArray(kalooga.geoIpData.country_code,a.countries)?(kaloogaLog("Ad excluded based on country: "+kalooga.geoIpData.country_code),widgets.sendEvent(b.cfg,"findAd #"+d+" not in country: "+kalooga.geoIpData.country_code,{extra:"ad:"+a.adId}),!1):!0}
function checkAdPlayerSupport(a,b,d,c){return!("preroll"!=a.adType&&"videoPlaza"!=a.adType&&"adswizz"!=a.adType&&"yume"!=a.adType||b.flashembed&&b.flashembed.isSupported([3,0]))||"yume-html5"==a.adType&&!document.createElement("video").canPlayType?(widgets.sendEvent(d.cfg,"findAd #"+c+" incompatible type:"+a.adType,{extra:"ad:"+a.adId}),!1):!0}
function checkAd(a,b,d,c,f,n){return!a.reusable&&a.selected||0!==a.position&&a.position!=c||n&&!n[a.iab]||!(checkAdPlatform(a,f)&&checkAdCountries(a,d,c)&&checkAdPlayerSupport(a,b,d,c))?!1:!0}
BaseWidget.prototype.findAdCfg=function(a,b,d){var c=this,f=null,n=c.iWin||window,g=null;if(!this.cfg.ads)return null;b&&(g={},"string"===typeof b?g[b]=!0:$.isArray(b)&&$.each(b,function(a,b){g[b]=!0}));var e=getPlatform();kaloogaLog("platform \x3d ",e);var p=0;$.each(c.cfg.ads,function(b,r){kaloogaLog("Ad platform: "+r.platform);null===f&&(!r.usedInWaterfall&&checkAd(r,n,c,a,e,g))&&(d||(r.selected=!0),p=b,f=r)});if(f&&"jwplayer"==f.adType&&!f.waterfall)for(f.waterfall=[f],kaloogaLog("!!!! WATERFALL starting at ",
p,f),b=p+1;b<c.cfg.ads.length;b++){var s=c.cfg.ads[b];if(!s.waterfall&&checkAd(s,n,c,a,e,g)){if("jwplayer"!==s.adType)break;d||(s.selected=!0);s.usedInWaterfall=!0;kaloogaLog("!!!! WATERFALL chaining ",s);f.waterfall.push(s)}}kaloogaLog("exit findAdCfg:",f);return f};BaseWidget.prototype.elementInViewport=function(a){var b=this.i$||$,d=this.iWin||window;a=b(a).get(0).getBoundingClientRect();return 0<=a.top&&0<=a.left&&a.bottom<=b(d).height()&&a.right<=b(d).width()};
BaseWidget.prototype.elementAreaInViewport=function(a){var b=this.i$||$,d=this.iWin||window;a=b(a).get(0).getBoundingClientRect();var c=Math.max(0,a.top),f=Math.max(0,a.left),n=Math.min(b(d).height(),a.bottom),b=Math.min(b(d).width(),a.right);return(n-c)*(b-f)/((a.bottom-a.top)*(a.right-a.left))};
BaseWidget.prototype.elementOffset=function(a){var b=a.offset();b&&(b.top+=Math.max(0,Math.round(parseFloat(a.css("border-top-width")))),b.left+=Math.max(0,Math.round(parseFloat(a.css("border-left-width")))),b.top+=Math.max(0,Math.round(parseFloat(a.css("padding-top")))),b.left+=Math.max(0,Math.round(parseFloat(a.css("padding-left")))));return b};BaseWidget.prototype.loadStyles=function(a){var b=this;$.each(a,function(a,c){b.loadStyle(c)})};
BaseWidget.prototype.getFiletype=function(){try{if(!document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1"))return"PNG"}catch(a){return"PNG"}return"SVG"};
BaseWidget.prototype.loadStyle=function(a){var b=this.iDoc||document,d=this.i$||$,c="http:"!=b.location.protocol;kaloogaLog("loading css pre normalize",a);a=a.replace(/(https?:\/\/[^#?\/]+)(\/\.\.)*/,"$1").replace(/\/[^\/]+\/\.\.\//g,"/");/^https?:.*/.test(a)||(a=(c?"https:":"http:")+a);kaloogaLog("loading css",a);d.each(b.styleSheets,function(b,d){d.href==a&&(d.disabled=!1,kaloogaLog("enabled css",a))});0==d('link[href\x3d"'+a+'"]').length&&(kaloogaLog("css was not yet loaded",a),d("head",b).append(d(b.createElement("link")).attr({media:"screen",
rel:"stylesheet",type:"text/css",href:a})))};
BaseWidget.prototype.getText=function(a,b){var d=$.extend({},{es:{"Open Timeline":"Abrir L\u00ednea de Tiempo","Latest news":"\u00daltimas noticias ",Back:"Atr\u00e1s",on:"en","Timeline about ... at ...":"L\u00ednea de Tiempo sobre ... en ...","... Timeline":"L\u00ednea de Tiempo ...",Search:"Buscar","The latest visual news about ...":"\u00daltimas noticias visuales sobre ...","Related search results":"Resultados relacionados con la b\u00fasqueda","more images":"M\u00e1s im\u00e1genes",of:"de","... stories and pictures at ...":"... noticias y m\u00e1s fotos en ...",
"Check out these ... stories and pictures at ...:":"Mira m\u00e1s noticias y fotos de ... en ...","The latest stories at ...":"Las \u00faltimas noticias en ...","... (and other stories)":"... (y otras noticias)","Check out these latest stories at ...:":"Mira m\u00e1s noticias y fotos de ...",images:"fotos","Back to\narticle":"Volver a\nart\u00edculo","Back to\noverview":"Volver a\ngaler\u00eda"},ca:{"Latest news":"\u00daltimes not\u00edcies ",on:"en",Search:"Buscar",of:"de","Check out these ... stories and pictures at ...:":"Mira m\u00e9s not\u00edcies y fotos de ... en ...",
"The latest stories at ...":"Las \u00faltimes not\u00edcies en ...","... (and other stories)":"... (y otras not\u00edcies)","Check out these latest stories at ...:":"Mira m\u00e9s not\u00edcies y fotos de ...",images:"fotos"},pt:{"Open Timeline":"Abrir Timeline","Latest news":"Ultimas not\u00edcias",Back:"Voltar",on:"em","... Timeline":"... Timeline",Search:"Busca","more images":"mais imagens",images:"imagens"},no:{"Open Timeline":"\u00e5pen Timeline","Latest news":"Siste nytt",Back:"Tilbake",on:"p\u00e5",
"... Timeline":"... Timeline"},fr:{"Open Timeline":"Les derniers articles en images","Latest news":"Les plus r\u00e9centes",Back:"Retour",on:"sur","Timeline about ... at ...":"Timeline au sujet ... sur ...","... Timeline":"... Timeline","Related search results":"Connexes r\u00e9sultats de la recherche","more images":"plus photos",of:"de",images:"photos","Back to\narticle":"Retour \u00e0\nl'article","Back to\noverview":"Retour \u00e0\nla galerie"},de:{"Open Timeline":"Open Timeline","Latest news":"Aktuelle Nachrichten",
Back:"Zur\u00fcck",on:"auf","Timeline about ... at ...":"Timeline \u00fcber ... auf ...","... Timeline":"... Timeline",Search:"Suche","Related search results":"Verwandte Suchergebnisse","more images":"mehr Bilder",of:"von","... stories and pictures at ...":"... Nachrichten und Bilder von ...","The latest stories at ...":"Aktuellen Nachrichten auf ...","... (and other stories)":"... (und weitere Nachrichten)","Check out these ... stories and pictures at ...:":"Sehen Sie sich das an ... Nachrichten und Bilder von ...:",
"Check out these latest stories at ...:":"Die neusten Nachrichten sehen Sie auf ...:",images:"Bilder","Back to\narticle":"Zur\u00fcck zum\nArtikel","Back to\noverview":"Zur\u00fcck zur\nBildergalerie"},nl:{"Open Timeline":"Open Timeline","Latest news":"Laatste Nieuws",Back:"Terug",on:"op","Timeline about ... at ...":"Timeline over ... op ...","... Timeline":"... Timeline",Search:"Zoeken","The latest visual news about ...":"Het laatste in beeld over ...","Related search results":"Gerelateerde zoekresultaten",
"more images":"meer foto's",of:"van","... stories and pictures at ...":"... nieuws en fotos op ...","The latest stories at ...":"Het laatste nieuws op ...","... (and other stories)":"... (en ander nieuws)","Check out these ... stories and pictures at ...:":"Bekijk ... nieuws en fotos op ...","Check out these latest stories at ...:":"Bekijk het laatste nieuws op ...",images:"fotos","Back to\narticle":"Terug naar\nartikel","Back to\noverview":"Terug naar\noverzicht"},it:{"more images":"altre immagini"},
zh:{"more images":"\u66f4\u591a\u56fe\u50cf"},tr:{"more images":"daha fazla g\u00f6r\u00fcnt\u00fc","Check out these ... stories and pictures at ...:":"... haberlerine ve foto\u011fraflar\u0131na g\u00f6zat: ..."},id:{"more images":"lebih gambar\u00fc"},ar:{"more images":"\u0627\u0644\u0635\u0648\u0631 \u0645\u0646 \u0645\u0632\u064a\u062f"},ko:{"more images":"\ub354 \ub9ce\uc740 \uc774\ubbf8\uc9c0"},ja:{"more images":"\u4ee5\u4e0a\u306e\u753b\u50cf"},fa:{"more images":"\u0628\u06cc\u0634\u062a\u0631 \u062a\u0635\u0627\u0648\u06cc\u0631"},
th:{"more images":"\u0e2b\u0e25\u0e32\u0e01\u0e2b\u0e25\u0e32\u0e22\u0e23\u0e39\u0e1b\u0e20\u0e32\u0e1e"},ru:{"more images":"\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0435\u0449\u0451"}}[this.cfg.language],this.cfg.translation);d&&d[a]&&(a=d[a]);b&&$.each(b,function(b,d){a=a.replace(/\.\.\./,d)});return a};BaseWidget.prototype.blockTypes.adslot=function(a,b,d,c){function f(c){if(!$.contains(u.documentElement,t[0]))return kaloogaLog("Div element is not part of dom tree (anymore)"),c(),null;p++;t.empty();var f=e.findAdCfg(a.position,a.iabs);if(!f)return kaloogaLog("No ad found for position",a.position),a.adFailedCallback&&a.adFailedCallback(t),c(),null;if(e.cfg.inViewAds){kaloogaLog("Load ad when in view");var h=function(){if(r.window){var a;var e=t;a=b;var u=d,q=r;if(q.window&&0!=e.closest("body").length){var g=
e.offset(),e=g.top,g=g.left;a=e<q.pageYOffset+q.innerHeight&&g<q.pageXOffset+q.innerWidth&&e+u>q.pageYOffset&&g+a>q.pageXOffset}else a=!1;a?(kaloogaLog("Ad is in view"),n(c,f)):setTimeout(h,50)}};h()}else return n(c,f);return t}function n(c,m){function h(a){if("timeout"==a)if(g||0<e.adQueue.length)kaloogaLog("Ad-queue logging: Timeout interval stop, ",g,e.adQueue.length),window.clearInterval(k),k=null;else{kaloogaLog("Ad-queue logging: waiting for next ad timer interval");return}g||(g=!0,k&&(window.clearInterval(k),
k=null),kaloogaLog("Ad-queue logging: readyOrNot: ",a),c())}kaloogaLog("printing ad",m);var u="ad-"+m.adType+"-pos"+a.position+"-attempt"+p+" ";a.adBeforePrintCallback&&a.adBeforePrintCallback(m);e.cfg.adDebug&&widgets.sendEvent(e.cfg,u+"printAd",{extra:"ad:"+m.adId});var k=null,g=!1;r.kalooga.require(["ad_"+m.adType],function(c){if(a.replayAfterLightbox&&("preroll"==m.adType||"jwplayer"==m.adType||"jwplayer-googima"==m.adType)){var u=a.adCompleteCallback;a.adCompleteCallback=function(t){u&&u(t);
s(r).one("overlayClosed",function(){kaloogaLog("Overay closed after ad complete");t.empty();c.print.call(e,m,t,b,d,null,f,a,r)})}}c.print.call(e,m,t,b,d,h,f,a,r)},function(){kaloogaLog("Did not load ad module :(",m);h("Error in ad module require")});k=window.setInterval(function(){h("timeout")},2500);e.cfg.adDebug&&widgets.sendEvent(e.cfg,u+"after print",{extra:"ad-"+m.adId})}function g(){if(e.adQueue&&0<e.adQueue.length){e.adLoading=!0;kaloogaLog("Ad-queue logging: Calling new printAd function from queue",
e.adQueue);try{e.adQueue.shift()(g)}catch(a){kaloogaLog("Error running something from adQueue",a),g()}}else kaloogaLog("Ad-queue logging: queue empty"),e.adLoading=!1}var e=this,p=0,s=e.i$||$,u=e.iDoc||document,r=e.iWin||window,t=s(u.createElement("div"));kaloogaLog("constructing ad block",a,e,r);t.addClass("interactive");t.one("impression",function(a){a.stopPropagation();e.adQueue=e.adQueue||[];e.adLoading?(kaloogaLog("Ad-queue logging: Adding item to queue",e.adQueue),e.adQueue.push(f)):(e.adLoading=
!0,f(g))});return t};function GridWidget(a){this.cfg=a}GridWidget.prototype=kalooga.inherit(BaseWidget.prototype);GridWidget.prototype.constructor=GridWidget;GridWidget.prototype.print=function(a){for(var b=0;b<a.length;b++){var d=$(a[b]);this._print(d)}};
GridWidget.prototype._print=function(a){function b(a,b,e,f){var m=b.images[0],h=Math.floor(a/c.layout[0]),g=a%c.layout[0],k=["","",a,"_row"+h,"_col"+g].join(" kalooga_item");m.video&&(k+=" kalooga_video");e&&(k+=" kalooga_backfill");b.label&&(k+=" kalooga_label_"+b.label.replace(/[^a-z0-9]/ig,"_"));e=$(document.createElement("li")).addClass(k);var k=$(document.createElement("img")).addClass("kalooga_img"),p=$(document.createElement("div")).addClass("kalooga_info"),q=$(document.createElement("span")).addClass("kalooga_title");
if(f)var w=$(document.createElement("span")).addClass("kalooga_kicker");var x=$(document.createElement("span")).addClass("kalooga_date"),v=Math.floor(c.width/c.layout[0]),l=Math.floor(c.height/c.layout[1]);0===g&&(v=c.width-v*(c.layout[0]-1));0===h&&(l=c.height-l*(c.layout[1]-1));e.width(v);k.width(v);k.height(l);(h=m.caption?m.caption.replace(/^\s+|\s+$/g,""):null)&&0==h.length&&(h=null);k.attr({src:m.src+"\x26size\x3d"+v+"x"+l,title:h});l=b.title.replace(/^\s+|\s+$/g,"");f?(l=l.split(":"),2===l.length?
(w.text(l[0]),q.text(l[1])):2<l.length?(w.text(l.slice(0,2).join(":")),q.text(l.slice(2,l.length).join(":"))):q.text(l[0])):q.text(l);d.cfg.showTimeInGrid?(h=new Date(b.date),l=h.getHours(),h=h.getMinutes(),x.text((10>l?"0":"")+l+":"+(10>h?"0":"")+h+" "+b.shortDate)):x.text(b.shortDate);f&&p.append(w);p.append(q);p.append(x);e.append(k);e.append(p);n.append(e);$.each({itemClickAction:e,titleClickAction:q,imageClickAction:k},function(c,e){var f=s[d.cfg[c]];f&&e.click(function(c){f.call(d,c,b,m,a)})})}
var d=this,c=d.cfg,f=$(a);a=$(document.createElement("div")).addClass("kalooga_pre");var n=$(document.createElement("ul")).addClass("kalooga_itemList"),g=$(document.createElement("div")).addClass("kalooga_post"),e=$(document.createElement("style")).attr({type:"text/css"}),p=".kalooga_"+d.cfg.widgetId+" { display:none; }";e[0].styleSheet?e[0].styleSheet.cssText=p:e.text(p);$("html \x3e head").append(e);c.css&&d.loadStyles(c.css);var s={ARTICLE:function(a,b,c,e){kaloogaLog("Article!",arguments);if(b)return widgets.trackArticleNavigation(d.cfg,
b.url,b.articleId,window,{extra:"open_layer",image:c,index:e,event:a}),!1},LAYER:function(a,b,c,e){if(b)return kaloogaLog("Layer!",arguments),widgets.sendEvent(d.cfg,"click",{extra:"open_layer",image:c,index:e,event:a}),d.cfg.targetPage?window.open(d.cfg.targetPage+"?"+$.param({wid:d.cfg.linkWidget,imageUrl:c.src,clickedArticleUrl:b.url}),d.cfg.openTargetInNewTab?"_blank":"_self"):widgetLoader.load(d.cfg.linkWidget,function(a,d){a&&a.display(b.url,c.src)},b.url),a.stopPropagation(),!1}};c.preContent&&
a.append(c.preContent);c.postContent&&g.append(c.postContent);f.empty().addClass("kalooga_grid");f.append(a);f.append(n);f.append(g);$.each(c.articles,function(a,d){b(a,d,!1,c.kicker)});c.backfillArticles&&$.each(c.backfillArticles,function(a,d){b(a+c.articles.length,d,!0,c.kicker)});$.each({preClickAction:a,postClickAction:g},function(a,b){var c=s[d.cfg[a]];c&&b.click(function(a){c.call(d,a)})});d.cfg.ads&&setTimeout(function(){function a(){if(f.is(":visible")){var g={};$.each(d.cfg.ads,function(a,
b){var c=b.iab.split("x");d.cfg.adSizeFilter&&parseInt(c[0],10)>1.05*f.width()?kaloogaLog("Ad too wide for widget",parseInt(c[0],10),f.width()):d.cfg.adSizeFilter&&parseInt(c[1],10)>1.05*f.height()?kaloogaLog("Ad too high for widget",parseInt(c[1],10),f.height()):g[b.iab]=!0});var h=[];$.each(g,function(a,b){h.push(a)});if(0==h.length)setTimeout(a,1E3);else if(b=d.blockTypes.adslot.call(d,{position:1,iabs:h,minimizeHeight:d.cfg.adMinimizeHeight,minimizeWidth:d.cfg.adMinimizeWidth,adFailedCallback:e,
adReadyCallback:function(){b.removeClass("kalooga_adLoading").addClass("kalooga_adActive");setTimeout(function(){c=$(document.createElement("div")).addClass("kalooga_closeBtn");c.click(e);b.append(c)},1E3);if(0<d.cfg.adDuration){var a=function(){d.elementInViewport(f)?setTimeout(e,d.cfg.adDuration):setTimeout(a,100)};a()}}},f.width(),f.height()))b.addClass("kalooga_adBlock kalooga_adLoading"),f.append(b),b.trigger("impression")}else setTimeout(a,100)}var b=null,c=null,e=function(){try{b.fadeOut(function(){try{b.remove()}catch(a){}}),
c.remove()}catch(a){}};a()},d.cfg.adDelay)};	return {
		'create' : function(cfg) {
			return new GridWidget(cfg);
		}
	};
});

})(kalooga.require, kalooga.define);
