(function(){var d=void 0,g=true,h=null,j=false;function k(){return function(){}}function l(a){return function(){return this[a]}}function n(a){return function(){return a}}var o,q=this;
function ba(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ca(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function r(a,b,c){r=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ca:da;return r.apply(h,arguments)}function fa(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ga(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ja(a,b){var c="",e=ka(encodeURIComponent(a));e.splice(b||5,e.length);s(e,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",e;a>0;)e=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+b,a>>>=6;a=b}c+=a});return c}
function ka(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,e=4023233417,f=2562383102,i=271733878,p=3285377520,B=[],m,C,L,P,S,ea=Math.ceil((a.length/4+2)/16),aa=[ea],N=0,E;N<ea;N++){aa[N]=[];for(m=0;m<16;m++)aa[N][m]=a.charCodeAt(N*64+m*4)<<24|a.charCodeAt(N*64+m*4+1)<<16|a.charCodeAt(N*64+m*4+2)<<8|a.charCodeAt(N*64+m*4+3)}N=(a.length-1)*8;a=ea-1;aa[a][14]=Math.floor(N/Math.pow(2,32));aa[a][15]=N&4294967295;for(N=0;N<ea;N++){for(E=0;E<16;E++)B[E]=
aa[N][E];for(E=16;E<80;E++)B[E]=(B[E-3]^B[E-8]^B[E-14]^B[E-16])<<1|(B[E-3]^B[E-8]^B[E-14]^B[E-16])>>>31;a=c;m=e;C=f;L=i;P=p;for(E=0;E<80;E++)S=Math.floor(E/20),S=(a<<5|a>>>27)+(S==0?m&C^~m&L:S==1?m^C^L:S==2?m&C^m&L^C&L:m^C^L)+P+b[S]+B[E]&4294967295,P=L,L=C,C=m<<30|m>>>2,m=a,a=S;c=c+a&4294967295;e=e+m&4294967295;f=f+C&4294967295;i=i+L&4294967295;p=p+P&4294967295}return[c,e,f,i,p]}
function la(a){var b=q.navigator,c=q.window.screen,e=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];s(b.plugins,function(a){e.push(a.name+a.description+a.filename+a[0].type)});b=q.performance;e=e.concat([b&&b.now?b.now():"",document.title,q.location.href,t(),ga()]);return e.concat(a||[]).join()}function u(a,b,c){var e=Array.prototype.slice,f=e.call(arguments,2);return function(){return a.apply(b,f.concat(e.call(arguments)))}}
function v(a){return typeof a!=="undefined"}function ma(a){return a.replace(/^www\./,"")}function w(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!!e):a.attachEvent&&a.attachEvent("on"+b,c)}function na(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function oa(a){return typeof a==="number"}function x(a){return typeof a==="string"}function pa(a){return typeof a==="function"}
function qa(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function t(){return(new Date).getTime()}function sa(a){return encodeURIComponent(a)}function s(a,b){if((!!a&&a.constructor===Object)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var e=a.length;c<e;c++)if(b(a[c],c)===j)break}}function ta(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c]))return c;return-1}function ua(a){var b=q.pSUPERFLY_video,a=ta(b,a);if(a>-1)return b[a]}
function va(a){return a===d?0:t()-a}function wa(a,b){var c,e,f="c"+Math.round(Math.random()*1E9);e=250;a+=(a.indexOf("?")>-1?"&":"?")+(c||"callback")+"=_cb_call."+f;c=document.createElement("script");var i=xa(f,c);c.id=f;c.type="text/javascript";c.charset="UTF-8";c.src=a;var p=document.getElementsByTagName("head");if(p=p&&p[0]){var B=q._cb_call||(q._cb_call={});e=setTimeout(ya(b,i),e);B[f]=za(b,i,e);p.appendChild(c)}}function ya(a,b){return function(){b();a(d,"TIMEOUT")}}
function za(a,b,c){return function(e){b(c);a(e)}}function xa(a,b){return function(c){c&&clearTimeout(c);setTimeout(function(){b&&b.parentNode&&b.parentNode.removeChild(b)},0);var e=q._cb_call,f=j;if(e&&(c?delete e[a]:e[a]=Aa,s(e,function(){f=g;return j}),!f))try{delete q._cb_call}catch(i){q._cb_call=d}}}function Aa(){}
function Ba(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],e=0,f=b.length;e<=f;e++)c[e]=[e];for(var i=0,p=a.length;i<=p;i++)c[0][i]=i;for(var B,m,C,e=1;e<=f;e++)for(i=1;i<=p;i++)B=e-1,m=i-1,C=c[B][m],b.charAt(B)==a.charAt(m)?c[e][i]=C:(m=c[e][m]+1,B=c[B][i]+1,C+=2,c[e][i]=Math.min(m,B,C));return c[b.length][a.length]}function Ca(a){return a===d?0:t()-a}function Da(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}
var Ea,Fa=q.setInterval,Ga=q.clearInterval,Ha=q.setTimeout,Ia=q.clearTimeout;function Ja(a){switch(a){case d:return"undefined";case "":return"empty";default:return a}}function Ka(a){switch(a){case "undefined":break;case "empty":return"";default:return a}};function La(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var e=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&e.push(c[f]);return e}function Ma(a,b,c){return a===d?j:c===d&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?j:Ma(a.parentNode,b,c)}
function Na(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=La("data-cb-scroll-element"))&&a.length)return a[0][c];if(oa(q[b]))return q[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function Oa(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function Pa(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Qa(a,b,c){var e=a.ownerDocument.documentElement,f=0,i=v(c)?c+1:-1;x(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==e&&f!==i;){if(c(a))return a;a=a.parentNode;f++}return h}function Ra(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Sa(a){a=a||window.event;return!a?h:Qa(a.target||a.srcElement,Ra,10)}function Ta(a,b){var c=document.createElement(a);s(b,function(a,b){c.setAttribute(b,a)});return c};function Ua(){this.oa={};this.Oa=1}function y(a,b,c,e){a.Oa++;a.oa[b]=a.oa[b]||{};a.oa[b][a.Oa]=[c,e];return a.Oa}function Va(a,b){if(x(b))a.oa[b]=d,delete a.oa[b];else if(oa(b)){var c=g;s(a.oa,function(a){s(a,function(f,i){if(parseInt(i,10)===b)return a[i]=d,delete a[i],c=j});return c})}}Ua.prototype.Da=function(a,b){if(this.oa[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];s(this.oa[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
Ua.prototype.addEventListener=function(a,b){var c=y(this,a,b);b._cbEventId=c};Ua.prototype.removeEventListener=function(a,b){this.oa[a]&&this.oa[a][b._cbEventId]&&this.oa[a][b._cbEventId][0]===b&&Va(this,b._cbEventId)};var z=new Ua;var A={};
A.N=function(){A.Fb?A.lb("pageload"):(A.Fc=[{target:q,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:q,event:"resize"},{target:document.body,event:"mousedown"}],A.sb=h,A.Wb=j,A.Ua=h,A.mc={},A.ub={},s(A.Fc,function(a){var b=a.event;w(a.target,b,function(a){A.lb.call(A,b,a)})}),y(z,"f",function(){A.lb("focus")}),A.lb("pageload"),w(document.body,"click",function(a){(a=Sa(a))&&z.Da("c",a)},g),w(document.body,"contextmenu",function(a){(a=Sa(a))&&
z.Da("r",a)}),A.Fb=g)};A.Kc=function(){var a,b=A.mc.keydown;if(b===d)return j;b=t()-b;return b<=(a||15E3)&&b>=0};A.Sa=function(a,b){var c=A.ub[a];if(!c)return"";var b=b||t(),e,f=0;s(c,function(a){e=Math.floor((b-a)/1E3);e>=0&&e<16&&(f|=1<<e)});c=("0000"+f.toString(16)).slice(-4);return c=="0000"?"":c};A.Gd=function(){A.ub={}};A.dc=100;A.lb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}A.Md(a);A.sb===h?A.zc():A.Wb=g};
A.Md=function(a){var b=t();A.mc[a]=b;var c=A.ub[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();A.ub[a]=c};A.zc=function(){A.sb=Ha(A.Qc,A.dc);z.Da("a");A.Ua!==h&&Ia(A.Ua);A.Ua=Ha(function(){z.Da("i");Ia(A.Ua);A.Ua=h},5E3+A.dc)};A.Qc=function(){Ia(A.sb);A.sb=h;if(A.Wb)A.Wb=j,A.zc()};var Wa,Xa,Ya,Za,$a;(function(){var a,b;s(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof q.document[a]==="boolean")return b=c,j});b!==d&&(Za=a,$a=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),Ya=b+"visibilitychange")})();var ab=j;function bb(){ab=$a&&q.document[$a]==="prerender"?g:j}function cb(){Xa=g;z.Da("f")}function db(){Xa=j;z.Da("b")}
function eb(a,b,c){q.addEventListener?q.addEventListener(a,c,j):q.document.attachEvent&&q.document.attachEvent(b,c)}function fb(){var a=g;q.document.hasFocus&&(a=q.document.hasFocus());var b=j;Za&&(b=q.document[Za]);return a&&!b}function gb(){fb()?cb():db()}function hb(a){bb();if(ab){var b=j,c=function(){b||(bb(),ab||(b=g,a(),q.window.setTimeout(function(){q.document.removeEventListener(Ya,c,j)},100)))};q.document.addEventListener(Ya,c,j)}else a()};function ib(){this.k=q._sf_async_config||{};this.hc=u(this.tc,this)}ib.prototype.N=function(){this.vc=0};ib.prototype.tc=k();ib.prototype.Za=function(a){if(!ab){var b=this.hc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};ib.prototype.xa=function(){this.hc=h};function jb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),s(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function kb(a,b){var c="",e=q.location.href.split("?");if(e.length){var e=jb(e[1]),f=b||a;e[f]&&(c=e[f])}return c}function lb(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function mb(a){var b=[];s(nb,function(c){var e=a[c];v(e)&&(Object.prototype.toString.call(e)==="[object Array]"?s(e,function(a){b.push(c+"="+a)}):e&&e.constructor===Object?s(e,function(a,c){b.push(c+"="+a)}):((e+"").length||c=="r")&&b.push(c+"="+e))});b.push("_");return b.join("&")}
function ob(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),e=q.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=e.protocol+a;else if(a.indexOf("/")===0)var f=lb(e.protocol,e.port)?"":e.port,a=e.protocol+"//"+e.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||e.href,i=f.indexOf("?");i===-1&&(i=f.indexOf("#"));if(i===-1)i=f.length;i=f.lastIndexOf("/",i);a=i===-1?"/"+a:f.substr(0,i)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=e.hostname;if(b.protocol==="")b.protocol=e.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(lb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function pb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function D(a,b,c){a[b]=a[b]||c}function qb(a,b){for(var c=q[a]||[];c.length;)b(c.shift());q[a]={push:b}}function rb(a){s(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=jb(b.src.split("?")[1]),D(a,"uid",b.uid),D(a,"domain",b.domain),j})}function sb(a,b){return a[b]?encodeURIComponent(a[b]):""}function tb(a){var b={};s(a,function(a,e){e.charAt(0)=="_"&&(b[e]=a)});return b};var F={};F.Nc=function(){try{F.create("_cb_test","1",1);var a=F.F("_cb_test");F.remove("_cb_test");return a==="1"}catch(b){return j}};F.F=function(a){a+="=";var b="";s(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
F.create=function(a,b,c){var e=q._sf_async_config;if(e&&e.noCookies)return"";e=new Date;e.setTime(t()+c*1E3);a=a+"="+b+("; expires="+e.toGMTString())+"; path=/";return document.cookie=a};F.remove=function(a){return F.F(a)?F.create(a,"",-86400):""};var G={};G.Y=function(a){var b=q._sf_async_config;if(!a&&b&&b.noCookies)return h;if(G.Y.yb!==d)return G.Y.yb;var a=t()+"",c,e;try{if((e=q.localStorage).setItem(a,a),c=e.getItem(a)===a,e.removeItem(a),c)return G.Y.yb=e}catch(f){}return G.Y.yb=h};G.F=function(a){var b=G.Y();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&t()>c)?(G.remove(a),""):b.getItem(a)||""};
G.create=function(a,b,c){var e=G.Y();if(e){var f=new Date;f.setTime(t()+c*1E3);try{e.setItem(a,b),e.setItem(a+"_expires",f.getTime())}catch(i){}}};G.remove=function(a){var b=G.Y();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function ub(a){this.ob=a||"";this.Rc=G.Y()!==h||F.Nc();this.Vb=j;vb(this)}o=ub.prototype;o.isSupported=l("Rc");
function vb(a){if(!F.F("_cb_ls")){var b=G.Y()!==h,c=F.F("_SUPERFLY_nosample");c&&s(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,g)});var e=F.F("_chartbeat3");e&&(a.create("_v__chartbeat3",e,2592E3,g),F.remove("_chartbeat3"));b&&((b=F.F("_chartbeat2"))&&a.create("_chartbeat2",b,63072E3,g),(b=F.F("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,63072E3,g),(b=F.F("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));F.create("_cb_ls","1",2592E3)}}
function wb(a){var b=a.Vb;a.Vb=j;return b}o.create=function(a,b,c,e){a=e?a:this.ob+a;(G.Y()?G:F).create(a,b,c);G.Y()&&F.create(a,b,c)};o.update=function(a,b,c,e,f,i,p){a=e?a:this.ob+a;f=x(f)?f:"::";e=(e=this.F(a,g))?e.split(f):[];if(p&&e.length){var B=p(b),m=ta(e,function(a){return p(a)===B});m!==-1&&e.splice(m,1)}oa(i)&&e.length>=i&&e.splice(0,e.length-i+1);e.push(b);this.create(a,e.join(f),c,g)};
o.F=function(a,b){var a=b?a:this.ob+a,c=(G.Y()?G:F).F(a);if(!c&&G.Y()&&(c=F.F(a))&&F.F("_cb_ls")){this.Vb=g;var e;switch(a){case "_SUPERFLY_nosample":e=600;break;case "_chartbeat4":e=3600;break;case "_cb_cp":e=3600;break;case "_chartbeat3":e=2592E3;break;default:e=63072E3}G.create(a,c,e)}return c};o.remove=function(a,b){a=b?a:this.ob+a;(G.Y()?G:F).remove(a);G.Y()&&F.remove(a)};function xb(a){var b=h;if(a&&(b=yb()))return b;var c=q.location,b=zb(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),e=/&utm_[^=]+=[^&]+/ig;(c=e.exec(c.search))&&(a=a.replace(e,""));e=/\?utm_[^=]+=[^&]+(.*)/i;(c=e.exec(a))&&(a=a.replace(e,c[1]!=""?"?"+c[1]:""));return b+a}function yb(){var a=h;s(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=ob(b.href),a=zb(b.pathname)+b.search+b.hash,j});return a}
for(var Ab={},Bb=0;Bb<81;Bb++)Ab["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Bb)]=g;function Cb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Ab[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function zb(a){if(!x(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Cb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};var H={Hc:{IDLE:0,Qd:1,Pd:2,Gc:3},pa:0};H.N=function(){if(!H.Fb)y(z,"a",H.Wc,H),y(z,"i",H.Zc,H),y(z,"f",H.Yc,H),y(z,"b",H.Xc,H),H.Fb=g};H.H=function(){return H.pa};H.Wc=function(){H.pa===1?H.Aa(3):H.pa===0&&H.Aa(2)};H.Zc=function(){H.pa===3?H.Aa(1):H.pa===2&&H.Aa(0)};H.Yc=function(){(H.pa===0||H.pa===2)&&H.Aa(3)};H.Xc=function(){H.pa===3?H.Aa(2):H.pa===1&&H.Aa(0)};H.Aa=function(a){H.pa=a;z.Da("s",a)};function Db(a,b){this.Db=a||d;this.Jb=b||d;this.Va=this.Na=0;this.Eb=u(this.Eb,this)}o=Db.prototype;o.N=function(){this.Va=this.Na=0;this.ab=h;this.Id=y(z,"s",this.lc,this);this.lc(H.H())};o.lc=function(a){Ga(this.ab);this.ab=h;if(a===H.Hc.Gc)this.ab=Fa(this.Eb,1E3)};o.Eb=function(){if(this.Db===d||this.Db())this.Na++,this.Va++,this.Jb&&this.Jb()};o.terminate=function(){Ga(this.ab);this.ab=h;Va(z,this.Id)};o.xa=function(){this.terminate();this.Jb=this.Db=d};function I(){ib.call(this);this.Fa=[];this.G=new ub(this.Bc);this.na=new Db;this.Lb=u(this.Xa,this);w(q,"unload",this.Lb);hb(u(this.N,this))}fa(I,ib);o=I.prototype;o.Sb=g;
o.N=function(){I.ma.N.call(this);this.hb=this.Ja=0;this.Ba=t();this.za=ja(Eb(this));this.Qb=g;this.jb=72E5;if(this.Sb){var a=+this.k.sessionLength;if(!isNaN(a))this.jb=a*6E4}a=J(Fb);if(!a){var a=[],b=this.G.F("_chartbeat2",g);b.length>0&&(a=b.split("."));a.length>4&&(a=[]);var b=t(),c=b-+(a[1]||0),e=b-+(a[2]||0),f=Gb,c=a[0]&&c>18E5&&e<2592E6?0:1;K()[f]=c;c="1";e=a&&+a[2];f=a&&a[3];if(a&&e&&f)if(c=Math.abs((qa(b)-qa(e))/864E5)){c=Math.min(c,16)-1;for(e="";c--;)e+=0;c=(f+e+"1").slice(-16)}else c=f;
f=c;a[0]||(a[0]=this.k.utoken||ja(Eb(this),3),a[1]=b);a[2]=b;a[3]=f;this.k.utoken=this.bb;this.G.create("_chartbeat2",a.join("."),63072E3,g);b=Fb;K()[b]=a}this.Xd=a.join(".");var i;f=+a[1];c=+a[2];if((b=a[3])&&f&&c)i=(Math.min((Math.abs((qa(c)-qa(f))/864E5)||0)+1,16,b.length)-1).toString(16),i+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.kc=i;this.Hb=J(Gb,1);this.bb=a[0];this.na.N();H.N();A.N();Wa||(Xa=fb(),Ya&&q.document.addEventListener&&q.document.addEventListener(Ya,gb,j),eb("focus","onfocusin",
cb),eb("blur","onfocusout",db),Xa&&cb(),Wa=g);this.Wa=0;this.Jc=y(z,"a",this.fd,this)};function Hb(a){if(!a.G.F("_SUPERFLY_nosample")&&!ab)a.ed?a.qb():(a.ed=g,!q._sf_async_config&&!q._cbq?(a.nb=u(a.qb,a),w(q,"load",a.nb)):a.qb())}o.qb=function(){var a=q._sf_startpt,b=q._sf_endpt;if(oa(a))this.Ya=oa(b)?b-a:t()-a;A.N();a=u(this.ka,this);this.Ia=Fa(a,15E3);this.ka()};
o.ka=function(){var a=this.na.Va,a=this.k.reading&&+this.k.reading||a>0;if(this.hb<this.Ja&&!a)this.hb++;else{var b;if(Ea===d)b=q.navigator.userAgent,Ea=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Ea;b&&!a?this.hb++:(a?this.Ja=0:this.xb(),this.hb=0,this.Fa.push(0),this.Fa.length>18&&this.Fa.shift(),this.Sb&&t()-this.Ba>=this.jb?this.terminate():this.Ma())}};
o.tc=function(){this.Fa.push(1);var a=0;s(this.Fa,function(b){a+=b});a<3?(this.Qb=g,this.xb()):(this.terminate(),this.G.create("_SUPERFLY_nosample","1",600))};o.Xa=k();o.fd=function(){var a=Ib(this);this.Wa=Math.max(this.Wa,a)};function Ib(a){return Na(!!a.k.scrollElement)}o.xb=function(){var a=this.Ja;this.Ja=a=a?Math.min(a*2,16):1};o.gb=function(){this.Xa();this.terminate()};o.Ac=function(){this.N();Hb(this)};
function Jb(a){if(a.k.virtualReferrer)return g;a=(document.referrer||"").indexOf("://"+q.location.hostname+"/");return a!=-1&&a<9}function Kb(a){a=a.k.virtualReferrer;if(!a&&(a=document.referrer||"")){var b=ob(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=zb(b.pathname),a=pb(b)}return encodeURIComponent(a)}function Lb(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Eb(a){a=[Kb(a),Pa("Width"),Pa("Height")];return la(a)}
function Mb(a){var b=[],c=a.G.F("_chartbeat4");c&&(s(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.G.remove("_chartbeat4"));return b}o.terminate=function(){this.na.terminate();Va(z,this.Jc);this.nb!==d&&na(q,"load",this.nb);Ga(this.Ia);var a=Fb;K()[a]=d;a=Gb;K()[a]=d};o.xa=function(){this.terminate();na(q,"unload",this.Lb);this.Lb=this.nb=this.G=this.Fa=this.k=h;this.na.xa();this.na=h;I.ma.xa.call(this)};var Fb="d",Gb="n";function J(a,b){var c=K();return v(b)&&!v(c[a])?b:c[a]}function K(){v(q._cb_shared)||(q._cb_shared={});return q._cb_shared};function Nb(a){for(var b=J("m")||[];b.length;)a(b.shift());a={push:a};K().m=a};function Ob(a){var b=a.offsetLeft,c=a.offsetTop,e=Pb(a);b+=e.x;c+=e.y;for(var f=j,e=a.offsetParent;a&&a!==d&&a!==document.body;){if(a===e)e=Pb(a),b+=a.offsetLeft+e.x,c+=a.offsetTop+e.y,e=a.offsetParent;if(Qb(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function Qb(a,b){var c={},e,f;q.getComputedStyle?e=q.getComputedStyle(a,h):a.currentStyle?f="currentStyle":a.style&&(f="style");s(b,function(b){c[b]=e?e[b]||e.getPropertyValue(b):a[f][b]});return c}var Rb=/matrix(3d)?\((.*)\)/;function Pb(a){var b={x:0,y:0},a=Qb(a,["transform"]).transform;if(!x(a))return b;var c=a.match(Rb);if(!c)return b;var a=c[2].split(", "),e;v(c[1])?(c=12,e=13):(c=4,e=5);b.x=parseInt(a[c],10);b.y=parseInt(a[e],10);return b};function Sb(){var a=q.location.href,a=a.replace(/-{2,}/g,"-"),a=ob(a);a.pathname=zb(a.pathname);return a}
function Tb(a){var b=F.F("_chartbeat6");if(!b)return h;var b=b.split("::"),c,e;if(b.length===1)c=b[0].split(","),e=0;else{var f,i=Sb(),p=pb(i);s(b,function(a,b){var i=a.split(","),m=Ba(p,decodeURIComponent(i[0]));if(m===0)return c=i,e=b,j;if(f===d||m<f)f=m,c=i,e=b})}b.splice(e,1);a="_chartbeat6="+b.join("::")+Ub(a);document.cookie=a;var a=[],b=c[0],i=c[1],B=c[2];c.splice(0,3);for(var m=c.length/2,C=0;C<m;C++)a.push({Ud:b,origin:i,Ka:B,Tc:c[C*2],Nd:c[C*2+1]});return a}
function Ub(a){var b="",c;if(!(a&&a.constructor===Object))return b;a.qc&&(c=new Date,c.setTime(c.getTime()+a.qc),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function Vb(a){var b=a.topStorageDomain,a=a.domain,c=q.location.hostname;return b?b:Wb(c,a)?a:c.replace(/^www\./,"")}function Wb(a,b){if(a===b)return g;for(var c=b.split("."),e=a.split(".");c.length;){if(e.length===0)return j;if(c.pop()!==e.pop())return j}return g}
function Xb(a,b,c,e){this.Vc=a;this.Uc=b;this.Od=c;this.Ka=e};function Yb(a,b){for(var c=b||document.documentElement,e=[],f=h,i=a,p,B,m,C,L,P;i&&i!==c;){p=i.nodeName.toLowerCase();f=i;B=f.nodeName;if((i=i.parentNode)&&i!==document.documentElement){m=i.children;C=0;for(L=0,P=m.length;L<P;L++){if(f===m[L]){p+="["+(1+L-C)+"]";break}m[L].nodeName!==B&&C++}}e.unshift(p)}return e.join("/")};function Zb(){this.Bc="_t_";I.call(this)}fa(Zb,I);o=Zb.prototype;
o.N=function(){Zb.ma.N.call(this);rb(this.k);var a=q.location;D(this.k,"mabServer","mabping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);D(this.k,"path",xb(!!this.k.useCanonical));this.ra=ma(a.hostname);this.k.domain=ma(this.k.domain);this.Ld=Vb(this.k);this.Ra=this.ib=j;this.ic=[];var b=this,a=Tb({domain:"."+this.Ld,qc:6E4,path:"/"});if(a!==h)this.ib=g,s(a,function(a){b.ic.push(new Xb(a.origin,a.Tc,a.Nd,a.Ka))});this.rc=0;this.rb=h;Nb(u(this.cd,this))};
o.Ma=function(){var a=this.na.Na,b=$b(this),c,e=this;this.ib&&s(this.ic,function(f){c=b+"&x="+f.Uc+"&v="+f.Od+"&ml="+f.Ka+"&xo="+f.Vc+"&e="+a;e.Za(c)});!this.Ra&&this.rb&&ac(this,this.rb);this.Ra=g};o.qb=function(){var a=q._sf_startpt,b=q._sf_endpt;if(oa(a))this.Ya=oa(b)?b-a:t()-a;A.N();if(this.ib)a=u(this.ka,this),this.Ia=Fa(a,500);this.ka()};o.ka=function(){var a,b;this.Ra?(a=this.na.Na,b=this.rc*15,a-b>=15&&(this.Ma(),this.rc+=1),a>=45&&this.terminate()):this.Ma()};
function $b(a){var b=a.k;return(q.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ra)+"&u="+a.bb+"&c="+Math.round((t()-a.Ba)/600)/100}o.Xa=k();o.Jd=function(a){var b=a.d,c=h;b!==h&&(c={Tb:b.s,Ka:b.g,pc:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Ra?ac(this,a):this.rb=a};
function ac(a,b){var c=$b(a),e=b.status,f=b.data;if(e=="s"&&f!==h){var i=u(a.Za,a);f.Tb&&f.Tb.constructor===Object&&s(f.Tb,function(a,b){i(c+"&x="+b+"&v="+a+"&ml="+f.Ka+"&e=-1")});Object.prototype.toString.call(f.pc)==="[object Array]"&&s(f.pc,function(a){i(c+"&me=3&ml="+f.Ka+"&x="+a)})}else e=="e"&&a.Za(c+"&me="+b.code)}o.cd=function(a,b){for(var c=0,e=arguments.length;c<e;c++){var a=arguments[c],f=a.shift();f==="t"?this.Jd.apply(this,a):f==="v"&&this.Hd.apply(this,a)}};
o.gb=function(){K().m=[];v(this.$b)&&this.$b();Zb.ma.gb.call(this)};o.Hd=function(a){this.$b=a};o.terminate=function(){this.$b=this.Vd=d;this.rb=h;this.Ra=this.ib=d;Zb.ma.terminate.call(this)};if(!q.pSUPERFLY_mab){var bc=new Zb,cc={};cc.evps=u(bc.gb,bc);cc.svps=u(bc.Ac,bc);q.pSUPERFLY_mab=cc;Hb(bc)};var dc,ec,fc;
function gc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);hc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=v(d)?d:{},b.src=a,a=Ta("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],v(d)?d.appendChild(a):b&&b.appendChild(a)}}
function hc(){Ia(ec);ec=d;na(q,"message",gc);fc&&fc.parentNode&&fc.parentNode.removeChild(fc);fc=d};function ic(){var a=q._sf_async_config&&q._sf_async_config.domain;if(a&&!dc){dc=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);w(q,"message",gc);ec=Ha(hc,1E4);var b=v(d)?d:{};b.src=a;a=Ta("iframe",b);a.style.display="none";v(d)?d.appendChild(a):document.body&&document.body.appendChild(a);fc=a}}
function jc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=G.Y(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),ic(),na(q,"message",jc))}};function kc(){"postMessage"in window&&w(q,"message",u(this.$c,this));I.call(this);qb("_cbq",u(this.yc,this))}fa(kc,I);
kc.prototype.N=function(){kc.ma.N.call(this);var a=this.bb;K().u=a;a=this.za;K().t=a;this.wb=h;rb(this.k);a=q.location;D(this.k,"pingServer","ping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);this.k.path=this.k.path?zb(this.k.path):xb(!!this.k.useCanonical);this.ra=ma(a.hostname);this.k.domain=ma(this.k.domain);this.Lc=y(z,"c",this.ld,this);this.Mc=y(z,"r",this.md,this);this.Ha=h};kc.prototype.Ic=function(a){this.wb=a};
kc.prototype.Xa=function(){this.G.update("_chartbeat4",["t="+this.za,"E="+this.na.Na,"x="+Ib(this),"c="+Math.round((t()-this.Ba)/600)/100,"y="+Pa("Height"),"w="+Oa()].join("&"),3600,d,d,1)};var nb="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR".split(",");o=kc.prototype;
o.Ma=function(a){this.vc++;var b={};b.g=this.k.uid;b.g0=sb(this.k,"sections");b.g1=sb(this.k,"authors");b.g2=sb(this.k,"zone");b.g3=sb(this.k,"sponsorName");b.g4=sb(this.k,"type");!this.k.noCookies&&this.G.isSupported()?b.n=this.Hb:b.nc=1;b.c=Math.round((t()-this.Ba)/600)/100;b.E=this.na.Na;var c=Ib(this);this.Wa=Math.max(this.Wa,c);b.x=c;b.m=this.Wa;b.y=Pa("Height");b.o=Pa("Width");b.w=Oa();b.b=this.Ya?this.Ya:"";if(this.kc)b.f=this.kc;b[""]=tb(this.k);b.t=this.za;b.V=68;b.tz=(new Date).getTimezoneOffset();
b.sn=this.vc;c=this.na.Va;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.bb;b.d=encodeURIComponent(this.ra);b.j=Math.round((this.Ja+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var e=b.c*6E4+this.Ba;b.eD=A.Sa("mousedown",e);b.eM=A.Sa("mousemove",e);b.eK=A.Sa("keydown",e);b.eR=A.Sa("resize",e);b.eS=A.Sa("scroll",e);A.Gd();A.Kc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Jb(this);if(this.Qb){this.Qb=j;if(c)this.Ha=lc(this);b.i=Lb(this);e=this.k.hudTrackable;
e!==d&&(b.L=e?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.Ha){if(b.v=encodeURIComponent(this.Ha.path),b.K=mc(this.Ha),this.Ha.Ib>1)b.l1=this.Ha.Ib}else b.v=Kb(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=Kb(this);c=Ja(b.v);K().v=c;c=Ja(b.r);K().r=c;b.A=this.wb?this.wb:"";b._c=kb("utm_campaign",this.k.campaignTag);b._m=kb("utm_medium",this.k.mediumTag);b.z=Mb(this);b.C=this.k.mobileApp?1:"";b.KK=a?mc(a):"";b.l=wb(this.G)?1:"";this.na.Va=0;this.Za((q.location.protocol||
"http:")+"//"+this.k.pingServer+"/ping?"+mb(b))};
o.$c=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.ra)){var c=a.data;if(x(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.yc(a));else if(c=="cbdata?"){var c="&u="+J("u"),e="&t="+J("t"),f="&v="+J("v"),i="&r="+J("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+Lb(this)+"&referrer="+Kb(this)+"&internal="+(Jb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ra)+
c+e+f+i+"&utoken="+this.bb;a.source.postMessage(b,"*")}}};o.yc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.Ja=0};function nc(a){a=a.replace(/-{2,}/g,"-");a=ob(a);a.pathname=zb(a.pathname);return a}o.ld=function(a){oc(this,a,"c")};o.md=function(a){oc(this,a,"r")};
function oc(a,b,c){if(a.Sb&&t()-a.Ba>=a.jb)a.terminate();else{var e=b.href||"",e=nc(e);if(!(e.hostname!==q.location.hostname||e.protocol.indexOf("http")!==0)){var e=pb(e),f=Qa(b,function(a){return a.id}),i=Yb(b,f);f&&(i&&(i="/"+i),i="*[@id='"+f.id+"']"+i);f=ja(i);b=Ob(b);c={left:b.x,top:b.y,path:a.k.path,href:e,cc:f,bc:i,Ub:c,Ib:0};a.Ma(c);a.G.update("_chartbeat5",pc(c),60,j,d,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function mc(a){return[a.left,a.top,a.cc,encodeURIComponent(a.bc),a.Ub,encodeURIComponent(a.href)].join("::")}function pc(a){var b=encodeURIComponent(a.bc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.cc,b,a.Ub].join(",")}
function lc(a){var b=a.G.F("_chartbeat5");if(!b)return h;var c=b.split("::"),b=c.length,e,f;if(b===1)e=c[0].split(","),f=0;else{var i,p=nc(q.location.href),B=pb(p);s(c,function(a,b){var c=a.split(","),p=Ba(B,decodeURIComponent(c[3]));if(p===0)return e=c,f=b,j;if(i===d||p<i)i=p,e=c,f=b})}c.splice(f,1);a.G.create("_chartbeat5",c.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),href:decodeURIComponent(e[3]),cc:e[4]||
"",bc:a,Ub:e.length>6?e[6]:"c",Ib:b}}o.terminate=function(){Va(z,this.Lc);Va(z,this.Mc);kc.ma.terminate.call(this)};var M="ct",O="s1";function Q(a){this.a=a;this.B=this.D=j;this.q=t();this.ia()}o=Q.prototype;o.ia=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.ga();this.a.on("play",u(this.ga,this));this.a.ready(u(this.la,this))};o.la=function(){this.fa=this.a.mediainfo;this.D=g};o.ga=function(){this.B=g};o.O=function(){return this.D&&this.J()!==""};
o.Bb=function(){var a;this.a.cb_configs&&this.a.cb_configs.domain?a=this.a.cb_configs.domain:!a&&q._sf_async_config&&q._sf_async_config.domain&&(a=q._sf_async_config.domain);return a};o.Cb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&q._sf_async_config&&q._sf_async_config.uid&&(a=q._sf_async_config.uid);return a};
o.J=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("name")?this.fa.name:this.a.el().getAttribute("title"))||""};o.M=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("id")?this.fa.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};o.U=function(){return M};o.P=n("");o.ca=function(){var a=this.a.duration();return Da(a)};
o.H=function(){return!this.B?O:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};o.X=function(){var a=this.a.currentTime();return Da(a)};o.T=n(-1);o.ba=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("thumbnail")?this.fa.thumbnail:this.a.poster())||""};o.Z=k();o.S=k();o.da=function(){return Ca(this.q)};
o.$=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.sections&&(a=q._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};o.Q=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.authors&&(a=q._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};
o.aa=n("BCN");Q.prototype.getStrategyName=Q.prototype.aa;Q.prototype.isReady=Q.prototype.O;Q.prototype.getHost=Q.prototype.Bb;Q.prototype.getUid=Q.prototype.Cb;Q.prototype.getTitle=Q.prototype.J;Q.prototype.getVideoPath=Q.prototype.M;Q.prototype.getContentType=Q.prototype.U;Q.prototype.getAdPosition=Q.prototype.P;Q.prototype.getTotalDuration=Q.prototype.ca;Q.prototype.getState=Q.prototype.H;Q.prototype.getCurrentPlayTime=Q.prototype.X;Q.prototype.getBitrate=Q.prototype.T;
Q.prototype.getThumbnailPath=Q.prototype.ba;Q.prototype.getPlayerType=Q.prototype.Z;Q.prototype.getAutoplayType=Q.prototype.S;Q.prototype.getViewStartTime=Q.prototype.da;Q.prototype.getSections=Q.prototype.$;Q.prototype.getAuthors=Q.prototype.Q;Q.verify=function(a){return a.controlBar!==d};function R(a){this.Oa=this.ra=d;this.D=j;this.xc=this.fc=-1;this.ta=h;this.a=a;this.B=j;this.Mb=g;this.q=t();this.Nb="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var e=a[c];if((e.indexOf("chartbeat")>=0||e.indexOf("localhost")>=0)&&e.indexOf(".js")>=0){this.Nb=e;break}}if(this.Nb)a=jb(this.Nb),this.ra=a.domain,this.Oa=a.uid;a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);b.getReady()?
this.uc():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,r(this.uc,this))}o=R.prototype;
o.uc=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.fc=Math.round(a)});b.getCurrentVideo(function(a){c.ta=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,r(this.vd,this));b.addEventListener(a.STOP,r(this.xd,this));b.addEventListener(a.COMPLETE,r(this.nd,this));b.addEventListener(a.BEGIN,r(this.ga,this));this.D=g};o.vd=function(a){this.xc=a.position;this.va=this.Mb=j};o.xd=function(){this.Mb=g};
o.nd=function(){this.va=g};o.ga=function(){this.va=j;if(!this.B)this.B=g};o.O=l("D");o.J=function(){var a="";this.ta&&(a=this.ta.displayName);return a};o.M=function(){var a="";this.ta&&(a="video@"+this.ra+"/"+this.ta.id);return a};o.U=function(){return M};o.P=n("");o.ca=l("fc");o.H=function(){return!this.B?O:this.va?"s4":this.Mb?"s3":"s2"};o.X=l("xc");o.T=n(-1);o.ba=function(){var a="";this.ta&&(a=this.ta.thumbnailURL);return a};o.Z=k();o.da=function(){return isNaN(this.q)?0:va(this.q)};o.Q=k();
o.$=function(){var a;this.ta&&(a=this.ta.tags);return a};o.S=n("unkn");o.aa=n("BC");o.Bb=l("ra");o.Cb=l("Oa");R.prototype.isReady=R.prototype.O;R.prototype.getTitle=R.prototype.J;R.prototype.getVideoPath=R.prototype.M;R.prototype.getContentType=R.prototype.U;R.prototype.getAdPosition=R.prototype.P;R.prototype.getTotalDuration=R.prototype.ca;R.prototype.getState=R.prototype.H;R.prototype.getCurrentPlayTime=R.prototype.X;R.prototype.getBitrate=R.prototype.T;R.prototype.getThumbnailPath=R.prototype.ba;
R.prototype.getPlayerType=R.prototype.Z;R.prototype.getViewStartTime=R.prototype.da;R.prototype.getAuthors=R.prototype.Q;R.prototype.getSections=R.prototype.$;R.prototype.getAutoplayType=R.prototype.S;R.verify=function(a){return a===window.brightcove};R.prototype.getStrategyName=R.prototype.aa;R.prototype.getHost=R.prototype.Bb;R.prototype.getUid=R.prototype.Cb;function T(){this.a=window.flowplayer();this.B=this.D=j;this.q=t();this.ua=this.ya=d;this.tb=this.$a="";this.Gb=d;this.ia()}var qc=/url\(['"]?([^'"\)]*)['"]?\)/;o=T.prototype;
o.jc=function(){if(this.a.conf&&(this.tb=this.a.conf.title?this.a.conf.title:"",this.$a=this.a.conf.poster?this.a.conf.poster:"",this.tb&&this.$a))return g;var a=this.M(),b=La("name","param"),c=d;s(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===d&&(b=La("src","video"),s(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=Ma(c,"data-swf");if(b===j)return j;var e=b.style.background;if(e){if(e=
e.match(qc))this.$a=e[1]}else this.$a=b.attributes.poster&&b.attributes.poster.value;this.tb=b.title;if(this.Gb!==d)clearInterval(this.Gb),this.D=g;return g};o.ia=function(){this.a.Zd?this.la():this.a.bind("ready",r(this.la,this));this.a.bind("resume",r(this.ga,this));this.a.Yd&&this.ga()};o.la=function(){this.jc()===j?this.Gb=setInterval(r(this.jc,this),1E3):this.D=g};o.ga=function(){if(!this.B)this.B=g};o.O=l("D");o.J=l("tb");o.M=function(){return this.a.video.url||this.a.video.src};o.U=function(){return M};
o.P=n("");o.ca=function(){return this.a.video.duration};o.H=function(){return!this.B?O:this.a.Wd?"s4":this.a.paused?"s3":"s2"};o.X=function(){return this.a.video.time};o.T=n(-1);o.ba=l("$a");o.Z=k();o.S=k();o.da=function(){return isNaN(this.q)?0:va(this.q)};o.$=l("ya");o.Q=l("ua");o.aa=n("FP");T.prototype.getStrategyName=T.prototype.aa;T.prototype.isReady=T.prototype.O;T.prototype.getTitle=T.prototype.J;T.prototype.getVideoPath=T.prototype.M;T.prototype.getContentType=T.prototype.U;
T.prototype.getAdPosition=T.prototype.P;T.prototype.getTotalDuration=T.prototype.ca;T.prototype.getState=T.prototype.H;T.prototype.getCurrentPlayTime=T.prototype.X;T.prototype.getBitrate=T.prototype.T;T.prototype.getThumbnailPath=T.prototype.ba;T.prototype.getPlayerType=T.prototype.Z;T.prototype.getAutoplayType=T.prototype.S;T.prototype.getViewStartTime=T.prototype.da;T.prototype.getSections=T.prototype.$;T.prototype.getAuthors=T.prototype.Q;T.verify=function(){return!!window.flowplayer};function U(a){this.a=a;this.vb=this.B=this.D=j;this.q=t();this.ua=this.ya=d;this.ia()}o=U.prototype;o.ia=function(){this.a.readyState>0&&this.la();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.ga();this.a.addEventListener("canplay",u(this.la,this));var a=u(this.ga,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",u(this.Dd,this))};o.la=function(){this.D=g};o.ga=function(){this.B=g;this.vb=j};
o.Dd=function(){this.vb=g};o.O=l("D");o.J=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};o.M=function(){return this.a.currentSrc||""};o.U=function(){return M};o.P=n("");o.ca=function(){return Da(this.a.duration)};o.H=function(){return!this.B?O:this.a.ended||this.vb&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.vb?"s3":"s2"};o.X=function(){return Da(this.a.currentTime)};o.T=n(-1);o.ba=function(){return this.a.poster||""};o.Z=k();
o.S=function(){return this.a.autoplay?"auto":"man"};o.da=function(){return Ca(this.q)};o.$=l("ya");o.Q=l("ua");o.aa=n("H5");U.prototype.getStrategyName=U.prototype.aa;U.prototype.isReady=U.prototype.O;U.prototype.getTitle=U.prototype.J;U.prototype.getVideoPath=U.prototype.M;U.prototype.getContentType=U.prototype.U;U.prototype.getAdPosition=U.prototype.P;U.prototype.getTotalDuration=U.prototype.ca;U.prototype.getState=U.prototype.H;U.prototype.getCurrentPlayTime=U.prototype.X;
U.prototype.getBitrate=U.prototype.T;U.prototype.getThumbnailPath=U.prototype.ba;U.prototype.getPlayerType=U.prototype.Z;U.prototype.getAutoplayType=U.prototype.S;U.prototype.getViewStartTime=U.prototype.da;U.prototype.getSections=U.prototype.$;U.prototype.getAuthors=U.prototype.Q;U.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==h;return b&&!a};function V(a){this.a=a;this.B=this.va=this.D=j;this.q=t();this.ia()}o=V.prototype;o.ia=function(){this.a.onReady(r(this.la,this));this.a.onTime(r(this.zd,this));this.a.onComplete(r(this.Ad,this))};o.la=function(){this.D=g};o.zd=function(){this.va=j;if(!this.B)this.B=g};o.Ad=function(){this.va=g};o.O=function(){this.a.getState();return this.D||this.a.getState()!==d};o.J=function(){var a=rc(this);return!a?"":a.title};
function rc(a){if(a.a.getPlaylistIndex===d)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return h;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?h:b[a]}o.M=function(){var a=rc(this);return!a?"":a.file};o.U=function(){return M};o.P=n("");o.ca=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};o.H=function(){if(!this.B)return O;var a=this.a.getState();return this.va?"s4":a.toUpperCase()==="PAUSED"?"s3":"s2"};o.X=function(){return this.a.getPosition()};
o.T=n(-1);o.ba=function(){var a=rc(this);return!a?"":a.image};o.Z=k();o.da=function(){return isNaN(this.q)?0:va(this.q)};o.Q=k();o.$=k();o.S=n("unkn");o.aa=n("JW");V.prototype.getStrategyName=V.prototype.aa;V.prototype.isReady=V.prototype.O;V.prototype.getTitle=V.prototype.J;V.prototype.getVideoPath=V.prototype.M;V.prototype.getContentType=V.prototype.U;V.prototype.getAdPosition=V.prototype.P;V.prototype.getTotalDuration=V.prototype.ca;V.prototype.getState=V.prototype.H;
V.prototype.getCurrentPlayTime=V.prototype.X;V.prototype.getBitrate=V.prototype.T;V.prototype.getThumbnailPath=V.prototype.ba;V.prototype.getPlayerType=V.prototype.Z;V.prototype.getViewStartTime=V.prototype.da;V.prototype.getAuthors=V.prototype.Q;V.prototype.getSections=V.prototype.$;V.prototype.getAutoplayType=V.prototype.S;V.verify=function(a){return v(a.id)&&v(a.registerPlugin)};function W(a){this.a=a;this.Dc="";this.ja=O;this.wa=M;this.qa="";this.q=t();this.ia()}o=W.prototype;o.ia=function(){this.a.kBind("playerStateChange.cb",r(this.Cd,this));this.a.kBind("playerUpdatePlayhead.cb",r(this.ud,this));this.a.kBind("playerPlayEnd.cb",r(this.Bd,this));this.a.kBind("adStart.cb",r(this.hd,this));this.a.kBind("adEnd.cb",r(this.gd,this));this.a.kBind("switchingChangeComplete.cb",r(this.yd,this))};
o.Cd=function(a){switch(a){case "playing":this.ja="s2";break;case "buffering":this.ja="s3";break;case "paused":this.ja="s3"}};o.ud=function(){this.ja="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};o.Bd=function(){this.ja="s4"};o.hd=function(a){this.wa="ad";switch(a){case "pre":this.qa="a1";break;case "post":this.qa="a3";break;case "mid":this.qa="a2";break;case "main":this.qa="a5"}};o.gd=function(){this.wa=M};o.yd=function(a,b){this.Oc=b};
o.O=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=h};o.J=function(){return this.a.evaluate("{mediaProxy.entry.name}")};o.M=function(){if(!this.O())return this.Dc;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.Dc=a)||""};o.U=l("wa");o.P=l("qa");o.ca=function(){var a=this.a.evaluate("{duration}");return Da(a)};o.H=l("ja");o.X=function(){var a=this.a.evaluate("{video.player.currentTime}");return Da(a)};o.T=l("Oc");
o.ba=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};o.Z=k();o.S=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};o.da=function(){return isNaN(this.q)?0:Ca(this.q)};o.$=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
o.Q=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};o.aa=n("KT");W.prototype.getStrategyName=W.prototype.aa;W.prototype.isReady=W.prototype.O;W.prototype.getTitle=W.prototype.J;W.prototype.getVideoPath=W.prototype.M;W.prototype.getContentType=W.prototype.U;W.prototype.getAdPosition=W.prototype.P;W.prototype.getTotalDuration=W.prototype.ca;W.prototype.getState=W.prototype.H;W.prototype.getCurrentPlayTime=W.prototype.X;W.prototype.getBitrate=W.prototype.T;
W.prototype.getThumbnailPath=W.prototype.ba;W.prototype.getPlayerType=W.prototype.Z;W.prototype.getAutoplayType=W.prototype.S;W.prototype.getViewStartTime=W.prototype.da;W.prototype.getSections=W.prototype.$;W.prototype.getAuthors=W.prototype.Q;W.verify=function(a){return typeof a.kBind=="function"};function X(a){this.ec=d;this.a=a;this.oc=d;this.D=j;this.Ea=d;this.B=j;this.ua=this.ya=this.q=d;this.ec=q.OO;this.oc=this.a.mb;this.q=t();this.ia()}o=X.prototype;
o.ia=function(){var a=this.oc,b=this.ec.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",r(this.la,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",r(this.kd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",r(this.ga,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",r(this.jd,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",r(this.td,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",r(this.od,this))};o.la=function(){this.D=g};
o.kd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.Ea=a===0?"a1":sc(a,b)?"a3":"a2"};o.ga=function(){this.B=g};o.jd=function(){this.Ea=d};o.td=k();o.O=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.D=g;return this.D};o.J=function(){var a=this.a.getItem();return a?a.title:""};o.M=function(){return(this.a.getItem()||{}).embedCode||this.a.embedCode||""};o.U=function(){return this.Ea===d?M:"ad"};
o.P=function(){return this.Ea?this.Ea:""};o.ca=function(){var a=this.a.getDuration();return a===-1||isNaN(a)?-1:a*1E3};o.H=function(){if(!this.B)return O;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return sc(a,b)?"s4":"s2"};function sc(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}o.od=function(){this.Ea=d};
o.X=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};o.T=function(){return this.a.getTargetBitrate()};o.ba=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};o.Z=k();o.S=k();o.da=function(){return isNaN(this.q)?0:Ca(this.q||0)};o.$=l("ya");o.Q=l("ua");o.aa=n("OO");X.prototype.getStrategyName=X.prototype.aa;X.prototype.isReady=X.prototype.O;X.prototype.getTitle=X.prototype.J;X.prototype.getVideoPath=X.prototype.M;
X.prototype.getContentType=X.prototype.U;X.prototype.getAdPosition=X.prototype.P;X.prototype.getTotalDuration=X.prototype.ca;X.prototype.getState=X.prototype.H;X.prototype.getCurrentPlayTime=X.prototype.X;X.prototype.getBitrate=X.prototype.T;X.prototype.getThumbnailPath=X.prototype.ba;X.prototype.getPlayerType=X.prototype.Z;X.prototype.getAutoplayType=X.prototype.S;X.prototype.getViewStartTime=X.prototype.da;X.prototype.getSections=X.prototype.$;X.prototype.getAuthors=X.prototype.Q;
X.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("adPlaying")};function Y(a){this.a=a;this.ha=h;this.Ta="";this.ja=O;this.wa=M;this.qa="";this.q=t();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}o=Y.prototype;o.dd=function(a){this.ia(a.controller)};
o.ia=function(a){a.addEventListener("OnLoadRelease",u(this.sc,this));a.addEventListener("OnLoadReleaseUrl",u(this.sc,this));a.addEventListener("OnReleaseStart",u(this.wd,this));a.addEventListener("OnMediaPlay",u(this.qd,this));a.addEventListener("OnMediaStart",u(this.sd,this));a.addEventListener("OnMediaPause",u(this.Kb,this));a.addEventListener("OnMediaComplete",u(this.pd,this));a.addEventListener("OnMediaError",u(this.Kb,this));a.addEventListener("OnMediaBuffer",u(this.Kb,this));a.addEventListener("OnMediaPlaying",
u(this.rd,this))};o.sc=function(a){if(a.data&&a.data.title)this.ha=a.data;if(a.data&&a.data.guid)this.Ta=a.data.guid};o.wd=function(a){s(a.data.clips,function(a){if(a=a.baseClip.guid)return this.Ta=a,j});if(this.Ta&&a.data.release&&a.data.release.title)this.ha=a.data.release};o.qd=function(){this.ja="s2"};o.sd=function(a){this.ja="s2";a=a.data.baseClip;a.isAd?(this.wa="ad",this.qa=a.isMid?"a2":"a1"):(this.wa=M,this.qa="")};o.Kb=function(){if(this.ja!=O)this.ja="s3"};o.pd=function(){this.ja="s4"};
o.rd=function(a){this.Sc=a.currentTime};o.O=function(){return this.ha!=h};o.J=function(){return this.ha.title};o.M=function(){return!this.Ta?"":this.Ta};o.U=l("wa");o.P=l("qa");o.ca=function(){return this.ha.duration};o.H=l("ja");o.X=l("Sc");o.T=function(){return this.ha.bitrate};o.ba=function(){return this.ha&&this.ha.defaultThumbnailUrl?this.ha.defaultThumbnailUrl:this.ha.pid?"http://link.theplatform.com/s/ngc/"+this.ha.pid+"?format=poster&height=70&width=95":""};o.Z=k();o.S=k();
o.da=function(){return isNaN(this.q)?0:this.q===d?0:t()-this.q};o.$=function(){var a=this.ha.keywords?this.ha.keywords.split(","):[],b=[];s(this.ha.categories?this.ha.categories:[],function(a){b.push(encodeURIComponent(a.name))});s(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};o.Q=k();o.aa=n("TP");Y.prototype.initialize=Y.prototype.dd;Y.prototype.getStrategyName=Y.prototype.aa;Y.prototype.isReady=Y.prototype.O;Y.prototype.getTitle=Y.prototype.J;Y.prototype.getVideoPath=Y.prototype.M;
Y.prototype.getContentType=Y.prototype.U;Y.prototype.getAdPosition=Y.prototype.P;Y.prototype.getTotalDuration=Y.prototype.ca;Y.prototype.getState=Y.prototype.H;Y.prototype.getCurrentPlayTime=Y.prototype.X;Y.prototype.getBitrate=Y.prototype.T;Y.prototype.getThumbnailPath=Y.prototype.ba;Y.prototype.getPlayerType=Y.prototype.Z;Y.prototype.getAutoplayType=Y.prototype.S;Y.prototype.getViewStartTime=Y.prototype.da;Y.prototype.getSections=Y.prototype.$;Y.prototype.getAuthors=Y.prototype.Q;
Y.verify=function(a){return typeof a.controller!=="undefined"};function tc(a,b){this.a=a;this.Cc=b;this.Ga=window.location!=window.parent.location;this.wc=j;this.Kd=t();this.Bc="_v_";this.sa={};I.call(this)}fa(tc,I);var uc=q.QUICK_TEST?1E4:6E4,vc="autoDetect",wc={Sd:"title",Td:"videopath",Rd:"thumbnailpath"},xc={};o=tc.prototype;
o.N=function(){this.Hb=(this.La=this.G.F("_chartbeat3"))?0:1;this.ac=this.Rb=g;this.Ab=j;this.pb=this.Ob=this.gc=this.Ca=d;this.Qa=15E3;this.cb=d;this.Ed=this.Xb=this.Yb=this.eb=this.fb=0;var a=q.location;this.Pb=j;if(!this.La||this.La.length===0)this.La=ja(Eb(this),3);this.G.create("_chartbeat3",this.La,2592E3);var b;(b=this.Cc)&&pa(b)?(this.ea=new b(this.a),b=g):b=j;if(b){D(this.k,"pingServer","ping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);D(this.k,"path",xb(!!this.k.useCanonical));
this.ea.getPlayerType&&D(this.k,"video_type",this.ea.getPlayerType());this.gc=setInterval(u(this.Pc,this),1E3);if(this.Ga===g)this.kb=u(this.ad,this),w(window,"message",this.kb),this.cb=setInterval(this.Fd,1E3);tc.ma.N.call(this)}};o.xb=k();
o.ka=function(){if(this.ea){if(!yc(this))this.ac=g;if(!this.ac)return t()-this.Ba>=this.jb&&clearInterval(this.Ca),tc.ma.ka.call(this);if(this.ea.isReady())this.Ab=this.ac=j,this.Ob=zc(this),Ac(this),this.Ca=setInterval(u(this.zb,this),100),tc.ma.ka.call(this);else if(!this.Ab){this.Ab=g;if(this.Ed++>150)throw"Error: Video strategy never reported its ready state";clearInterval(this.Ia);this.Ia=setInterval(u(this.ka,this),100)}}};
o.Ma=function(){if(this.ea){var a=this.k,b=this.ea,c=b.getState(),e=yc(this),f=this.Ga?[]:q._cbq||(q._cbq=[]),i=b.getViewStartTime(),p=Bc(this),B=b.getAutoplayType?b.getAutoplayType():d,i=i===-1?-1:i/1E3,p=p?encodeURIComponent(p):d;if(!xc.path||xc.path===e||c==="s2"&&xc.state!=="s2")switch(xc={path:e,state:c},f.push(["_vi",sa(Cc(this))]),f.push(["_vp",e]),f.push(["_vdd",encodeURIComponent("video@"+(a.videodomain||a.domain))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),
b.getAdPosition&&f.push(["_vap",b.getAdPosition()]),f.push(["_vtn",sa(Bc(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case O:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=Dc(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",i)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",p)+Z("_vaup",B||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.Xb)+Z("c",Math.round(va(this.Kd)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.Yb+"&j="+(this.Qa/1E3+15)+Ec(this)+"&tz="+(new Date).getTimezoneOffset()+(wb(this.G)?"&l=1":"")+"&_";this.Ga===g&&s(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.Za(a)}};function Z(a,b){return b!==d&&b!==""?"&"+a+"="+b:""}o.Xa=function(){this.G.update("_cb_cp",this.za,3600,j,",")};function Ec(a){var b=a.G.F("_cb_cp");a.G.remove("_cb_cp");return b?"&D="+b:""}
function Fc(a){return a.k.subdomain?a.k.subdomain:ma(q.location.hostname)}function yc(a){var b=a.sa.videopath;if(b)return b;if(a.k.videoPathHash){if(a=Cc(a))return ja(a)}else return a.ea.getVideoPath();return""}function Cc(a){return a.sa.title||a.ea.getTitle()}function Bc(a){return a.sa.thumbnailpath||a.ea.getThumbnailPath()}
function Dc(a){var b=a.k,c=a.ea,e=q.location,f=c.getUid&&c.getUid()||b.uid,i=b.videodomain||c.getHost&&c.getHost()||b.domain,i=encodeURIComponent("video@"+i),p="",B=a.Ya?"&b="+a.Ya:"",m,C=a.k.path;m=a.k.useSubDomains!==j&&C&&C.substr(0,1)==="/"?Fc(a)+C:C;var C=c.getSections&&c.getSections(),L=c.getAuthors&&c.getAuthors(),P=b.sections?"&g0="+encodeURIComponent(b.sections):"",S=b.authors?"&g1="+encodeURIComponent(b.authors):"",C=C===d||b.videoPageGroups?P:"&g0="+C.join(","),L=L===d||b.videoPageGroups?
S:"&g1="+L.join(","),S="",P=yc(a);if(a.pb===d)a.pb=P;else if(P!=a.pb)S=Z("D",a.za),a.za=ja(Eb(a)),a.pb=P,a.fb=0,a.eb=0,a.Yb=0,a.Xb=0,a.Rb=g;if(a.Rb||S){if(a.Ga===j||a.Ga===g&&a.wc===g)a.Rb=j;p=(Jb(a)?"&v=":"&r=")+Kb(a)}a.Yb+=a.fb;a.fb=0;a.Xb+=a.eb;a.eb=0;Ac(a);var ea=P="",aa="",N="",E="",ra="",ha="",ia="";if(!a.Ga===g||a.Pb===g)P="&_vi="+Lb(a),ea="&_vp="+encodeURIComponent(m),aa="&_vh="+sa(Fc(a)),N="&_vdd="+encodeURIComponent(b.domain),a.Pb===g?(E=b.u,ra=b.t,ha=Ka(b.v),ia=Ka(b.r)):(E=J("u"),ra=J("t"),
ha=Ka(J("v")),ia=Ka(J("r")));m="";m=x(ha)?"&_pv="+ha:x(ia)?"&_pr="+ia:"&_pr=NA";ha="&_pu=";ia="&_pt=";ha+=E?E:"NA";ia+=ra?ra:"NA";E=!b.noCookies&&a.G.isSupported();ra=c.getStrategyName?c.getStrategyName():"";return(e.protocol||"http:")+"//"+b.pingServer+"/ping?h="+i+"&g="+f+"&p="+sa(yc(a))+"&i="+Cc(a)+C+L+"&u="+a.La+"&t="+a.za+"&x=0&y=0&V=68"+Z("VS",ra)+(E?"&n="+a.Hb:"&nc=1")+B+p+S+Z("_vd",c.getTotalDuration())+P+ea+aa+ha+ia+m+N}o.zb=function(){var a=zc(this);if(this.Ob!=a)this.Ob=a,Ac(this),this.ka()};
function Ac(a){var b=a.Qa;a.Qa=Gc(a)===g?5E3:a.ea.getState()===O?uc:15E3;if(b!=a.Qa)b=a.Qa,clearInterval(a.Ia),a.Ia=setInterval(u(a.ka,a),b)}function zc(a){return a.ea.getState()+a.ea.getAdPosition()}function Gc(a){return a.ea.getState()==="s2"||a.ea.getAdPosition()!==""&&a.ea.getViewAdPlayTime!==-1}o.Pc=function(){Gc(this)===g&&(this.fb+=1,this.ea.getContentType()===M&&(this.eb+=1))};o.Fd=function(){window.parent.postMessage("cbdata?","*")};
o.ad=function(a){if(a.source===window.parent&&(a=a.data,x(a)&&a.indexOf("domain=")===0)){this.Pb=g;var b={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g,u:g,t:g,v:g,r:g},c=this;s(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});na(window,"message",this.kb);clearInterval(this.cb);this.cb=d;this.wc=g;this.ka()}};o.setProperty=function(a,b){var c=j,e=this;s(wc,function(f){if(a.toLowerCase()==f)return e.sa[f]=b,c=g,j});return c};
o.terminate=function(){clearInterval(this.gc);clearInterval(this.cb);clearInterval(this.Ca);na(window,"message",this.kb);tc.ma.terminate.call(this)};o.xa=function(){tc.ma.xa.call(this);this.Cc=this.a=this.kb=h};function $(a){this.a=a;this.D=g;this.B=j;this.q=t();this.Ca=this.ua=this.ya=d;this.Ec=q._sf_async_config.ytApikey;this.Pa=d;Hc(this,Ic(this));this.ia()}o=$.prototype;o.ia=function(){this.Ca=setInterval(r(this.zb,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.ga()};o.zb=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ca),this.Ca=d,this.ga()};o.la=function(){this.D=g};o.ga=function(){if(!this.B)this.B=g};
function Ic(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}function Hc(a,b){var c="https://www.googleapis.com/youtube/v3/videos?part=snippet&id="+b+"&key="+a.Ec,e=u(function(){this.Pa={id:b,title:""}},a);if(a.Ec){var f=u(function(a){if(b==Ic(this))a?a.error?e():this.Pa={id:b,title:a&&a.items&&a.items[0]&&a.items[0].snippet&&a.items[0].snippet.title||""}:e()},a);wa(c,f)}else e()}o.O=function(){return this.D&&!!this.Pa};
o.J=function(){return this.Pa&&this.Pa.id===Ic(this)?this.Pa.title:""};o.M=function(){return Ic(this)||this.a.getVideoUrl()};o.U=function(){return M};o.P=n("");o.ca=function(){var a=this.a.getDuration();return oa(a)?a*1E3:a};o.H=function(){if(!this.B)return O;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};o.X=function(){return this.a.getCurrentTime()};o.T=n(-1);o.ba=function(){return"http://img.youtube.com/vi/"+Ic(this)+"/default.jpg"};o.Z=k();o.S=k();
o.da=function(){return isNaN(this.q)?0:va(this.q)};o.$=l("ya");o.Q=l("ua");o.aa=n("YT");$.prototype.getStrategyName=$.prototype.aa;$.prototype.isReady=$.prototype.O;$.prototype.getTitle=$.prototype.J;$.prototype.getVideoPath=$.prototype.M;$.prototype.getContentType=$.prototype.U;$.prototype.getAdPosition=$.prototype.P;$.prototype.getTotalDuration=$.prototype.ca;$.prototype.getState=$.prototype.H;$.prototype.getCurrentPlayTime=$.prototype.X;$.prototype.getBitrate=$.prototype.T;
$.prototype.getThumbnailPath=$.prototype.ba;$.prototype.getPlayerType=$.prototype.Z;$.prototype.getAutoplayType=$.prototype.S;$.prototype.getViewStartTime=$.prototype.da;$.prototype.getSections=$.prototype.$;$.prototype.getAuthors=$.prototype.Q;$.verify=function(a){return pa(a.getDuration)&&pa(a.getVideoUrl)&&pa(a.getVideoEmbedCode)};function Jc(){q._cbv_strategies||(q._cbv_strategies=[]);q._cbv_strategies.push(X);q._cbv_strategies.push(U);q._cbv_strategies.push(T);q._cbv_strategies.push($);q._cbv_strategies.push(V);q._cbv_strategies.push(R);q._cbv_strategies.push(Q);q._cbv_strategies.push(W);q._cbv_strategies.push(Y);this.Zb=[];this.sa=[];this.k=q._sf_async_config||{};qb("_cbv",u(this.bd,this));this.k[vc]!==j&&Kc()}
Jc.prototype.bd=function(a){if(ba(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){Lc();return}else if(b==="removePlayer"){Mc(this,a[1]);return}else if(b==="setProps"){Nc(a[1])||this.sa.push(a[1]);return}}Oc(this,a)};function Oc(a,b){var c=j,e=q._cbv_strategies;v(window.jwplayer)&&(b=pa(b)?b():b);s(e,function(a){if(a.verify(b)===g)return c=a,j});c===j||Pc(a,b,c)}
function Mc(a,b){var c=a.Zb,e=q.pSUPERFLY_video,f=ta(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=ta(e,function(a){return a.a===b});f!==-1&&e.splice(f,1)[0].xa()}function Nc(a){if(!v(a))return j;var b=a.player,c=ua(function(a){return a.a===b});return!v(c)?j:Qc(c,a)}function Qc(a,b){var c=j;s(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}
function Pc(a,b,c){var e=j;s(a.Zb,function(a){if(b===a)return e=g,j});if(!e){c=new tc(b,c);q.pSUPERFLY_video.push(c);for(var f=a.sa.length-1;f>-1;f--)Qc(c,a.sa[f])&&a.sa.splice(f,1);Hb(c);a.Zb.push(b)}}
function Kc(){if(pa(window.jwplayer)&&v(window.jwplayer()))for(var a=0,b=window.jwplayer(a);v(b.id);)window._cbv.push(b),b=window.jwplayer(++a);else window.flowplayer?window._cbv.push(window.flowplayer):window.brightcove&&window.experienceJSON?window._cbv.push(window.brightcove):window.videojs?(a=window.videojs.plugin,pa(a)&&a("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)})):window.kWidget?window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))}):
window.$pdk?window._cbv.push(window.$pdk):s(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})}function Lc(){function a(){function a(b){q._cbv.push(b.target)}var b=q.YT.Player;s(document.getElementsByTagName("iframe"),function(f){var i=f.src,p=i&&i.indexOf("www.youtube.com/embed/");i&&p>=0&&p<9&&new b(f,{events:{onReady:a}})})}if(q.YT&&q.YT.Player)a();else{var b=q.onYouTubeIframeAPIReady;q.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(q,arguments)}catch(c){}a()}}}};if(window.location==window.parent.location&&!q.pSUPERFLY){var Rc=new kc,Sc={};q.pSUPERFLY=Sc;var Tc=!!cc;Sc.virtualPage=function(a,b){if(!ab){var c=q._sf_async_config;c.virtualReferrer=q.location.protocol+"//"+c.domain+c.path;c.path=zb(a);b&&(c.title=b);Rc.gb();Tc&&cc.evps();Rc.Ac();Tc&&cc.svps()}};Sc.activity=u(Rc.Ic,Rc);Hb(Rc);var Uc=G.Y(g);if(Uc)if(Uc.getItem("_cb_ip")){var Vc=q.location;(!/^(.+[.])?chartbeat\.com$/.test(Vc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Vc.pathname))||ic()}else w(q,
"message",jc)}q.pSUPERFLY_video||(q.pSUPERFLY_video=[]);new Jc;})();
