gigya._.apiAdapters.web.callback({
  "threadCount": 3,
  "settings": {
    "useSiteLogin": false,
    "shareToSNCheckboxChecked": false,
    "enableFBComments": false,
    "mode": "comments",
    "newCommentPosition": "top",
    "disableRSS": false,
    "disableCommentsCount": false,
    "repliesCollapsed": false,
    "displayPosNegVotes": false,
    "refreshMode": "off",
    "refreshInterval": 0,
    "maxCommentLength": 5000,
    "enableRichTextEditing": false,
    "enableUserTagging": false,
    "enableUserSorting": false,
    "requireGuestName": true,
    "enableMediaItems": false,
    "enableDirectCommentLinking": false,
    "enableLinks": false,
    "readOnly": false,
    "threadingDepth": 5,
    "sortBy": "dateDesc",
    "allowNegativeVoting": true,
    "allowGuest": false,
    "pageSize": 25,
    "enableCommentTitles": "disabled",
    "enableCommentBody": "enabled_mandatory",
    "allowCommentDeletion": false,
    "isGuestEmailRequired": false,
    "enableFlagging": true,
    "enableRatings": "disabled",
    "flaggingEmailAfter": 0,
    "flaggingPendingAfter": 0,
    "moderationState": 1,
    "moderationModes": {
      "text": "pre",
      "image": "pre",
      "video": "pre",
      "url": "pre",
      "other": "pre"
    },
    "enableVoting": true,
    "allowMultipleReviewsPerUser": false,
    "allowAnonymous": false,
    "ratingDims": [],
    "highlightGroupsSettings": [
      {
        "name": "Moderators",
        "type": "moderator",
        "enabled": true,
        "showBadge": false,
        "badgeText": "Moderator",
        "badgeColor": "#00AEEF",
        "badgeFrame": "rectangle",
        "commenterNameColor": "#00AEEF"
      },
      {
        "name": "Experts",
        "type": "user",
        "enabled": false,
        "showBadge": true,
        "badgeText": "Expert",
        "badgeColor": "#828282",
        "badgeFrame": "rectangle",
        "commenterNameColor": "#000000"
      },
      {
        "name": "Journalists",
        "type": "user",
        "enabled": false,
        "showBadge": true,
        "badgeText": "Journalist",
        "badgeColor": "#7A3CC6",
        "badgeFrame": "rectangle",
        "commenterNameColor": "#000000"
      },
      {
        "name": "Staff",
        "type": "user",
        "enabled": false,
        "showBadge": true,
        "badgeText": "Staff",
        "badgeColor": "#39B54A",
        "badgeFrame": "rectangle",
        "commenterNameColor": "#000000"
      },
      {
        "name": "Pick",
        "type": "comment",
        "enabled": false,
        "showBadge": true,
        "badgeText": "Editor's Pick",
        "badgeColor": "#009CDC",
        "badgeFrame": "none",
        "badgeImageURL": "https://cdns.gigya.com/gs/i/comments2/editors_pick.png",
        "commentBackgroundColor": "#E5F8FF"
      }
    ],
    "userEditComment": false
  },
  "streamInfo": {
    "status": "enabled",
    "streamURL": "http://america.aljazeera.com/articles/2014/7/21/naked-in-a-steamroomthenewfaceofprivacy.html#commentsDiv",
    "streamTitle": "Naked in a steam room: The new face of privacy | Al Jazeera America",
    "streamTags": [],
    "createDate": 1405971552790,
    "commentCount": 4,
    "approvedCommentCount": 4,
    "threadCount": 3,
    "ratingCount": 0,
    "rssURL": "http://comments.us1.gigya.com/comments/rss/6311261/ajam/61c6ec9c-cf5c-4c67-83ad-e70e12e12dc71405908764414",
    "lastCommentTimestamp": 1409403783982,
    "isUserSubscribed": false,
    "moderationMode": "inherit",
    "moderationModes": {
      "text": "inherit",
      "image": "inherit",
      "video": "inherit",
      "url": "inherit",
      "other": "inherit"
    }
  },
  "comments": [
    {
      "ID": "a0977a2e3ec14cbebb563103d74a9c30",
      "streamId": "61c6ec9c-cf5c-4c67-83ad-e70e12e12dc71405908764414",
      "threadID": "",
      "isModerator": false,
      "commentText": "Disruptive, bandwidth hog and resource consuming....(when we record our own conversations for protection.)\r\nImportant for national security and keeping us all safe from terrorists, (when the government is recording our daily lives.)\r\n\r\nIf there is NO difference in the recordings, then the difference must be in the usage it will be put to....................\r\n\r\nIf you are defending, the information is bad.\r\nIf the government is prosecuting you, the information is good.\r\n\r\nThe #1 argument against all of this record keeping on the citizens is that we DO NOT have access tp it to use it in our defence..\r\nIt can only be used in prosecuting us and it can be used out of context and any information contained proving us innocent will be hidden, if not erased.",
      "ratings": {},
      "TotalVotes": 0,
      "posVotes": 0,
      "negVotes": 0,
      "vote": "none",
      "sender": {
        "photoURL": "https://lh6.googleusercontent.com/-c5MYInDfQnA/AAAAAAAAAAI/AAAAAAAAAF4/r1BZdBqwZtc/photo.jpg?sz=50",
        "profileURL": "https://plus.google.com/111674763420428536524",
        "name": "Dean Borchert",
        "isSelf": false,
        "loginProvider": "GooglePlus"
      },
      "flagCount": 0,
      "highlightGroups": [],
      "edited": false,
      "timestamp": 1409403783982,
      "threadTimestamp": 1409403783982,
      "status": "published"
    },
    {
      "ID": "585d6c1ea43240daa6e024013f8b09b0",
      "streamId": "61c6ec9c-cf5c-4c67-83ad-e70e12e12dc71405908764414",
      "threadID": "",
      "isModerator": false,
      "commentText": "Hey! They can watch me all they want! Watch me sleep. poop-eat and drink beer, sitting on my duff in front of the TV 24/7. I hope it's entertaining ",
      "ratings": {},
      "TotalVotes": 0,
      "posVotes": 0,
      "negVotes": 0,
      "vote": "none",
      "sender": {
        "photoURL": "https://graph.facebook.com/100006387610205/picture?type=square",
        "profileURL": "https://www.facebook.com/al.marshall.969",
        "name": "Al Marshall",
        "isSelf": false,
        "loginProvider": "Facebook"
      },
      "providerPostIDs": {
        "facebook": "100006387610205_1534114016811504"
      },
      "flagCount": 0,
      "highlightGroups": [],
      "edited": false,
      "timestamp": 1406482749022,
      "threadTimestamp": 1406482749022,
      "status": "published"
    },
    {
      "ID": "241c74e3271f4a88b127e7da1ce2afa7",
      "streamId": "61c6ec9c-cf5c-4c67-83ad-e70e12e12dc71405908764414",
      "threadID": "",
      "isModerator": false,
      "commentText": "Elevator hacking?? Yes they could! Most may not know this,but, that high speed elevator you ride in every day, many times, is controlled be a Computer System! In all large towers, a master computer controls where elevators park while waiting a call. This changes during the day as rush hours change,and, allows elevator to be closer to where they will be needed. Up traffic in the AM,and, down traffic at night. Imagine if you cold change the instructions? Grid lock!",
      "ratings": {},
      "TotalVotes": 1,
      "posVotes": 1,
      "negVotes": 0,
      "vote": "none",
      "descendantsCount": 1,
      "sender": {
        "photoURL": "http://graph.facebook.com/100002334812324/picture?type=square",
        "profileURL": "https://www.facebook.com/arthur.cook.71",
        "name": "Arthur Cook",
        "isSelf": false,
        "loginProvider": "Facebook"
      },
      "flagCount": 0,
      "replies": [
        {
          "ID": "eff28bd476514d9c86d632097efc18b6",
          "streamId": "61c6ec9c-cf5c-4c67-83ad-e70e12e12dc71405908764414",
          "parentID": "241c74e3271f4a88b127e7da1ce2afa7",
          "threadID": "241c74e3271f4a88b127e7da1ce2afa7",
          "isModerator": false,
          "commentText": "Theoretically, such systems shouldn't be on an open (i.e. connected to the internet) network in the first case. So, any well designed system should be fairly insulated from all but the most targeted attacks (such as the one that took out the Iranian nuclear silos by hopping through USBs to get around the fact the facility wasn't connected to the internet).\r\n\r\nThat said though, one of the ironclad rules of security is that if it hasn't been audited for security, the design is almost assuredly insecure.",
          "ratings": {},
          "TotalVotes": 0,
          "posVotes": 0,
          "negVotes": 0,
          "vote": "none",
          "sender": {
            "photoURL": "http://graph.facebook.com/605062731/picture?type=square",
            "profileURL": "https://www.facebook.com/legoremix",
            "name": "Oreoluwatomiwa Babarinsa",
            "isSelf": false,
            "loginProvider": "Facebook"
          },
          "flagCount": 0,
          "highlightGroups": [],
          "edited": false,
          "timestamp": 1406049778253,
          "threadTimestamp": 0,
          "status": "published"
        }
      ],
      "highlightGroups": [],
      "edited": false,
      "timestamp": 1405971552790,
      "threadTimestamp": 1405971552790,
      "status": "published"
    }
  ],
  "commentCount": 4,
  "next": "ts_1405971552790",
  "nextTS": 1405971552790,
  "hasMore": false,
  "statusCode": 200,
  "errorCode": 0,
  "statusReason": "OK",
  "callId": "aa87e865d8034ff98da9d8211e788303",
  "time": "2015-10-28T10:51:16.695Z",
  "context": "R2405658138"
});