var $$FSR = {
   'timestamp': 'July 11, 2012 @ 2:26 PM',
   'version': '12.3.1',
   'enabled': true,
   'sessionreplay': true,
   'auto' : true,
   'encode' : false,
   'files': 'http://beta.images.theglobeandmail.com/static/foresee/',
   'js_files': 'http://beta.images.theglobeandmail.com/static/foresee/',
   'image_files': 'http://beta.images.theglobeandmail.com/static/foresee/',
   'html_files': 'http://www.theglobeandmail.com/static/foresee/',
   'css_files': 'http://beta.images.theglobeandmail.com/static/foresee/',
   //'swf_files': '__swf_files_' needs to be sef when foresee-transport.swf is not located at 'files'
   'id': 'fNsw9GYZ5R+VYkr5Mz00fg==',
   'definition': 'foresee-surveydef.js',
   'embedded': false,
   'replay_id': 'theglobeandmail.com',
   'renderer':'W3C',	// or "ASRECORDED"
   'layout':'CENTERFIXED',	// or "LEFTFIXED" or "LEFTSTRETCH" or "CENTERSTRETCH"
   'sites': [
      {
         path: /\w+-?\w+\.(com|ca|org|edu|gov|net|co\.uk)/
      },
      {
         path: '.',
         domain: 'default'
      }
   ],
   storageOption: 'cookie'
};
// -------------------------------- DO NOT MODIFY ANYTHING BELOW THIS LINE ---------------------------------------------
if (typeof(FSR) == "undefined") {
(function(config){var k=void 0,s=!0,u=null,x=!1;function K(){return function(){}}
(function(O){function $(a,c){g.controller.execute(g.controller.mb,b._sd(),{sp:a,when:c,qualifier:k,invite:x})}function ka(a,c,b){setTimeout(function(){a.Xc(c,b)},1)}function L(a,c){return(c?a.get(c):a)||""}function V(a){return[a||f.f.j(),(a||f.f.j()).get("cp")||{}]}function la(a,c){if(""===a&&c)return c;var d=a.split(" "),e=b.shift(d),h;if("#"==e.charAt(0)){var f=b.Ic(e.substring(1));h=f?[f]:[]}else{h="."!==e.charAt(0)?e.split(".")[0]:"*";var g=e.split("."),q=u;-1!=b.u("[",h)&&(q=h,h=h.substr(0,b.u("[",
h)));for(var f=function(a){var c=arguments.callee,d;if(!(d=!c.bd)){d=c.Nc;if(a.className.length==0)d=x;else{for(var e=a.className.split(" "),h=d.length,f=0;f<d.length;f++)b.Ob(d[f],e)&&h--;d=h==0}}if(d&&!(d=!c.ad)){c=c.attributes;d=s;e=function(a){var c="";b.n(["!","*","~","$","^"],function(d,e){if(b.u(e,a)!=-1){c=e;return x}});return c};for(h=0;h<c.length;h++){var z=c[h].split("="),f=b.shift(z),z=z.length>2?z.join("="):z[0],g=e(f)+"=",C=function(a,c){var b=a.match(c);return b&&b.length>0},f=g!="="?
f.substring(0,f.length-1):f,f=a.getAttribute(f);switch(g){case "=":d=d&f===z;break;case "!=":d=d&f!==z;break;case "*=":d=d&C(f,z);break;case "~=":d=d&C(f,RegExp("\\b"+z+"\\b","g"));break;case "^=":d=d&C(f,RegExp("^"+z));break;case "$=":d=d&C(f,RegExp(z+"$"));break;default:d=x}}}if(d)return a},n=[],i=0;i<c.length;i++)for(var y=c[i].getElementsByTagName(h),l=0;l<y.length;l++)n.push(y[l]);g&&b.shift(g);h=[];f.Nc=g;if(q!=u)var j=b.u("[",q),j=q.substring(j+1,q.lastIndexOf("]")).split("][");f.attributes=
q!=u?j:u;f.bd=-1!=b.u(".",e)&&0<g.length;f.ad=q!=u;for(e=0;e<n.length;e++)f(n[e])&&h.push(n[e])}return la(d.join(" "),h)}function ta(a){return a instanceof Date?isFinite(this.valueOf())?this.getUTCFullYear()+"-"+N(this.getUTCMonth()+1)+"-"+N(this.getUTCDate())+"T"+N(this.getUTCHours())+":"+N(this.getUTCMinutes())+":"+N(this.getUTCSeconds())+"Z":u:a.valueOf()}function X(a,c){var b,e,h,f,g=A,q,n=c[a];n&&("object"===typeof n&&(n instanceof Date||n instanceof Date||n instanceof Boolean||n instanceof String||
n instanceof Number))&&(n=ta(n));"function"===typeof M&&(n=M.call(c,a,n));switch(typeof n){case "string":return aa(n);case "number":return isFinite(n)?String(n):"null";case "boolean":case "null":return String(n);case "object":if(!n)return"null";A+=R;q=[];if("[object Array]"===Object.prototype.toString.apply(n)){f=n.length;for(b=0;b<f;b+=1)q[b]=X(b,n)||"null";h=0===q.length?"[]":A?"[\n"+A+q.join(",\n"+A)+"\n"+g+"]":"["+q.join(",")+"]";A=g;return h}if(M&&"object"===typeof M){f=M.length;for(b=0;b<f;b+=
1)"string"===typeof M[b]&&(e=M[b],(h=X(e,n))&&q.push(aa(e)+(A?": ":":")+h))}else for(e in n)Object.prototype.hasOwnProperty.call(n,e)&&(h=X(e,n))&&q.push(aa(e)+(A?": ":":")+h);h=0===q.length?"{}":A?"{\n"+A+q.join(",\n"+A)+"\n"+g+"}":"{"+q.join(",")+"}";A=g;return h}}function aa(a){ba.lastIndex=0;return ba.test(a)?'"'+a.replace(ba,function(a){var b=ma[a]||ma[a.charCodeAt(0)];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function N(a){return 10>a?
"0"+a:a}function b(a){g=b.A(g,a)}var g={},l={},i=i=this,B=i.document;b.X=!i.opera&&!!B.attachEvent;b.zb=864E5;var S=Object.prototype.hasOwnProperty,ca=Object.prototype.toString,T=[],Y=x,w=x,Q;b.q=function(a){return u!==a&&k!==a};b.D=function(a){return"[object Function]"===ca.call(a)};b.C=function(a){return"[object Array]"===ca.call(a)};b.M=function(a){return"string"===typeof a};b.Tb=function(a){return"number"===typeof a};b.Xd=function(a){var c=a.getAttribute("id");c&&!b.M(c)&&(c=a.attributes.id.value);
return c};b.Y=function(a){if(!a||("[object Object]"!==ca.call(a)||a.nodeType||a.setInterval)||a.constructor&&!S.call(a,"constructor")&&!S.call(a.constructor.prototype,"isPrototypeOf"))return x;for(var c in a);return c===k||S.call(a,c)||!S.call(a,c)&&S.call(Object.prototype,c)};b.A=function(){var a=arguments[0]||{},c=1,d=arguments.length,e,h,f;"object"!==typeof a&&!b.D(a)&&(a={});d===c&&(a=this,--c);for(;c<d;c++)if((e=arguments[c])!=u)for(h in e)f=e[h],a!==f&&f!==k&&(a[h]=f);return a};b.wb=function(a){var c;
if(b.Y(a)){c={};for(var d in a)c[d]=b.wb(a[d])}else if(b.C(a)){c=[];d=0;for(var e=a.length;d<e;d++)c[d]=b.wb(a[d])}else c=a;return c};b.ta=function(){for(var a={},c=0,d=arguments.length;c<d;c++){var e=arguments[c];if(b.Y(e))for(var h in e){var f=e[h],g=a[h];a[h]=g&&b.Y(f)&&b.Y(g)?b.ta(g,f):b.wb(f)}}return a};b.ua=K();b.now=function(){return+new Date};b.u=function(a,c){if(b.C(c)||b.Y(c)){for(var d in c)if(c[d]===a)return d;return-1}return String(c).indexOf(a)};b.Ob=function(a,c){return-1!=b.u(a,c)};
b.n=function(a,c){var d,e=0,h=a.length;if(h===k||b.D(a))for(d in a){if(c.call(a[d],d,a[d])===x)break}else for(d=a[0];e<h&&c.call(d,e,d)!==x;d=a[++e]);return a};b.Ic=function(a){return B.getElementById(a)};b.trim=function(a){return a.toString().replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};b.Rc=function(a){return a.toString().replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1")};b.shift=function(a){return a.splice(0,1)[0]};b.$a=function(a,c,d){for(var e=a.split("."),c=c[b.shift(e)],h=d,f;c!=u&&0<e.length;)c=
c[b.shift(e)];if(c){e=a.split(".");for(f;e.length&&(f=b.shift(e));)h=h[f]?h[f]:h[f]={};e=a.split(".");h=d;for(f;e.length&&(f=b.shift(e));)0<e.length?h=h[f]:h[f]=c}};b.R=function(){return B.location.href};b.Ha=function(){return B.referrer};b.Ga=function(){return B.location.protocol};b.Ia=function(a){return encodeURIComponent(a)};b.P=function(a){return decodeURIComponent(a)};b.Fa=this;b.ka=function(a,c){var d=i.document.readyState,c=c||1;if(b.D(a)){var e=b.Fa,h=a,f=c,a=function(){setTimeout(function(){h.call(e)},
f)};if(d&&("complete"==d||"loaded"==d)){Y=s;for(T.push(a);d=b.shift(T);)d&&d.call(b.Fa);return}}if(!Y&&b.D(a))T.push(a);else if(Y&&b.D(a))a.call(b.Fa);else if(!b.D(a))for(Y=s;0<T.length;)(d=b.shift(T))&&d.call(b.Fa)};b.Xa=u;b.ka(function(){b.Xa=B.getElementsByTagName("head")[0]||B.documentElement});b.Pa=function(a,c,d){var d=d||b.ua,e=B.createElement(c);if(!(c="script"===c))e.rel="stylesheet";e.type=c?"text/javascript":"text/css";c&&(b.X?e.onreadystatechange=function(){("loaded"==this.readyState||
"complete"==this.readyState)&&d("ok")}:e.onload=function(){d("ok")},e.onerror=function(){d("error")});e[c?"src":"href"]=0==b.u("//",a)?b.Ga()+a:a;c?b.Xa.appendChild(e):c||(b.hb[e.href]?e=b.hb[e.href]:(b.hb[e.href]=e,b.Xa.appendChild(e)));if(!c){var h,f;"sheet"in e?(h="sheet",f="cssRules"):(h="styleSheet",f="rules");var g=setInterval(function(){try{if(e[h]&&e[h][f].length){clearInterval(g);clearTimeout(q);d(s,e)}}catch(a){}finally{}},10),q=setTimeout(function(){clearInterval(g);clearTimeout(q);d(x,
e)},2500)}};b.Zd=function(a){var c=b.now(),d;do d=b.now();while(d-c<a)};B.addEventListener?Q=function(){B.removeEventListener("DOMContentLoaded",Q,x);b.ka(u)}:b.X&&(Q=function(){"complete"===B.readyState&&(B.detachEvent("onreadystatechange",Q),b.ka(u))});w||(w=s,B.addEventListener?(B.addEventListener("DOMContentLoaded",Q,x),O.addEventListener("load",b.ka,x)):b.X&&(B.attachEvent("onreadystatechange",Q),O.attachEvent("onload",b.ka)));b.hb={};b.startTime=b.now();i.FSR=b;i.FSR.opts=g;i.FSR.prop=l;b.f=
{};b.f.Bc={};var r=b.f.Bc;b.f.vc={};var m=b.f.vc,v;v||(v={});var da=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200b-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,ba=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200b-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,A,R,ma={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\",8203:""},M;"function"!==typeof v.stringify&&(v.stringify=function(a,c,b){var e;R=A="";if(typeof b==="number")for(e=
0;e<b;e=e+1)R=R+" ";else typeof b==="string"&&(R=b);if((M=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return X("",{"":a})});"function"!==typeof v.parse&&(v.parse=function(a,c){function b(a,e){var f,g,n=a[e];if(n&&typeof n==="object")for(f in n)if(Object.prototype.hasOwnProperty.call(n,f)){g=b(n,f);g!==k?n[f]=g:delete n[f]}return c.call(a,e,n)}var e,a=String(a);da.lastIndex=0;da.test(a)&&(a=a.replace(da,function(a){return"\\u"+("0000"+
a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){e=(new Function("return "+a))();return typeof c==="function"?b({"":e},""):e}throw new SyntaxError("JSON.parse");});b.f.JSON=v;b.f.g={};var f=b.f.g,ea=1,fa=9,ga=Array.prototype.slice;m.Ac=function(a,c){c=c||B;if(a.nodeType&&a.nodeType===fa){a=B.body;if(a===u)return[B]}if(a.nodeType&&
a.nodeType===ea)return[a];if(a.aa&&b.M(a.aa))return ga.call(a,0);c&&(c=m.m.Cb(c));if(b.C(a))return a;if(b.M(a)){for(var d=[],e=0;e<c.length;e++)d=d.concat(la(a,[c[e]]));return d}return u};r.F={};r.F.G=function(){this.za=[];this.Qc=x};r.F.G.prototype.Gd=function(a){this.za[this.za.length]={cd:x,Kc:a}};r.F.G.prototype.J=function(){this.Qc=s;for(var a=0;a<this.za.length;a++){var c=this.za[a];c.Kc.apply(this,arguments);if(c.cd){this.za.splice(a,1);a--}}};r.Nb=function(){for(var a=i.navigator.userAgent.replace(/[\s\\\/\.\(\);:]/gim,
""),c="",d=b.now()+"",e=0;e<a.length-1;e=e+a.length/7)c=c+Number(a.charCodeAt(Math.round(e))%16).toString(16);c.length>7&&(c=c.substr(c.length-7));return c+"-"+a.length+d.substr(d.length-6)+"-xxxx-xxxx-xxxxx".replace(/[xy]/g,function(a){var c=Math.random()*16|0;return(a=="x"?c:c&3|8).toString(16)})};b.f.Ab={};var o=b.f.Ab;o.qa=[];o.Ud=function(a,c,d){if(a.SR&&a.SR.updatedAt)for(var e=0;e<o.qa.length;e++){var h=o.qa[e];if(h.Xb.SR&&h.Xb.SR.updatedAt==a.SR.updatedAt){if(b.now()-h.Nd<1500)return h.Fd;
o.qa.splice(e,1);break}}c=b.f.JSON.stringify(a,c,d);o.qa[o.qa.length]={Xb:a,Fd:c,Nd:b.now()};return c};m.m=function(a,c){return new m.m.prototype.Na(a,c)};var ha=O.document,na=Array.prototype.push,ga=Array.prototype.slice,ea=1,fa=9;m.m.ta=function(a,c){var d=a.length,e=0;if(b.Tb(c.length))for(var h=c.length;e<h;e++)a[d++]=c[e];else for(;c[e]!==k;)a[d++]=c[e++];a.length=d;return a};m.m.$d=function(a,c){var d=c||[];a!=u&&(a.length==u||b.M(a)||b.D(a)||!b.D(a)&&a.setInterval?na.call(d,a):m.m.ta(d,a));
return d};m.m.Ec=function(a,c){var b={};b[a]=c;return b};m.m.Dc=function(a){a=b.trim(a).toLowerCase();return b.u("<option",a)==0?"SELECT":b.u("<li",a)==0?"UL":b.u("<tr",a)==0?"TBODY":b.u("<td",a)==0?"TR":"DIV"};m.m.Cb=function(a){a.setInterval||a.nodeType&&(a.nodeType===ea||a.nodeType===fa)?a=[a]:b.M(a)?a=m.m(a).tb():a.aa&&b.M(a.aa)&&(a=a.tb());return a};m.m.Yd=function(a,c){var b,e=[],h;b=!!s;for(var f=0,g=a.length;f<g;f++){h=!!c(a[f],f);b!==h&&e.push(a[f])}return e};m.m.prototype.Na=function(a,
c){this.ae=a;this.Oc=c;this.length=0;this.aa="_4cCommonDom.Query";if(!a)return this;if(a.setInterval||a.nodeType){this.Oc=this[0]=a;this.length=1}else{var d=[];if(a.aa&&b.M(a.aa))d=a.tb();else if(b.C(a))d=a;else if(b.M(a)&&b.u("<",b.trim(a))==0&&b.u(">",b.trim(a))!=-1){var e=m.m.Dc(a),e=B.createElement(e);e.innerHTML=a;b.X?d.push(e.firstChild):d.push(e.removeChild(e.firstChild))}else{if(b.u(",",a)!=-1){d=a.split(",");for(e=0;e<d.length;e++)d[e]=b.trim(d[e])}else d=[a];for(var e=[],h=0;h<d.length;h++)e=
e.concat(m.Ac(d[h],c));d=e}na.apply(this,d)}return this};m.m.prototype.n=function(a){return b.n(this,a)};m.m.prototype.tb=function(){return ga.call(this,0)};m.m.prototype.constructor=m.m;m.m.prototype.Na.prototype=m.m.prototype;i.FSR._query=function(a,c){return m.m(a,c)};o.k=function(a,c){a||(a=r.Nb());this.La=a.replace(/[- ]/g,"");o.k.L||o.k.eb();this.va=c||{};this.data={};this.Cc=new r.F.G;this.xa=0;this.Ed=4E3};o.k.prototype.set=function(a,c){this.Za();this.L[a]=c;this.ra()};o.k.prototype.get=
function(a){this.Za();return a?this.L[a]:this.L};o.k.prototype.Kb=function(a){this.Za();delete this.L[a];this.ra()};o.k.prototype.ha=function(){this.L={};var a=this.va.duration;this.va.duration=-1;this.ra();a?this.va.duration=a:delete this.va.duration};o.k.prototype.Za=function(){this.xa=0;try{var a=o.k.N(this.La);if(a){this.xa=this.La.length+a.length+2;this.L=b.f.JSON.parse(a)}else{this.L={};this.xa=0}}catch(c){this.xa=0;this.L={}}if(!this.L)this.L={}};o.k.prototype.ra=function(){var a=b.f.JSON.stringify(this.L);
this.La.length+b.Ia(a).length>this.Ed&&this.Cc.J(this);this.xa=o.k.write(this.La,a,this.va)};o.k.N=function(a){return(a=i.document.cookie.match("(?:^|;)\\s*"+b.Rc(a)+"=([^;]*)"))?b.P(a[1]):u};o.k.write=function(a,c,d){var e=!d||!b.q(d.encode)||d.encode?b.Ia(c):c,a=b.Ia(a);b.n(d,function(a,c){if(c!=u){var d;a:switch(a){case "duration":d="="+(new Date(b.now()+c*b.zb)).toGMTString();break a;case "secure":d="";break a;default:d="="+c}e=e+(";"+(a==="duration"?"expires":a)+d)}});i.document.cookie=a+"="+
e;return a.length+e.length+2};o.k.ha=function(a,c){o.k.write(a,"",b.A(c,{duration:-1}))};o.k.eb=function(a){a&&a.apply(o.k)};o.k.isSupported=function(){return s};var oa={};f.Aa=function(a,c){function d(a){this.ya=a()}var e=oa[a];if(e!=u)return e;d.prototype.set=function(a,c){if(b.Y(a))for(var d in a)this.ya.set(d,a[d]);else this.ya.set(a,c)};d.prototype.get=function(a){return this.ya.get(a)};d.prototype.Ja=function(a){this.ya.Kb(a)};d.prototype.Kb=function(){this.ya.ha()};return e=oa[a]=new d(c)};
i.FSR._storage=function(a,c,d){a=b.fe.Ab(a);if(d===k&&b.M(c))return a.get(c);d!==k?a.set(c,d):c!==k&&a.set(c);return a.Wd()};f.I={};f.I.Hd={host:"survey.foreseeresults.com",path:"/survey",url:"/display"};f.I.B={host:"controller.4seeresults.com",path:"/fsrSurvey",url:"/OTCImg",Va:3};f.I.event={host:"events.foreseeresults.com",path:"/rec",url:"/process"};f.I.domain={host:"survey.foreseeresults.com",path:"/survey",url:"/FSRImg",Va:3};f.I.yd={host:"replaycontroller.4seeresults.com",path:"/images",enabled:x};
b.f.Bb={};var t=b.f.Bb;r.r={};r.r.ja=function(){return 0+Math.random()*100};r.r.oa=function(a,c,d){var e="";a&&b.n(a,function(a,f){e=e+((e.length!=0?"&":"")+(c?c+"["+a+"]":a)+"="+(d?f:b.Ia(f)))});return e};r.r.hash=function(a){a=a.split("_");return a[0]*3+1357+""+(a[1]*9+58)};r.r.Yb=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&+]"+a+"=([^&#]*)").exec(b.R());return a==u?x:a[1]};r.r.fa=function(a,c){return a[c]||a.files};f.f={};f.f.W=function(a){return a+(g.site.cookie?
"."+g.site.cookie:"")};f.f.j=function(a,c){var d=f.f.W("fsr.s"),d=f.Aa(d,f.f.Ka(d));return a?b.q(c)?d.set(a,c):d.get(a):d};f.f.Uc=function(a,c){var d=a.name;b.n([a.site,a.section,c,f.f.j("q"),f.f.j("l")],function(a,c){d=d+(c?"-"+c:"")});return d};f.f.Yc=function(a,c){function d(c){if("ok"===c&&b.surveydefs){b.A(l,b.properties);g.na=g.surveydefs=b.surveydefs;a()}}var e=g.definition||"foresee-surveydef.js";c?setTimeout(function(){d("ok")},100):b.Pa(r.r.fa(g.site,"js_files")+e,"script",d)};f.f.log=function(a,
c){if(l.events.enabled){var d=f.f.j(),e=d.get("sd");b.q(e)||(e=d.get("cd"));var e=g.na[e],h=new Date;(new E.K(f.I.event,"logit")).send({cid:g.id,rid:d.get("rid")||"",cat:e.name,sec:e.section||"",type:d.get("q")||"",site:g.site.name||"",lang:d.get("l")||b.$S.locale||"",msg:a,param:c,tms:h.getTime(),tmz:h.getTimezoneOffset()*6E4})}};f.f.Ka=function(a){var c;switch(g.storageOption){case "window":c=function(){var a=arguments.callee;return new o.Rd(a.Wb,a.Mb||{})};break;default:c=function(){var a=arguments.callee;
return new o.k(a.Wb,b.A({path:"/",domain:a.jb.site.domain,secure:a.jb.site.secure,encode:a.jb.encode},a.Mb||{}))}}c.Wb=a;c.jb=g;c.Mb=k;return c};var w=navigator.userAgent,G=[{ma:w,ea:"Chrome",Q:"Chrome"},{ma:navigator.vendor,ea:"Apple",Q:"Safari",xb:"Version"},{fd:O.opera,Q:"Opera"},{ma:w,ea:"Firefox",Q:"Firefox"},{ma:w,ea:"Netscape",Q:"Netscape"},{ma:w,ea:"MSIE",Q:"Explorer",xb:"MSIE"},{ma:w,ea:"Gecko",Q:"Mozilla",xb:"rv"}],ia;t.l={ub:w};t.l.platform=(navigator.platform.match(/mac|win32|linux|iphone|ipad|ipod|blackberry|wince|android/i)||
["other"])[0].toLowerCase();t.l.ub.match(/android/i)&&(t.l.platform="android");t.l.ub.match(/windows phone/i)&&(t.l.platform="winmobile");"other"==t.l.platform&&i.orientation!=k&&(t.l.platform="mobile");v=t.l;a:{for(var H=0;H<G.length;H++){var pa=G[H].ma,ua=G[H].fd;ia=G[H].xb||G[H].Q;if(pa&&-1!=b.u(G[H].ea,pa)||ua){G=G[H].Q;break a}}G="unknown"}v.type=G;v=t.l;var qa="unknown";b.n([w,navigator.appVersion],function(a,c){var d=b.u(ia,c);if(d!=-1){qa=parseFloat(c.substring(d+ia.length+1));return x}});
v.version=qa;var w=t.l,I;try{var F;F=navigator.plugins["Shockwave Flash"]?navigator.plugins["Shockwave Flash"].description:(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version")||"0 r0";F=F.match(/\d+/g);I=parseInt(F[0]||"0."+F[1]||0)}catch(wa){I="0 r0"}w.Sc=I;t.l.name=t.l.type;t.l.kb="Unknown";b.n([["win32","Windows"],["mac","Mac"],["linux","Linux"],["iphone","iOS"],["ipad","iOS"],["ipad","iOS"],["android","Android"],["blackberry","Blackberry"],["winmobile","Windows Phone"]],
function(a,c){if(t.l.platform===c[0])t.l.kb=c[1]});"blackberry"==t.l.platform&&!t.l.ub.match(/applewebkit/i)&&(t.l.platform="other");var va=100,U={};m.m.prototype.bind=function(a,c){return this.n(function(){var b,e=this;b=function(a){c.call(e,a)};if(a=="beforeunload"){if(this.onbeforeunload){var f=this.onbeforeunload,g=this;b=function(a){var b;b=f.call(g,a);c.call(g,a);if(b)return b}}else b=c;this.onbeforeunload=b}else if(a==="mouseenter")this.attachEvent?this.attachEvent("on"+a,b):this.addEventListener("mouseover",
m.yc.Sd(c),x);else if(a==="mouseleave")this.attachEvent?this.attachEvent("on"+a,b):this.addEventListener("mouseout",m.yc.Td(c),x);else{U[va++]={dd:c,Fc:b};this.attachEvent?this.attachEvent("on"+a,b):this.addEventListener(a,b,x)}})};m.m.prototype.Wa=function(a,c){this.n(function(){var b,e=u,f;for(f in U)if(U[f].dd===c){b=U[f].Fc;e=f;break}if(e!=u){this.detachEvent?this.detachEvent("on"+a,b):this.removeEventListener(a,b,x);delete U[e]}})};m.m.prototype.Ba=function(a){!a||this.n(function(){if(this.className&&
this.className.length!=0){var c=this.className.split(" ");b.n(a.split(" "),function(a,e){b.Ob(e,c)||c.push(e)});this.className=c.join(" ")}else this.className=a})};m.m.prototype.xd=function(){this.n(function(){if(this.className.length!=0){var a=this.className.split(" ");b.n(["fsrLandscape"],function(c,d){var e=b.u(d,a);e!=-1&&a.splice(e,1)});this.className=a.join(" ")}})};m.m.prototype.z=function(a,c){if(b.M(a)&&c==u)return this[0].style[a];a=b.M(a)?m.m.Ec(a,c):a;return this.n(function(){var c=this,
e={opacity:1,zIndex:1,zoom:1};b.q(c.style)&&b.n(a,function(a,b){b=String(b);isNaN(Number(b))||(b=!e[a]?b+"px":b);c.style[a]=b})})};m.m.prototype.height=function(a){if(a)return this.z("height",a+(b.u("px",a)==-1?"px":""));a=typeof this[0].currentStyle!="undefined"?this[0].currentStyle:ha.defaultView.getComputedStyle(this[0],u);return a.height=="auto"?this[0].clientHeight:parseInt(a.height,10)};m.pa={};m.pa.xc=function(a){var c=0,b=0,e=a.document,f=e.documentElement;if(typeof a.innerWidth=="number"){c=
a.innerWidth;b=a.innerHeight}else if(f&&(f.clientWidth||f.clientHeight)){c=f.clientWidth;b=f.clientHeight}else if(e.body&&(e.body.clientWidth||e.body.clientHeight)){c=e.body.clientWidth;b=e.body.clientHeight}return{w:c,h:b}};m.pa.wc=function(a){var c=0,b=0,e=a.document,f=e.documentElement;if(typeof a.pageYOffset=="number"){b=a.pageYOffset;c=a.pageXOffset}else if(e.body&&(e.body.scrollLeft||e.body.scrollTop)){b=e.body.scrollTop;c=e.body.scrollLeft}else if(f&&(f.scrollLeft||f.scrollTop)){b=f.scrollTop;
c=f.scrollLeft}return{x:c,y:b}};m.pa.Qd=function(a,c,b){a.scrollTo(c,b)};m.m.prototype.append=function(a){a=m.m.Cb(a);return this.n(function(){for(var c=0;c<a.length;c++)this.appendChild(a[c])})};b.f.zc={};var E=b.f.zc,ja={},ra=["onload","onerror","onabort"];b.n(ra,function(a,c){ja[c]=function(){this.Qa(arguments.callee.Q==0?1:0);this.Ua=x};ja[c].Q=a});E.K=function(a,c){this.options=b.A({},a);this.Ua=x;this.event=c;this.yb=0;return this};E.K.prototype.Qa=function(a,c){if(this.Ua){this.Ua=x;this.status=
a;switch(a){case 1:(this.options.onSuccess||b.ua)(c);break;case 0:this.event?this.Jd():(this.options.onFailure||b.ua)(c);break;case -1:(this.options.onError||b.ua)(c)}}};E.K.prototype.Jd=function(){if(this.yb<3)this.Db();else this.onFailure()};E.K.prototype.Eb=function(a,c){this.Ua=s;var d=this,e=r.r.oa(b.A(a,{uid:b.now()})),e=b.Ga()+"//"+this.options.host+this.options.path+this.options.url+"?"+e,c=b.A({},ja,c),f=new Image;b.n(ra,function(a,b){f[b]=function(){var a=arguments.callee;a.sa.onload=a.sa.onerror=
a.sa.onabort=u;a.Tc.call(a.self,a.sa);a.sa=u};f[b].Tc=c[b];f[b].sa=f;f[b].self=d});f.src=e};E.K.prototype.send=function(a){this.Md=a;this.Db()};E.K.prototype.Ra=function(){var a=b.A(this.options.Zb,{protocol:b.Ga()});this.Eb(a,{onload:function(a){!this.options.Va||a.width==this.options.Va?this.Qa(1,a.width):this.Qa(0,a.width)},onerror:function(){this.Qa(-1)}})};E.K.prototype.Db=function(){var a;this.yb++;a=b.A({event:this.event,ver:this.yb},this.Md,a);this.Eb(a)};f.Pd={};b.cb=function(){B.cookie=
"fsr.a"+(g.site.cookie?"."+g.site.cookie:"")+"="+b.now()+";path=/"+(g.site.domain?";domain="+g.site.domain+";":";")+(g.site.secure?"secure":"")};I=$$FSR.sites;F=0;for(w=I.length;F<w;F++){var Z;b.C(I[F].path)||(I[F].path=[I[F].path]);v=0;for(G=I[F].path.length;v<G;v++)if(Z=b.R().toLowerCase().match(I[F].path[v])){g.siteid=F;g.site=$$FSR.sites[F];g.site.domain?"default"==g.site.domain&&(g.site.domain=u):g.site.domain=Z[0];g.site.secure||(g.site.secure=u);g.site.name||(g.site.name=Z[0]);b.n("files js_files image_files html_files css_files swf_files".split(" "),
function(a,c){g.site[c]||$$FSR[c]&&(g.site[c]=$$FSR[c])});break}if(Z)break}i.fsr$timer||(b.cb(),i.fsr$timer=setInterval(b.cb,1E3));f.t={};f.t.set=function(a,c,b){b=V(b);b[1][a]=c;b[0].set("cp",b[1])};f.t.get=function(a,c){return V(c)[0][a]};f.t.Ja=function(a,c){var b=V(c);delete b[1][a];b[0].set("cp",b[1])};f.t.append=function(a,c,b){b=V(b);b[1][a]=b[1][a]?b[1][a]+","+c:c;b[0].set("cp",b[1])};f.t.oa=function(a){var a=a||f.f.j(),c=a.get("sd");b.q(c)||(c=a.get("cd"));c=g.na[c];a={browser:t.l.name+" "+
t.l.version,os:t.l.kb,pv:a.get("pv"),url:L(a,"c"),ref_url:L(a,"ru"),locale:L(a,"l"),site:L(g.site.name),section:L(c.section),referrer:L(a,"r"),terms:L(a,"st"),sessionid:L(a,"rid"),replay_id:L(a,"mid"),flash:t.l.Sc};FSR.f.Bb.l.kb.match(/android|IOS|blackberry|firefox/i)&&(a.screen=screen.width+"x"+screen.height);if(l.meta.user_agent)a.user_agent=navigator.userAgent;if(l.analytics.google){var d=o.k.N("__utma"),c=o.k.N("__utmz");if(d&&d!=""){d=d.split(".");a.first=d[2];a.last=d[3];a.current=d[4];a.visits=
d[5]}if(c&&c!=""){var e=[];b.n(["utmgclid","utmcsr","utmccn","utmcmd","utmctr"],function(a,c){e.push(RegExp(c+"=([^\\|]*)"))});if(d=c.match(e[0])){a.source="Google";a.campaign="Google Adwords";a.medium="cpc"}else{if(d=c.match(e[1]))a.source=d[1];if(d=c.match(e[2]))a.campaign=d[1];if(d=c.match(e[3]))a.medium=d[1]}if(d=c.match(e[4]))a.keyword=d[1]}}c=f.f.j("cp")||{};a=b.A({},c,a||{});return r.r.oa(a,"cpp")};i.FSR.CPPS=f.t;i.FSR.CPPS.set=f.t.set;i.FSR.CPPS.get=f.t.get;i.FSR.CPPS.erase=f.t.Ja;i.FSR.CPPS.append=
f.t.append;i.ForeSee={};i.ForeSee.CPPS=f.t;i.ForeSee.CPPS.fsr$set=f.t.set;i.ForeSee.CPPS.fsr$get=f.t.get;i.ForeSee.CPPS.fsr$erase=f.t.Ja;i.ForeSee.CPPS.fsr$append=f.t.append;var j=m.m;f.ba=function(a,c){this.options=a;this.Id=c;this.Oa=x;var b=t.l;if("iphone,ipod,iphone,android,winmobile,blackberry,mobile".indexOf(b.platform)>-1)this.Oa=s;if(b.type=="Explorer"&&b.version<=6)this.Wc=s};f.ba.prototype.show=function(){if(!this.sb){j("object, embed").z("visibility","hidden");var a=this.Id.invite,c=a.isMDOT,
d=r.r.fa(g.site,"image_files"),e=this.Oa,h=f.f.j("l"),z=this.Vb=j('<div class="fsrC"></div>');c&&z.Ba("fsrM");var C=j('<div class="fsrFloatingContainer"></div>'),q=j('<div class="fsrFloatingMid"></div>'),n=j('<div class="fsrInvite"></div>'),l=j('<div class="fsrLogos"></div>');if(a.siteLogo){var y=a.siteLogo;typeof y==="object"&&(y=y.hasOwnProperty(h)?y[h]:y["default"]);y=j('<img src="'+d+y+'" class="fsrSiteLogo">');l.append(y)}y=j('<img src="'+d+'fsrlogo.gif" class="fsrCorpLogo">');l.append(y);for(var o=
j('<div class="fsrDialogs"></div>'),p=[],W=0,y="",P=0;P<a.dialogs.length;P++){var D=a.dialogs[P],v=D.locales;v&&v[h]&&(D=b.A(D,v[h]));if(v=D.closeInviteButtonText){y.length>0&&(y=y+" / ");y=y+v}c&&D.acceptButton.length>17&&(D.acceptButton=D.acceptButton.substr(0,15)+"...");var v=j('<div class="fsrDialog"><h1>'+D.headline+"</h1></div>").append(j('<p class="fsrBlurb">'+D.blurb+"</p>")),F;if(D.noticeAboutSurvey){F=j('<p class="fsrSubBlurb">'+D.noticeAboutSurvey+"</p>");v.append(F)}D.attribution&&v.append(j('<p class="fsrAttribution">'+
D.attribution+"</p>"));var A=D.mobileExitDialog;if(A){var J=j('<div class="fsrQuiz"></div>').append(j('<p class="fsrQuizQuestion">'+A.message+"</p>"));J.append(j('<input type="text" class="fsrNumber" id="fsrNumber'+P+'" />'));v.append(J)}if(A=D.quizContent){for(var J=j('<div class="fsrQuiz"></div>').append(j('<p class="fsrQuizQuestion">'+A.question+"</p>")),w=0;w<A.answers.length;w++){var E=A.answers[w],G=j('<p class="fsrAnswer" id="fsrAns'+P+"_"+w+'"><input name="fsrQuiz'+P+'" type="radio" id="fsrA'+
P+"_"+w+'"><label for="fsrA'+P+"_"+w+'">'+E.answer+"</label></p>");J.append(G);E.proceedWithSurvey?G.bind("click",function(a){return function(){var c=this.parentNode.parentNode;j(".fsrQuiz",c).z({display:"none"});j(".fsrSubBlurb",c).z({display:"block"});j(".fsrB",c).z({display:"block"});a.ia.call(a)}}(this)):G.bind("click",function(a,c,b){return function(){var d=this.parentNode.parentNode.parentNode;d.innerHTML='<div class="fsrDialog" style="margin-left: 0px;"><h1>'+c.cancelTitle+'</h1><p class="fsrBlurb">'+
c.cancelText+'</p><div class="fsrB" style="display: block;"><a class="declineButton">'+b+"</a></div></div>";j(".declineButton",d).bind("click",function(){a.V()});a.Dd.call(a);a.ia.call(a)}}(this,E,D.closeInviteButtonText))}v.append(J)}var I=D.locale,J=j('<div class="fsrB"></div>');++W;w=j('<div class="declineButtonContainer"><a href="javascript:void(0)" class="declineButton'+(b.X?" ie":"")+'" tabindex="'+W+'">'+D.declineButton+"</a></div>");++W;E=j('<div class="acceptButtonContainer"><a href="javascript:void(0)" class="acceptButton'+
(b.X?" ie":"")+'"  tabindex="'+W+'">'+D.acceptButton+"</a></div>");D.reverseButtons?J.append(E.z({"float":"left"})).append(w.z({"float":"right"})):J.append(w).append(E);j(".declineButton",J[0]).bind("click",function(a){return function(){a.V(I)}}(this));j(".acceptButton",J[0]).bind("click",function(a){return function(){a.da(I)}}(this));if(A){F.z({display:"none"});J.z({display:"none"})}p.push(v.append(J))}a=j('<div class="fsrFooter"><a href="http://privacy-policy.truste.com/click-with-confidence/ctv/en/www.foreseeresults.com/seal_m" title="Validate TRUSTe privacy certification" target="_blank"><img src="'+
d+'truste.png" class="fsrTruste"></a></div>');z.append(C.append(q.append(n.append(l).append(o).append(j('<div class="fsrCTermination"></div>')).append(a).append(j('<div class="fsrCTermination"></div>')))));if(!c){q=j('<a href="#" class="fsrCloseBtn" title="'+y+'"><div></div></a>');n.append(q);var L=this;q.bind("click",function(a){L.V();a&&a.preventDefault?a.preventDefault():i.event&&i.event.returnValue&&(i.eventReturnValue=x)})}n=i.document.body;n.children.length==0?n.appendChild(z[0]):n.insertBefore(z[0],
n.firstChild);this.Oa&&c&&z.z({height:O.innerHeight+"px"});if(this.Oa||b.X&&(t.l.version<=7||i.document.compatMode!="CSS1Compat")){n=c?"fsrM":"";this.Wc&&(n=n+" fsrActualIE6");z[0].className="fsrC ie6 "+n;var M=z[0];this.qb=function(){var a=m.pa.wc(i);M.style.left=a.x+"px";M.style.top=a.y+"px";a.y<=0&&(e&&t.l.platform!="blackberry")&&O.scrollTo(0,1);H.call(this)};j(i).bind("scroll",this.qb)}var H=this.ia=function(){var a=m.pa.xc(i);z.z({width:a.w+"px",height:a.h+"px"});C.z({position:"relative",left:(C[0].parentNode.offsetWidth-
C[0].offsetWidth)/2+"px",top:(C[0].parentNode.offsetHeight-C[0].offsetHeight)/2+"px"})};this.ia.call(this);j(i).bind("resize",this.ia);var Q=this.Dd=function(){C.z({width:o[0].offsetWidth+(C[0].offsetWidth-l[0].offsetWidth)+"px"})},N=this;setTimeout(function(){for(var a=0;a<p.length;a++){p[a].z({marginLeft:(a>0?15:0)+"px"});o.append(p[a])}Q.call(N);H.call(N);e&&O.scrollTo(0,1);var a=C[0].offsetHeight,c=C[0].parentNode.offsetHeight;if(a>c){C.Ba("fsrBulgeInstant");a="rotateX(0deg) rotateZ(0deg) scale("+
c/a+")";c=C[0].style;c.WebkitTransform=a;c.MozTransform=a;c.transform=a}else C.Ba("fsrBulge");j(".fsrLogos")[0].focus();setTimeout(function(){H.call(N)},1)},1);this.Ca=function(){if(c&&e&&b.q(i.orientation)){i.orientation==0||i.orientation==180?z.xd():z.Ba("fsrLandscape");setTimeout(function(){C.z({width:o[0].offsetWidth+(C[0].offsetWidth-l[0].offsetWidth)+"px"});H.call(this)},1)}};this.Ca.call(this);j(i).bind("orientationchange",this.Ca);var R=this;this.gb=function(a){(a.keyCode?a.keyCode:a.which)==
27&&R.V()};j(B).bind("keyup",this.gb);this.sb=s}};f.ba.prototype.Ma=function(){if(this.sb){this.ia&&j(i).Wa("rethis.scrollfnsize",this.ia);this.qb&&j(i).Wa("scroll",this.qb);this.Ca&&j(i).Wa("orientationchange",this.Ca);this.gb&&j(B).Wa("keyup",this.gb);this.Vb[0].parentNode.removeChild(this.Vb[0]);this.sb=x;j("object, embed").z("visibility","visible")}};f.ba.prototype.da=function(a){this.Ma();this.options.vb.accepted(a)};f.ba.prototype.V=function(a){this.Ma();this.options.vb.declined(a)};f.ba.prototype.Ta=
function(a){this.Ma();this.options.vb.Ta(a)};f.T={};f.T.zd=function(){if(b.q(b.Ya)&&b.q(b.la)&&b.q(b.la.mc)&&b.q(b.la.mc.Vc)){b.la.ce();f.f.j("mid",b.la.mc.Vc)}};f.T.Da=function(){if(b.q(b.Ya))var a=setInterval(function(){if(b.q(b.la)){clearInterval(a);b.la.be()}},250)};var sa={Explorer:5.5,Safari:2,Firefox:1.4,Opera:1E3},j=m.m,p={invite:k,qualifier:k,locale:k,canceled:x};b.g=function(a){b.A(this,{options:b.A({},a),Sb:x,Ub:x,pb:u,H:k,Fb:x,tc:x,Vd:k,Lb:[],ee:u,U:u,wa:u,Jb:u,Z:u});g.controller=this;
this.Od()};b.g.loaded=new r.F.G;b.g.Pb=new r.F.G;b.g.qc=new r.F.G;b.g.fb=new r.F.G;b.g.Qb=new r.F.G;b.g.Rb=new r.F.G;b.g.sc=new r.F.G;b.g.rc=new r.F.G;b.g.jc=new r.F.G;b.g.pc=new r.F.G;b.g.prototype.Od=function(){b.g.O.ab&&b.n([["loaded",b.g.loaded],["initialized",b.g.Pb],["surveyDefChanged",b.g.qc],["inviteShown",b.g.fb],["inviteAccepted",b.g.Qb],["inviteDeclined",b.g.Rb],["trackerShown",b.g.sc],["trackerCanceled",b.g.rc],["qualifierShown",b.g.jc],["surveyShown",b.g.pc]],function(a,c){b.D(b.g.O.ab[c[0]])&&
c[1].Gd(b.g.O.ab[c[0]])})};b.g.prototype.B=function(a){switch(a){case 3:return b.q(f.f.j("t"));case 2:return b.q(f.f.j("i"));case 1:return f.f.j("i")===1;case 4:return b.q(f.f.j("s"))}return x};b.g.prototype.load=function(){if(!(i.__$$FSRINIT$$__&&i.__$$FSRINIT$$__===s)){i.__$$FSRINIT$$__=s;g.auto&&this.execute(this.kc,s)}};b.g.prototype.execute=function(){if(g.enabled&&(l.ignoreWindowTopCheck||i==i.top)){for(var a=[],c=0;c<arguments.length;c++)a.push(arguments[c]);var c=b.shift(a),d=this;if(this.Sb)this.H!=
0&&c.apply(d,a);else{this.Lb.push({fn:c,args:a});if(!this.Ub){this.Ub=s;f.f.Yc(function(){d.eb()},g.embedded)}}}};b.g.prototype.eb=function(){b.g.loaded.J();this.bb=!b.q(f.f.j("v"));this.Na();if(this.bb&&b.q(b.Ya)){var a=f.I.yd;if(a.enabled&&this.H==1){a.url="/"+g.replay_id+".gif";var c=this,d=this;(new E.K(b.A({onSuccess:function(a){c.Gc(a);c.loaded()},onError:function(){d.loaded()}},a))).Ra();return}}this.loaded()};b.g.prototype.loaded=function(){this.Sb=s;this.bb&&f.f.j("v",this.H);var a=this;
setTimeout(function(){var c=b.shift(a.Lb);if(c){a.execute(c.fn,c.args);setTimeout(function(){a.loaded()},100)}},100)};b.g.prototype.Na=function(){this.Fb=s;var a=o.k.N(f.f.W("fsr.a"));this.B(3)||this.Jc();if(a){var c=this.lb();if(b.q(b.Ya)){c==200&&alert("Pooling number has not been updated.");g.replay_id=="site.com"&&alert("replay_id has not been updated.")}a=f.f.j("v");if(this.bb){a=1;if(!b.g.O.gd[t.l.platform]){p.message="Exit: Platform not supported";a=0}if(sa[t.l.type]&&t.l.version<=sa[t.l.type]){p.message=
"Exit: Browser not supported";a=0}if(this.S()){p.message="Exit: Met exclude criteria";a=0}if(o.k.N("fsr.o")){p.message="Exit: Opt-out cookie found";a=0}var d,e=new o.k(f.f.W("fsr.r"),{path:"/",domain:g.site.domain,secure:g.site.secure});if(d=e.get("d")){p.message="Exit: Persistent cookie found: "+d;a=-1}if(l.altcookie&&l.altcookie.name)if((d=o.k.N(l.altcookie.name))&&(!l.altcookie.value||l.altcookie.value==d)){p.message="Exit: Alternate persistent cookie found: "+d;a=-1}d=r.r.ja();if(a==1&&!(d>0&&
d<=c)){p.message="Exit: Not in pool: "+d;a=-2}if(c=e.get("i"))b.now()<e.get("e")&&(g.rid=c);g.rid||l.events.enabled&&l.events.id&&(g.rid=r.Nb());g.rid&&f.f.j("rid",g.rid);if(e=e.get("s")){f.f.j("sd",e);f.f.j("lk",1)}if((e=b.Ha())&&e!=""){l.meta.ref_url&&f.f.j("ru",e);if(l.meta.referrer){var c=e.match(/^(\w+:\/\/)?((\w+-?\w+\.?)+)\/[!]?/),h;c&&c.length>=3&&(h=c[2]);f.f.j("r",h)}l.meta.terms&&f.f.j("st",this.Pc(e)||"")}if(l.meta.entry){h=b.P(b.R());l.meta.entry_params||(h=h.replace(/(.*?)(\?.*)/g,"$1"));
f.f.j("ep",h)}a==1&&b.Pa(r.r.fa(g.site,"css_files")+l.invite.css,"link",b.ua);this.sd(f.f.j())}this.H=a;g.rid=f.f.j("rid");a=l.tracker.timeout;if(l.tracker.adjust&&b.q(f.f.j("f"))){a=f.f.j("to");h=(b.now()-f.f.j("f"))/1E3;a=Math.round((0.9*a+0.1*h*2)*10)/10;a=a<2?2:a>5?5:a}l.tracker.adjust&&f.f.j("to",a);this.H<1&&f.T.Da();b.g.Pb.J(this.H);o.k.ha("fsr.paused",{path:"/",domain:g.site.domain})}else this.H=0};b.g.prototype.kc=function(a){a&&f.f.j().Ja("pa");this.Ad();a=x;this.wa&&(a=this.hc(this.wa));
if(this.U){this.rd(this.U,a);a||this.hc(this.U);this.od(this.U);this.td()}this.ud()};b.g.prototype.Ad=function(){var a,c;g.sv=r.r.ja();this.pb=f.Aa("fsr.sp",f.f.Ka("fsr.sp"));if(b.q(f.f.j("cd")))this.Z=f.f.j("cd");g.cs=b.P(b.R());l.meta.url_params||(g.cs=g.cs.replace(/(.*?)(\?.*)/g,"$1"));l.meta.url&&f.f.j("c",g.cs);this.language();var d=f.f.j("pv")?f.f.j("pv")+1:1;f.f.j("pv",d);d=f.f.j("lc")||{};a=this.$c();if(a.length!=0){for(c=a.length;0<c;){c=g.na[a[0]];c.idx=a[0];a="d"+c.idx;this.Ib(c.criteria);
d[a]||(d[a]={v:0,s:x});c.lc=d[a].v=d[a].v+1;c.ec=d[a].e||0;c.type="current";this.Gb(c);var e=this.Zc(c),e=this.Mc(e,c.lc,c.ec);if(e>-1){c.ls=d[a].s=s;if(b.C(c.criteria.lf)){c.criteria.lf=c.criteria.lf[e];c.criteria.sp=c.criteria.sp[e];c.pop.when=c.pop.when[e];b.C(c.invite.dialogs)&&(c.invite.dialogs=c.invite.dialogs[e])}if(c.pin){a=f.f.j("pn");(!b.q(a)||a>c.idx)&&f.f.j("pn",c.idx)}}else{c.ls=d[a].s=x;if(b.C(c.criteria.lf)){c.criteria.lf=c.criteria.lf[0];c.criteria.sp=c.criteria.sp[0];c.pop.when=c.pop.when[0];
b.C(c.invite.dialogs)&&(c.invite.dialogs=c.invite.dialogs[0])}}this.Hb(c);a=f.f.j("v");e=f.f.j("i");if(!b.q(e)&&a==1&&c.lb){a=r.r.ja();if(!(a>0&&a<=c.lb)){a=-2;f.f.j("v",a);this.de=a;f.T.Da()}}this.U=c;this.Jb=c.idx;break}f.f.j("lc",d)}if(b.q(this.Z)&&this.Z!=this.Jb&&this.Z<g.na.length){c=g.na[this.Z];c.idx=this.Z;a="d"+c.idx;this.Ib(c);c.lc=d[a].v||0;c.ls=d[a].s||x;c.type="previous";this.Gb(c);this.Hb(c);this.wa=c;this.Z=c.idx;b.g.qc.J(this.wa,this.U)}};b.g.prototype.hc=function(a){return this.H<
0?x:this.wd(a)?s:this.ic(a)};b.g.prototype.rd=function(a,c){if(!(this.H<0)){f.f.j("cd",a.idx);if(!c&&a.ls&&!f.f.j("lk")){var d=f.f.j("pn");b.q(d)&&d<a.idx||f.f.j("sd",a.idx)}}};b.g.prototype.od=function(a){if(!(this.H<0)){if(this.B(1)&&!this.B(4)){this.$(a,"pop",this.cc);this.$(a,"cancel",this.Ea)}this.B(2)||this.$(a,"attach",this.mb);this.B(3)&&this.$(a,"pause",this.pause)}};b.g.prototype.wd=function(a){if(!this.Cd(a)||!this.B(3))return x;ka(this,a,"tracker");return s};b.g.prototype.Cd=function(a){if(!a.ls)return x;
if(a.type==="previous"){if(a.pop.when!=="later"||a.pop.after!=="leaving-section")return x}else if(a.type==="current"&&a.pop.when!=="now")return x;return s};b.g.prototype.ic=function(a){var c=s;this.Bd(a)||(c=x);if(c){this.qd(a);ka(this,a,"invite")}return c};b.g.prototype.Bd=function(a){if(!a.invite)return x;var c=this.B(2);if(a.invite.type&&a.invite.type==="static")return x;if(a.invite.type&&a.invite.type==="dynamic"&&c)return s;if(c)return x;c=b.P(b.R());if(a.invite.include){var d=s;a.invite.include.local&&
(d=this.ib(a.invite.include.local,c));if(!d){this.uc(a);return x}}if(a.invite.exclude){d=x;(d=this.ib(a.invite.exclude.local||[],c))||(d=this.ib(a.invite.exclude.referrer||[],b.P(b.Ha())));d||(d=b.g.O.S&&b.D(b.g.O.S.ga)?b.g.O.S.ga():x);if(d){this.uc(a);return x}}c=a.type==="previous"?"onexit":"onentry";return a.invite&&a.invite.when!=c||!a.ls?x:a.sv>0&&a.sv<=a.criteria.sp};b.g.prototype.qd=function(a){var c=a.alt;if(c)for(var b=r.r.ja(),e=0,f=0,g=c.length;f<g;f++){e=e+c[f].sp;if(b<=e){if(c[f].url){a.pop.what=
"url";a.pop.url=c[f].url}else if(c[f].script){a.pop.what="script";a.pop.script=c[f].script}delete a.invite;break}}};b.g.prototype.Xc=function(a,c){switch(c){case "invite":this.Hc(a);break;case "tracker":this.bc(a)}};b.g.prototype.ib=function(a,c){for(var b=0,e=a.length;b<e;b++)if(c.match(a[b]))return s;return x};b.g.prototype.uc=function(a){var c=f.f.j("lc");a.ec=c["d"+a.idx].e=(c["d"+a.idx].e||0)+1;f.f.j("lc",c)};b.g.prototype.Hc=function(a){var c=this.ga,d=this;if(l.mode==="hybrid")c=this.Lc;(new E.K(b.A({onSuccess:function(){c.call(d,
a)},onError:function(){c.call(d,a)}},f.I.B))).Ra()};b.g.prototype.Lc=function(a){var c=this.ga,d=this;(new E.K(b.A({Zb:{"do":0},success:f.I.B.Va,onSuccess:function(){c.call(d,a)}},f.I.domain))).Ra()};b.g.prototype.$=function(a,c,b){if(a.links)for(var e=0,c=a.links[c]||[],f=0,g=c.length;f<g;f++)e=e+this.link(c[f].tag,c[f].attribute,c[f].patterns||[],c[f].qualifier,b,a,{sp:c[f].sp,when:c[f].when,invite:c[f].invite,pu:c[f].pu,check:c[f].check})};b.g.prototype.link=function(a,c,d,e,f,g,i){var q=this,
n=0;b.n(d,function(d,l){n=n+j(a+"["+c+"*="+l+"]").bind("click",function(){e&&b._qualify(e);f.call(q,g,i)}).length});return n};b.g.prototype.Gb=function(a){var c=a.criteria.lf;b.Tb(c)&&(a.criteria.lf={v:c,o:">="})};b.g.prototype.Zc=function(a){var c=a.criteria.lf;b.Y(c)&&(c=[a.criteria.lf]);return c};b.g.prototype.Mc=function(a,c,b){for(var e=-1,f=0,g=a.length;f<g;f++)a[f].o==">="&&c>=a[f].v?e=f:a[f].o=="="&&c-b==a[f].v?e=f:a[f].o==">"&&c>a[f].v&&(e=f);return e};b.g.prototype.S=function(){var a=l.exclude,
c=b.g.O.S&&b.D(b.g.O.S.global)?b.g.O.S.global():x;return!a?c:this.match(a)||c};b.g.prototype.Hb=function(a){a.sv=g.sv;b.C(a.criteria.sp)&&(a.criteria.sp=a.criteria.sp[(new Date).getDay()]);var c=a.name+(a.section?"-"+a.section:""),d=c+(p.locale?"-"+p.locale:"");a.criteria.sp=this.pb.get(c)||this.pb.get(d)||a.criteria.sp;a.invite!==x&&(a.invite=b.ta(l.invite,a.invite||{}));b.n(["tracker","survey","qualifier","cancel","pop"],function(c,d){a[d]=b.ta(l[d],a[d]||{})});a.repeatdays=l.repeatdays||a.repeatdays;
if(!b.C(a.repeatdays)){c=a.repeatdays;a.repeatdays=[c,c]}};b.g.prototype.Ld=function(){if(g.enabled&&!this.tc&&this.Fb){this.tc=s;this.Kd()}};b.g.prototype.Kd=function(){p.invite==0&&f.f.log("103");l.previous&&f.f.j("p",g.cs);l.tracker.adjust&&f.f.j("f",b.now())};b.g.prototype.$c=function(){for(var a=[],c=g.na,b=0,e=c.length,f=0;b<e;b++)if(!(c[b].site&&c[b].site!=g.site.name)&&this.match(c[b].include)){a[f++]=b;break}return a};b.g.prototype.match=function(a){var c=x;b.n([["urls",b.R()],["referrers",
b.Ha()],["userAgents",navigator.userAgent]],function(d,e){b.n(a[e[0]]||[],function(a,d){if(b.P(e[1]).match(d)){c=s;return x}});if(!c)return x});if(c)return s;b.n(a.cookies||[],function(a,b){var d;if(d=o.k.N(b.name))if(d.match(b.value||".")){c=s;return x}});if(c)return s;var d=f.Aa("fsr.ipo",f.f.Ka("fsr.ipo")),e=a.variables;if(e)for(var h=0,g=e.length;h<g;h++){var i=e[h].name,q=e[h].value;if(!(i==l.ipexclude&&d.get("value")==1)){if(!b.C(i)){i=[i];q=[q]}for(var n,j=s,y=0,r=i.length;y<r;y++){try{n=(new Function("return "+
i[y]))();if(n===k||n===u)n=""}catch(p){n=""}var m;if(m=n||n===""){a:{m=n;var t=q[y];b.C(t)||(t=[t]);for(var v=0,w=t.length;v<w;v++)if((m+"").match(t[v])){m=s;break a}m=x}m=!m}if(m){j=x;break}}if(j)return s}}return x};b.g.prototype.lb=function(){var a=(new Date).getHours(),c=100;b.q(l.pool)&&(c=l.pool);var d=f.Aa("fsr.pool",f.f.Ka("fsr.pool")),c=d&&d.get("value")==1?100:c;b.C(c)||(c=[{h:0,p:c}]);for(var d=100,e=0,g=c.length;e<g;e++)a>=c[e].h&&(d=c[e].p);return d};b.g.prototype.Gc=function(a){var c=
r.r.ja();if(!(c>0&&c<=a)){this.H=-2;f.f.j("v",this.H);f.T.Da()}};b.g.prototype.ga=function(a){var c=this;b.A(p,{invite:0,repeatoverride:l.repeatoverride||x});f.f.j("i",p.invite);p.repeatoverride||this.rb(a,1);p.locale&&f.f.j("l",p.locale);if(a.invite){if(a.pop.when=="random"){var d=b.q(a.pop.now)?["now","later"]:["later","now"];if(r.r.ja()<=a.pop[d[0]]){a.invite.dialogs=a.invite.dialogs[d[0]];a.pop.when=d[0]}else{a.invite.dialogs=a.invite.dialogs[d[1]];a.pop.when=d[1]}}setTimeout(function(){b.g.fb.J(a,
f.f.j());f.f.log("100",g.cs);a.invite.type=="dhtml"?c.ob(a,"invite"):a.invite.type=="page"?c.jd(a):c.ob(a,"invite")},(a.invite.delay||0)*1E3);a.invite.timeout&&setTimeout(function(){k.Ma()},a.invite.timeout*1E3)}else setTimeout(function(){c.da(a)},0)};b.g.prototype.ob=function(a,c){var d=this;a[c].css?b.Pa(r.r.fa(g.site,"css_files")+a[c].css,"link",function(){d.nc(a)}):setTimeout(function(){d.nc(a)},100)};b.g.prototype.nc=function(a){function c(c){b.V(a,c)}var b=this,e={vb:{href:r.r.fa(g.site,"image_files"),
accepted:function(c){b.da(a,c)},declined:c,qualified:function(c){b.Ta(a,c)},close:c}};p.type=0;(new f.ba(e,a)).show()};b.g.prototype.da=function(a,c){b.g.Qb.J(a,f.f.j());if(c){p[c]=c;f.f.j("l",c)}p.invite=1;f.f.log("101");f.f.j("i",1);a.lock&&f.f.j("lk",1);this.rb(a,0);f.T.zd();this.nd(a);this.closed(a)};b.g.prototype.V=function(a,c){b.g.Rb.J(a,f.f.j());if(c){p[c]=c;f.f.j("l",c)}p.invite=-1;f.f.log("102");f.f.j("i",-1);this.rb(a,1);f.T.Da();this.closed(a)};b.g.prototype.closed=function(a){a=a.invite?
a.invite.hide:[];b.C(a)?b.n(a,function(a,b){j("#"+b).z("visibility","visible")}):j(a).z("visibility","visible")};b.g.prototype.Ta=function(a,c){if(c){p[c]=c;f.f.j("l",c)}p.qualifier=1;f.f.log("301");this.vd(a)};b.g.prototype.ed=function(a){p.repeatoverride=a==1};b.g.prototype.nd=function(a){if(a.pop.when=="later"){a.pop.tracker&&this.gc(a);this.$(a,"pop",this.cc);this.$(a,"cancel",this.Ea);this.$(a,"pause",this.pause)}else if(a.pop.when=="now")this.fc(a);else if(a.pop.when=="both"){this.gc(a);this.nb(a)}};
b.g.prototype.fc=function(a){f.f.j("s",1);switch(a.pop.what){case "survey":this.nb(a);break;case "qualifier":this.kd(a);break;case "url":this.md(a);break;case "script":this.ld(a)}};b.g.prototype.vd=function(a){!p.canceled?this.nb(a):this.ac(a)};b.g.prototype.bc=function(a,c){this.B(3)?this.oc(a,c):this.fc(a)};b.g.prototype.nb=function(a){b.g.pc.J(a,f.f.j());var c=a.survey,d=a.pop;this.dc(f.f.Uc(a,d.now),c.width,c.height,d.pu,"400")};b.g.prototype.hd=function(a){var c=l.survey,b="feedback",e=p.locale;
a&&(b=b+("-"+a));e&&(b=b+("-"+e));this.dc(b,c.width,c.height,x,"600")};b.g.prototype.dc=function(a,c,d,e,h){var l=f.I.Hd,j=new Date-0+"_"+Math.round(Math.random()*1E13),q=r.r.hash(j),a=r.r.oa({sid:a,cid:g.id,pattern:g.cs,a:j,b:q,c:b.zb,version:g.version}),j=f.t.oa();this.pop(h,b.Ga()+"//"+l.host+l.path+l.url+"?"+a+"&"+j,(i.screen.width-c)/2,(i.screen.height-d)/2,c,d,e);f.f.log(h,g.cs)};b.g.prototype.gc=function(a){if(!this.B(3)){b.g.sc.J(a,f.f.j());i.fsr$timer=setInterval(b.cb,1E3);this.Sa(a.tracker,
s,"200")}};b.g.prototype.kd=function(a){b.g.jc.J(a,f.f.j());this.Sa(a.qualifier,a.pop.pu,"300",a.pop.now)};b.g.prototype.jd=function(a){b.g.fb.J(a,f.f.j());this.Sa(a.invite,x,"_self")};b.g.prototype.ac=function(a){this.Sa(a.cancel,x,"500")};b.g.prototype.cc=function(a,c){var d=s;if(!this.B(4)){b.D(c.B)&&(d=c.B());d&&this.bc(a,c)}};b.g.prototype.Ea=function(a){if(!f.f.j("lk")&&this.B(3)){var c=O.open("","fsr200");if(c){b.g.rc.J(a,f.f.j());c.close()}}};b.g.prototype.oc=function(a,b){var d=this;if(t.l.type!=
"Firefox"||!a.qualifier.content)f.f.j("fo",b&&b.pu?2:1);else{this.Ea(a);setTimeout(function(){f.f.log("300",g.cs);d.ob(a,"qualifier")},(a.qualifier.delay||0)*1E3)}};b.g.prototype.Sa=function(a,c,d,e){this.page(a);var h=(i.screen.width-a.width)/2,l=(i.screen.height-a.height)/2,j=r.r.fa(g.site,"html_files")+(a.url.pop||a.url),q={siteid:g.siteid,name:g.site.name,domain:g.site.domain};e&&(q.when=e);e=r.r.oa(q);j=j+("?"+e);e=d;if(g.storageOption==="window"){e=b.f.JSON.parse(i.name);e.popOther=d;e=b.f.JSON.stringify(e)}this.pop(e,
j,h,l,a.width,a.height,c);f.f.log(d,g.cs)};b.g.prototype.mb=function(a,b){if(!this.B(2)){var d=this;b.sp&&(a.criteria.sp=b.sp);if(b.when||b.qualifier)a.pop.when=b.when;if(a.sv>0&&a.sv<=a.criteria.sp){p.locale&&f.f.j("l",p.locale);b.invite?this.ic(a):setTimeout(function(){d.da(a)},0)}}};b.g.prototype.md=function(a){var b=l.survey.width,d=l.survey.height;this.pop("Other",a.pop.url,(i.screen.width-b)/2,(i.screen.height-d)/2,b,d)};b.g.prototype.ld=function(a){b.Pa(a.pop.script,"script")};b.g.prototype.pause=
function(a){!b.q(a)||a?f.f.j("pa","1"):f.f.j("pa","0")};b.g.prototype.pop=function(a,b,d,e,f,g,l){var j="",n=a;if(a!="_self"){n="fsr"+a;j="location=0,status=0,scrollbars=1,resizable=1,width="+f+",height="+g+",left="+d+",top="+e+",toolbar=0,menubar=0"}if(t.l.platform=="winmobile")setTimeout(function(){i.location=b},10);else if((a=i.open(b,n,j,x))&&l){a.blur();i.focus()}};b.g.prototype.language=function(){var a=l.language;if(a){p.locale=a.locale;if(a.src){var c=p.locale,d,e,h=a.type;switch(a.src){case "location":d=
b.P(b.R());break;case "cookie":d=h&&h=="client"?o.k.N(a.name):f.f.j("lang");break;case "variable":b.C(a.name)||(a.name=[a.name]);for(e=0;e<a.name.length;e++){var j=new Function("return "+a.name[e]);if(h&&h=="client")try{d=j.call(i)}catch(m){d=k}else d=g[a.name];if(d)break}break;case "meta":if((e=ha.getElementsByName(a.name)).length!=0)d=e[0].content;break;case "navigator":d=navigator.browserLanguage||navigator.language;break;case "function":b.D(a.value)&&(d=a.value.call(i,a,this))}d=d||"";a=a.locales||
[];h=0;for(j=a.length;h<j;h++){b.C(a[h].match)||(a[h].match=[a[h].match]);var q;e=0;for(var n=a[h].match.length;e<n;e++)if(q=d.match(a[h].match[e])){c=a[h].locale;break}if(q)break}p.locale=c}}};b.g.prototype.page=function(a){var c=f.f.j("l");if(c)for(var d=a.locales||[],e=0,g=d.length;e<g;e++)if(d[e].locale==c){b.$a("url",d[e],a);b.$a("width",d[e],a);b.$a("height",d[e],a)}};b.g.prototype.Ib=function(a){var b=p.locale;if(b)for(var d=a.locales||[],e=0,f=d.length;e<f;e++)if(d[e].locale==b){a.sp=d[e].sp;
a.lf=d[e].lf;break}};b.g.prototype.Pc=function(a){var a=b.P(a||b.Ha()),c,d=u;b.n(["q","p","query"],function(b,c){if(d=a.match(RegExp("[?&]"+c+"=([^&]*)")))return x});if(!d)return c;(c=decodeURI(d[1]))&&(c=c.replace(/\+/g," "));return c};b.g.prototype.rb=function(a,c){if(!p.repeatoverride&&a.repeatdays&&a.repeatdays[c]){var d=new o.k(f.f.W("fsr.r"),{path:"/",domain:g.site.domain,secure:g.site.secure,duration:a.repeatdays[c]}),e=d.get();e.d=a.repeatdays[c];d.ra();l.altcookie.name&&o.k.write(l.altcookie.name,
l.altcookie.value,{path:l.altcookie.path,domain:l.altcookie.domain,secure:g.site.secure,duration:l.altcookie.persistent?a.repeatdays[c]:u});var h=l.events;if(h.pd){e.i=g.rid;var i=new Date;i.setDate(i.getDate()+h.pd);e.e=i.getTime();a.lock&&(e.s=a.idx);d.ra()}l.mode=="hybrid"&&(new E.K(b.A({Zb:{"do":1,rw:a.repeatdays[c]*1440}},f.I.domain))).Ra()}};b.g.prototype.td=function(){var a=l.cpps;if(a)for(var c in a)if(a.hasOwnProperty(c)){var d=a[c],e="",h,m,p=d.mode,q=p&&p=="append"?f.t.append:f.t.set;if(d.$b)if(e=
FSR.t.get(c)){for(var p=x,n=0,t=d.$b.length;n<t;n++)if(e===d.$b[n]){p=s;break}if(p)continue}switch(d.source.toLowerCase()){case "url":m=function(){var a=c,e,f=d.patterns||[],g=q;return function(){for(var c=0,d=f.length;c<d;c++)if(b.P(b.R()).match(f[c].regex)){e=f[c].value;break}e&&e!=""&&g(a,e)}};break;case "parameter":m=function(){var a=c,b=d.name,e=q,f;return function(){(f=r.r.Yb(b))&&f!=""&&e(a,f)}};break;case "cookie":m=function(){var a=c,b=d.name,f=q;return function(){(e=o.k.N(b))&&e!=""&&f(a,
e)}};break;case "variable":m=function(){var a=c,b=d.name,e=q,f;return function(){try{f=(new Function("return "+b)).call(i);if(f===k||f===u)f=x}catch(c){f=x}f&&f!=""&&e(a,f)}};break;case "meta":m=function(){var a=c,b=d.name,e=q,f;return function(){if((h=ha.getElementsByName(b)).length!=0)f=h[0].content;f&&f!=""&&e(a,f)}};break;case "function":m=function(){var a=c,e=q,f,h=d;return function(){b.D(h.value)&&(f=h.value.call(i,c,h,g.controller));f&&f!=""&&e(a,f)}};break;case "static":m=function(){var a=
c,b=q,e=d.value;return function(){e&&e!=""&&b(a,e)}}}d.on&&d.on!="load"&&d.query?j(d.query).bind(d.on,m()):m()()}};b.g.prototype.sd=function(a){var b=l.cpps;if(b)for(var d in b)if(b.hasOwnProperty(d)){var e=b[d];e.init&&f.t.set(d,e.init,a)}};b.g.ca=function(a,b,d,e){var g=f.f.j("ev")||{};if(e&&e!=""&&(!g["e"+b]||a.repeat)){g["e"+b]=(g["e"+b]||0)+1;f.f.log(d,e);f.f.j("ev",g)}};b.g.prototype.ud=function(){if(Math.abs(this.H)==1){var a=l.events;if(a.custom){var c=0,d;for(d in a.custom)if(a.custom.hasOwnProperty(d)){var e=
a.custom[d],f=a.codes[d];if(e.enabled){var m;switch(e.source.toLowerCase()){case "url":m=function(){var a=e,d=c,g=f,i=e.patterns||[],j;return function(){for(var c=0,e=i.length;c<e;c++)if(b.P(b.R()).match(i[c])){j=i[c];break}b.g.ca(a,d,g,j)}};break;case "parameter":m=function(){var a=e,d=c,g=e.name,i=f,j;return function(){j=r.r.Yb(g);b.g.ca(a,d,i,j)}};break;case "cookie":m=function(){var a=e,d=c,g=e.name,i=f,j;return function(){j=o.k.N(g);b.g.ca(a,d,i,j)}};break;case "variable":m=function(){var a=
e,d=c,g=e.name,j=f,l;return function(){try{l=(new Function("return "+g)).call(i);if(l===k||l===u)l=x}catch(c){l=x}b.g.ca(a,d,j,l)}};break;case "function":m=function(){var a=e,d=c,j=e.value,l=f,m;return function(){b.D(j)&&(m=j.call(i,a,e,g.controller));b.g.ca(a,d,l,m)}};break;case "static":m=function(){var a=e,d=c,g=e.value,i=f;return function(){b.g.ca(a,d,i,g)}}}e.on&&e.on!="load"&&e.query?j(e.query).bind(e.on,m()):m()();c++}}}}};b.g.prototype.Jc=function(){clearInterval(i.fsr$timer);o.k.ha(f.f.W("fsr.a"),
{path:"/",domain:g.site.domain,secure:g.site.secure})};b.popNow=function(a){$(a,"now")};b.popLater=function(a){$(a,"later")};b.popImmediate=function(){$(100,"now")};b.popFeedback=function(a){var b=g.controller;b.execute(b.hd,a)};b.clearTracker=function(){o.k.ha(f.f.W("fsr.r"),{path:"/",domain:g.site.domain,secure:g.site.secure});o.k.ha(f.f.W("fsr.s"),{path:"/",domain:g.site.domain,secure:g.site.secure})};b.stopTracker=function(a){g.controller.oc(b._sd(),{pu:a})};b.run=function(){var a=g.controller;
a.execute(a.kc)};b.invite=function(a,c,d){var e=g.controller;e.execute(e.mb,b._sd(),{sp:a,when:c,qualifier:d,invite:s})};b.popCancel=function(){g.controller.ac(b._sd())};b.showInvite=function(){g.controller.ga(b._sd())};b.close=function(){g.controller.Ea(b._sd())};b.pause=function(a){g.controller.pause(a)};b._sd=function(){return g.controller.U};b._pd=function(){return g.controller.wa};b._cancel=function(){p.canceled=s};b._qualified=function(a){k.Ta(a)};b._accepted=function(a){k.da(a)};b._declined=
function(a){k.V(a)};b._override=function(a){g.controller.ed(a)};b._language=function(a){if(a){p[a]=a;f.f.j("l",a)}};b._qualify=function(a){p.canceled=x;if(a){p.qid=a;f.f.j("q",a)}};b.Cookie={};b.Cookie.read=function(a){return o.k.N(a)};b.Storage={};b.Storage.read=function(a){return f.f.j(a)};b.$S=p;b.ka(function(){(new b.g).load();j(i).bind("beforeunload",function(){g.controller.Ld()})});b.g.O={ab:{loaded:K(),initialized:K(),surveydefChanged:K(),inviteShown:K(),inviteAccepted:K(),inviteDeclined:K(),
trackerShown:K(),trackerCanceled:K(),qualifierShown:K(),surveyShown:K()},S:{global:function(){return x},ga:function(){return x}},gd:{win32:s,mac:s,linux:s,iphone:x,ipad:x,ipod:x,android:x,blackberry:x,winmobile:x,wince:x,mobile:x,other:x}}})(window,{});})({});
}FSR($$FSR);