asmiPageSet = {
	cdn: (location.protocol == 'http:')?'http://cdn1.smartadserver.com':'https://ec-ns.sascdn.com',
	ppfix: (window.sas_ppfix)?sas_ppfix+'/':'',
	siteName: 'welt',
	siteId: '10034',
	siteIdMobile: '',
	scriptDomain: '//ww251.smartadserver.com',
	retgtHome: !1,
	adaud: !1,
	adrolay: !0,
	amazon: !0,
	criteo: !0,
	gmads: !0,
	krux: !0,
	kruxId: 'IaeXdO9D',
	meetrics: !0,
	nuggad: !0,
	nuggadId: '1982217550',
	nuggadIdMobile: '1712169372',
	remtreck: !0,
	pgWidth: 960,
	outerWrapper: 'pageWrapper',
	innerWrapper: 'viewport',
	innerWrapperArr: ["#viewport"],
	navi: '',
	pageCSS: '#ad3 {display:block!important;} #sas_5419 {clear:both;} #sas_6813 .fireplace {left: -20px;}',
	colorBg: !0,
	bgClick: !0,
	bgClickSelector: 'wallpaper|wpCont',
	stickySky: !0,
	waitArr: ["3648","3650","5419"],
	cursorCSS: 'body > * {cursor: auto;} html, body, a, #skyscraper, div[id^="sas_"] {cursor:pointer;}#viewport > * {cursor: auto;} #viewport {cursor:pointer;}',
	lblk: 3000,
	teadsPID: '21044',
	teadsSlot: function() {return ".artContent";},
	teadsMinSlot: '0',
	teadsBtf: !1,
	teadsFilter: function(){},
	teadsSize: {},
	teadsVolume: 70,
	teadsCSS: 'margin: 0px 0px 30px 30px; padding: 10px 0px 0px 50px',
	teadsSound: !0,
	isMobile: (/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|android|ipad|playbook|silk|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test((navigator.userAgent || navigator.vendor || window.opera)))?!0:!1
};
			
document.write('<script type="text/javascript" src="'+asmiPageSet.cdn+'/diff/251/smartad.js"></script>');