(function(){var h=function(){function h(a,b,c){function e(e){function g(b){function c(b){function g(a){a=d[a];return"undefined"!==typeof a?a.get(e):null}b=a+"/"+b.substr(2);var f;f=g(b);if(null!==f)return f;f=g(b+"/main");if(null!==f)return f;throw Error("Brak definicji modu\u0142u: "+b);}if(n(b))return c(b);if(b in e)b=e[b];else throw Error("Brak definicji zewn\u0119trznego modu\u0142u : "+b);return b}for(var k=[],f=0;f<b.length;f++)k.push(g(b[f]));return c.apply(null,k)}var g=null;m(b);return{get:function(a){null===
g&&(g=e(a));return g}}}function m(a){for(var b=0;b<a.length;b++){var c=a[b];n(c)||f.addName(c)}}function n(a){if("string"===typeof a)return 2<=a.length&&"./"===a.substr(0,2);throw Error("Spodziewano si\u0119 stringa");}var l=!1,f=function(){var a=[],b={};return{addName:function(c){if("string"===typeof c&&""!==c)"string"!==typeof b[c]&&(b[c]=c,a.push(c));else throw Error("Nieprawid\u0142owy typ parametru");},getExtendsModulesObject:function(b){if(a.length===b.length){for(var e={},g=0;g<a.length;g++)e[a[g]]=
b[g];return e}throw Error("nieprawid\u0142owe odga\u0142\u0119zienie programu");},getModulesName:function(){return a}}}(),d={};return{getDefine:function(a,b){return function(c,e){if(!1===l)d[a+"/"+b]=h(a,c,e);else throw Error("Nie mo\u017cna nic definiowa\u0107 po zako\u0144czeniu procesu konfiguracji");}},getRequire:function(a){var b=function(a,b){if(2===arguments.length)require(a,b);else throw Error("Spodziewano si\u0119 dw\u00f3ch argument\u00f3w");};b.toUrl=function(b){return require.toUrl(a+
"/"+b)};return b},install:function(){if(!1===l)l=!0,define(f.getModulesName(),function(){var a=Array.prototype.slice.call(arguments,0),a=f.getExtendsModulesObject(a);if("undefined"!==typeof d["./main"])a=d["./main"].get(a);else throw Error("Brak zdefiniowanego modu\u0142u: ./main");return a});else throw Error("Nieprawid\u0142owy stan");}}}();(function(h,m){h([],function(){var h=["ekstraklasa.tv"],l={_players:[],_topWeight:0.2,_minVisibility:0.7,_processing:!1,_currentPlayerIndex:!1,_delay:1500,_managerIsWorking:!1,
init:function(){var a=this;d(window,"message",function(b){a._onMessageIncoming(b.data)})},addPlayer:function(a){var b=this._players.length;a=new f(a,b);0===b&&a.sendMessage("IsManagerShouldWork?");this._players.push(a)},_startSilentPlay:function(){this._managerIsWorking=!0;var a=this;this._checkPlayersVisibility();setTimeout(function(){0===a._currentPlayerIndex&&a._onPlayerPriorityChange()},this._delay);this._addOnScrollListener()},_onPlayerPriorityChange:function(){this._players[this._currentPlayerIndex].sendMessage("silentPlay");
for(var a in this._players)this._players.hasOwnProperty(a)&&parseInt(a,10)!==parseInt(this._currentPlayerIndex,10)&&this._players[a].sendMessage("stopPlaying")},_addOnScrollListener:function(){var a=this;d(window,"scroll",function(){a._processing||a._checkPlayersVisibility()})},_updatePlayersVisibility:function(){for(var a in this._players)this._players.hasOwnProperty(a)&&this._players[a].updateVisiblity()},_checkPlayersVisibility:function(){if(this._managerIsWorking){var a=this;this._processing=
!0;setTimeout(function(){a._updatePlayersVisibility();var b=!1,c=0,e;for(e in a._players)a._players.hasOwnProperty(e)&&(a._players[e].visibility>a._players[c].visibility||a._players[e].visibility===a._players[c].visibility&&a._players[e].priority<a._players[c].priority)&&(c=e);!a._currentPlayerIndex&&a._players[c].visibility>=a._minVisibility&&(a._currentPlayerIndex=c,b=!0);a._currentPlayerIndex&&a._players[a._currentPlayerIndex].visibility+a._topWeight<a._players[c].visibility&&(a._currentPlayerIndex=
c,b=!0);b&&a._onPlayerPriorityChange();a._processing=!1},this._delay)}},_onMessageIncoming:function(a){"ManagerShouldWork"===a&&this._startSilentPlay();"ManagerShouldStop"===a&&(this._managerIsWorking=this._processing=!1)}},f=function(a,b){this.priority=b;this.Object=a;this.updateVisiblity();this.loaded=!1;var c=this;d(this.Object,"load",function(){c.loaded=!0})};f.prototype.updateVisiblity=function(){var a=document.documentElement.scrollTop,b="undefined"!==typeof window.innerHeight?window.innerHeight:
document.documentElement.clientHeight,c=this.getOfset().top,e=this.Object.clientHeight,g=0<a-c?a-c:0,a=0<e+c-a-b?e+c-a-b:0;this.visibility=0!==e?(0<e-(g+a)?e-(g+a):0)/e:0};f.prototype.getOfset=function(){var a,b={top:0,left:0};a=(this.Object&&this.Object.ownerDocument).documentElement;"undefined"!==typeof this.Object.getBoundingClientRect&&(b=this.Object.getBoundingClientRect());return{top:b.top+document.documentElement.scrollTop-a.clientTop,left:b.left+document.documentElement.scrollLeft-a.clientLeft}};
f.prototype.sendMessage=function(a){var b=this;this.loaded?b.Object.contentWindow.postMessage(a,"*"):d(this.Object,"load",function(){b.Object.contentWindow.postMessage(a,"*")})};var d=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)};l.init();return{runDomElement:function(a){var b=a.getAttribute("data-params-type"),c=a.getAttribute("data-params-mvp"),e=a.getAttribute("data-params-autostart"),g=a.getAttribute("data-params-playRelated"),d=JSON.parse(a.getAttribute("data-params")),
f=null!==d?d.parameters.url:null,d=null!==d?d.parameters.ust_plugin:null;if(null!==typeof b&&null!==typeof c||null!==typeof f)if(-1!==h.indexOf(window.location.host)&&"Playlist"!==d)e=document.createElement("div"),e.className="mvpContainer",d=document.createElement("div"),d.className="mvp",d.id="mvp:"+c,g=document.createElement("div"),g.className="mvp-params-configuration",g.hidden="hidden",g.style.visibility="hidden",c=document.createElement("div"),c.className="mvp:enableAds",c.innerHTML="1",f=document.createElement("div"),
f.className="mvp:autoplay",f.innerHTML="embed-detail"===b?"1":"0",b=document.createElement("div"),b.className="mvp:autoplayRelated",b.innerHTML="1",g.appendChild(c),g.appendChild(f),g.appendChild(b),d.appendChild(g),e.appendChild(d),a.parentNode.appendChild(e),a.parentNode.removeChild(a),a=document.getElementsByTagName("head")[0],script=document.createElement("script"),script.type="text/javascript",script.defer=!0,script.src="http://lib.onet.pl/mvp/mvp-loader.js",a.appendChild(script);else{d=document.createElement("div");
d.className="o_playListEmbedWrapper mvp-embed-wrapper";var k=document.createElement("iframe");k.className="o_playListEmbed mvp-embed";k.setAttribute("allowfullscreen","");d.style.position="relative";d.style.padding="56.25% 0 80px";d.style.height="0";k.style.position="absolute";k.style.top=0;k.style.left=0;k.style.width="100%";k.style.height="100%";b=null!==b?"http://onet.tv/"+b+".html?mvp="+c:f;c="";"undefined"!==typeof onetAds.DV&&(b+="&dv="+onetAds.DV);"undefined"!==typeof onetAds.dr&&(c+="dr="+
encodeURIComponent(onetAds.dr));"undefined"!==typeof offline&&offline&&"undefined"!==typeof originUrl?b+="&du="+encodeURIComponent(originUrl):"undefined"!==typeof onetAds.du&&(b+="&du="+encodeURIComponent(unescape(onetAds.du)));"undefined"!==typeof onetAds.target&&(b+="&site="+onetAds.target);"undefined"!==typeof onetAds.mvpEpisode&&(b+="&mvpEpisode="+encodeURIComponent(onetAds.mvpEpisode));"undefined"!==typeof onetAds.mvpMovie&&(b+="&mvpMovie="+encodeURIComponent(onetAds.mvpMovie));"undefined"!==
typeof onetAds.mvpSeries&&(b+="&mvpSeries="+encodeURIComponent(onetAds.mvpSeries));"undefined"!==typeof onetAds.mvpAdTarget&&""!==onetAds.mvpAdTarget&&(b+="&mvpAdTarget="+encodeURIComponent(onetAds.mvpAdTarget));"undefined"!==typeof $onet&&"undefined"!==typeof $onet.kwrd&&(b+="&mvpTestKwrd="+encodeURIComponent($onet.kwrd));g&&(b+="&playRelated="+encodeURIComponent(g));e&&(b+="&autoPlay="+encodeURIComponent(e));b="undefined"!==window.location.hash&&""!==window.location.hash?b+(window.location.hash+
"&"+c):b+("#"+c);k.src=b;d.appendChild(k);a.appendChild(d);l.addPlayer(k)}}}});Array.prototype.indexOf||(Array.prototype.indexOf=function(h,l){var f=this.length>>>0,d=Number(l)||0,d=0>d?Math.ceil(d):Math.floor(d);for(0>d&&(d+=f);d<f;d++)if(d in this&&this[d]===h)return d;return-1})})(h.getDefine(".","embedPlayerInit"),h.getRequire("."));(function(h,m){h(["./embedPlayerInit"],function(h){return{embedPlayerInit:h.runDomElement}})})(h.getDefine(".","main"),h.getRequire("."));h.install()})();
