(function (lib) { 
(function(lib,document,window){lib.getWindow=function(){var width,height,scrollLeft,scrollTop,scrollHeight,relativeScrollTop,db=document.body,de=document.documentElement;scrollHeight=Math.max(Math.max(db.scrollHeight,de.scrollHeight),Math.max(db.offsetHeight,de.offsetHeight),Math.max(db.clientHeight,de.clientHeight));if(window.pageYOffset!==void 0){scrollLeft=window.pageXOffset;scrollTop=window.pageYOffset;height=window.innerHeight;width=window.innerWidth;}else if(de.clientHeight){scrollLeft=de.scrollLeft;scrollTop=de.scrollTop;height=de.clientHeight;width=de.clientWidth;}else{scrollTop=db.scrollTop;scrollLeft=db.scrollLeft;height=db.clientHeight;width=db.clientWidth;}
relativeScrollTop=scrollTop/(scrollHeight-height);return{scrollTop:scrollTop,scrollHeight:scrollHeight,height:height,relativeScrollTop:relativeScrollTop,scrollLeft:scrollLeft,width:width};};}(lib,document,window));
(function(){lib.className=function(element,name,replace){var i,index={},classes=(element.className||'').split(' ');for(i=0;i<classes.length;i+=1){index[classes[i]]=i;}
i=index[name];if(replace===void 0){if(i===void 0){classes.push(name);}}else if(i>=0){if(index[replace]===void 0){classes[i]=replace;}else{classes.splice(i,1);}}
element.className=classes.join(' ');};}());
(function(){var x,frame,active=[];function enterframe(){var now,t;for(x=0;x<active.length;x+=1){t=active[x];now=new Date()-t.startTime;if(now>=t.time){t.currentValue=t.value;t.currentTime=t.time;t.element.style[t.property]=t.value+t.unit;t.remove();t.progress();t.complete();}else{t.currentTime=now;t.currentValue=t.easing(now,t.time,t.startValue,t.difference);t.element.style[t.property]=t.currentValue+t.unit;t.progress();}}}
function Tween(element,property,value,time,complete,progress,easing){this.element=element;this.property=property;this.value=value;this.time=time>0?time:0;this.easing=Tween[String(easing).toLowerCase()]||Tween.linear;this.complete=complete||this.complete;this.progress=progress||this.progress;}
Tween.prototype.start=function(){var s=this.element.style[this.property]?this.element.style[this.property]:window.getComputedStyle?window.getComputedStyle(this.element)[this.property]:this.element.currentStyle[this.property],n=parseFloat(s)||0;this.unit=s?s.replace(/^(\+|-)?\d+(\.\d+)?/,''):'';this.element.style[this.property]=n+this.unit;this.difference=this.value-n;this.currentValue=this.startValue=n;this.currentTime=0;this.startTime=new Date().getTime();active.push(this);if(!frame){frame=setInterval(enterframe,31);}
enterframe();return this;};Tween.prototype.remove=function(){var i;for(i=0;i<active.length;i+=1){if(active[i]===this){active.splice(i,1);x=i-1;break;}}
if(active.length===0){clearInterval(frame);frame=null;}
this.time=this.time-this.currentTime;this.currentTime=0;return this;};Tween.prototype.stop=function(){this.complete();this.remove();return this;};Tween.prototype.progress=function(){};Tween.prototype.complete=function(){};Tween.linear=function(n,t,p,d){return d*n/t+p;};Tween.easeinquad=function(n,t,p,d){return d*(n/=t)*n+p;};Tween.easeoutquad=function(n,t,p,d){return-d*(n/=t)*(n-2)+p;};lib.Tween=Tween;}());
(function(lib,document,window){var STATUS_HIDE=0,STATUS_PEEK=1,STATUS_SHOW=2;function Slide(widget){lib.slide=this;var spec=widget.spec||{};spec.scroll=spec.scroll||{};spec.scroll.peek=spec.scroll.peek||0;spec.scroll.show=spec.scroll.show||0;spec.scroll.peek=String(spec.scroll.peek).indexOf('%')>-1?parseFloat(spec.scroll.peek)/100:parseFloat(spec.scroll.peek);spec.scroll.show=String(spec.scroll.show).indexOf('%')>-1?parseFloat(spec.scroll.show)/100:parseFloat(spec.scroll.show);spec.scroll.max=Number(spec.scroll.max)||2000;spec.minWidth=spec.minWidth>=0?spec.minWidth:600;spec.timeShow=spec.timeShow>=0?spec.timeShow:500;spec.timeHide=spec.timeHide>=0?spec.timeHide:150;spec.cookieTTL=spec.cookieTTL>=0?spec.cookieTTL:86400000;spec.offsetHide=spec['adjustment-right-hide']||-20;spec.offsetPeek=spec['adjustment-right-peek']||0;this.spec=spec;this.container=null;this.uid=null;lib.Widget.call(this,widget);this.onscroll=lib.bind(this.onscroll,this);this.onresize=lib.bind(this.onresize,this);this.show=lib.bind(this.show,this);this.close=lib.bind(this.close,this);this.remove=lib.bind(this.remove,this);this.removeComplete=lib.bind(this.removeComplete,this);this.container.style.display='block';this.width=lib.getRect(this.container).width;this.container.style.right=-this.width+this.spec.offsetHide+'px';this.container.style.zIndex=1234567850;this.showButton=lib.querySelector('#'+this.uid+' .showbtn');this.closeButton=lib.querySelector('#'+this.uid+' .hidebtn');if(lib.hasAdBlock()===1&&this.campaigns[0]>0){return;}
lib.className(this.showButton,'arrleft');lib.addEventListener(lib.event.CLICK,this.show,this.showButton);lib.addEventListener(lib.event.CLICK,this.close,this.closeButton);lib.addEventListener(lib.event.SCROLL,this.onscroll,document);lib.addEventListener(lib.event.SCROLL,this.onscroll,window);lib.addEventListener(lib.event.RESIZE,this.onresize,window);this.onscroll();this.onresize();}
Slide.prototype.addCSS=lib.Widget.prototype.addCSS;Slide.prototype.additionalScript=lib.Widget.prototype.additionalScript;Slide.prototype.getContainer=function(){return document.body.insertBefore(document.createElement('div'),document.body.firstChild);};Slide.prototype.onscroll=function(){var w=lib.getWindow(),s=this.spec;if(w.relativeScrollTop>=s.scroll.show||w.scrollHeight<=w.height||w.scrollTop>s.scroll.max){this.show();}else if(w.relativeScrollTop>=s.scroll.peek){this.peek();}else{this.hide();}};Slide.prototype.onresize=function(){var w=lib.getWindow(),s=this.spec,m=w.width>s.minWidth;if(m&&this.status===STATUS_PEEK&&w.relativeScrollTop>=s.scroll.show){this.show();}else if(!m&&this.status===STATUS_SHOW){this.peek();}};Slide.prototype.hide=function(){if(this.status!==STATUS_HIDE){lib.className(this.showButton,'arrright','arrleft');this.removeTween();this.tween=new lib.Tween(this.container,'right',-this.width+this.spec.offsetHide,this.spec.timeHide).start();this.status=STATUS_HIDE;}
return false;};Slide.prototype.peek=function(){if(this.status!==STATUS_PEEK){lib.className(this.showButton,'arrright','arrleft');this.removeTween();this.tween=new lib.Tween(this.container,'right',-this.width+this.spec.offsetPeek+lib.getRect(this.showButton).width,this.spec.timeHide).start();this.status=STATUS_PEEK;}};Slide.prototype.show=function(e){if(e){lib.removeEventListener(lib.event.SCROLL,this.onscroll,document);lib.removeEventListener(lib.event.SCROLL,this.onscroll,window);lib.removeEventListener(lib.event.RESIZE,this.onresize,window);if(this.status===STATUS_SHOW){this.peek();return false;}}
if(this.status!==STATUS_SHOW){lib.className(this.showButton,'arrleft','arrright');this.removeTween();this.tween=new lib.Tween(this.container,'right',0,this.spec.timeShow);this.tween.easing=lib.Tween.easeoutquad;this.tween.start();this.status=STATUS_SHOW;}
return false;};Slide.prototype.close=function(){lib.setCookie('slide.removed',1,new Date().getTime()+this.spec.cookieTTL);this.remove();};Slide.prototype.remove=function(){lib.placements[this.uid]=void 0;lib.removeEventListener(lib.event.CLICK,this.show,this.showButton);lib.removeEventListener(lib.event.CLICK,this.remove,this.closeButton);lib.removeEventListener(lib.event.SCROLL,this.onscroll,document);lib.removeEventListener(lib.event.SCROLL,this.onscroll,window);lib.removeEventListener(lib.event.RESIZE,this.onresize,window);lib.removeEventListener(lib.event.UNLOAD,this.remove);this.removeTween();this.status=STATUS_HIDE;this.tween=new lib.Tween(this.container,'right',-this.width,this.spec.timeHide);this.tween.easing=lib.Tween.easeinquad;this.tween.complete=this.removeComplete;this.tween.start();};Slide.prototype.removeComplete=function(){if(this.container.parentNode){this.container.parentNode.removeChild(this.container);}};Slide.prototype.removeTween=function(){if(this.tween){this.tween.remove();}};lib.Slide=Slide;}(lib,document,window));
}(PLISTA));